nextcloud/neon

packages/harbour/lib/main.dart, packages/harbour/lib/src/blocs/login.dart, packages/harbour/lib/src/harbour.dart, packages/harbour/lib/src/models/account.dart, packages/harbour/lib/src/pages/login/login.dart, packages/harbour/lib/src/utils/global.dart, packages/nextcloud/lib/src/client.dart, packages/nextcloud/test/client_test.dart, packages/nextcloud/test/helper.dart
Client part for https://github.com/nextcloud/server/pull/33296
=> Add proper user-agent

packages/harbour/lib/l10n/en.arb, packages/harbour/lib/l10n/localizations.dart, packages/harbour/lib/l10n/localizations_en.dart, packages/harbour/lib/src/apps/files/app.dart, packages/harbour/lib/src/apps/files/dialogs/choose_create.dart, packages/harbour/lib/src/apps/files/options.dart, packages/harbour/lib/src/apps/files/pages/main.dart, packages/harbour/lib/src/apps/files/widgets/browser_view.dart
Closes https://github.com/jld3103/nextcloud-harbour/issues/3
=> Warn users when up-/downloading big files

packages/nextcloud/test/helper.dart, packages/nextcloud/test/notifications_test.dart
Fixes https://github.com/jld3103/nextcloud-neon/issues/26
=> nextcloud: Fix random port already being used in tests

packages/neon/lib/src/apps/news/dialogs/add_feed.dart
Closes https://github.com/jld3103/nextcloud-neon/issues/41
=> neon: Paste from clipboard when adding news feed if it contains a URL

packages/neon/lib/l10n/en.arb, packages/neon/lib/l10n/localizations.dart, packages/neon/lib/l10n/localizations_en.dart, packages/neon/lib/src/models/account.dart, packages/neon/lib/src/pages/settings/account_specific_settings.dart, packages/neon/lib/src/pages/settings/nextcloud_app_specific_settings.dart, packages/neon/lib/src/pages/settings/settings.dart, packages/neon/lib/src/utils/global_options.dart, packages/neon/lib/src/utils/nextcloud_app_specific_options.dart, packages/settings/lib/src/options/option.dart
Closes https://github.com/jld3103/nextcloud-neon/issues/44
=> Implement resetting settings

packages/neon/lib/src/apps/news/blocs/articles.dart, packages/nextcloud/lib/src/nextcloud.openapi.dart, packages/nextcloud/lib/src/nextcloud.openapi.json, packages/nextcloud/lib/src/version_supported.dart, packages/nextcloud/test/news_test.dart, specs/news.json
Requires News 18.1.1, so best to wait a little longer (maybe until Nextcloud 25 release).
Edit: Extended version checking has been implemented so this can be merged safely.
=> nextcloud: Use news v1.3 API

packages/neon/lib/src/apps/news/blocs/articles.dart, packages/nextcloud/lib/src/helpers.dart, packages/nextcloud/lib/src/nextcloud.openapi.dart, packages/nextcloud/lib/src/nextcloud.openapi.json, packages/nextcloud/test/news_test.dart, specs/news.json
Fixes https://github.com/jld3103/nextcloud-neon/issues/80
=> Fix news api

packages/neon/lib/src/utils/request_manager.dart
Based on https://github.com/jld3103/nextcloud-neon/pull/84
=> Cleanup request manager

packages/dynamite/lib/src/openapi_builder.dart, packages/nextcloud/lib/src/nextcloud.openapi.dart, packages/nextcloud/lib/src/nextcloud.openapi.g.dart
based on https://github.com/jld3103/nextcloud-neon/pull/90
=> Fix oneOf, anyOf and allOf parsing

packages/neon/integration_test/screenshot_test.dart, packages/neon/lib/src/apps/news/app.dart, packages/neon/lib/src/apps/notifications/app.dart, packages/neon/lib/src/blocs/accounts.dart, packages/neon/lib/src/blocs/apps.dart, packages/neon/lib/src/blocs/apps.rxb.g.dart, packages/neon/lib/src/neon.dart, packages/neon/lib/src/pages/home.dart, packages/neon/lib/src/widgets/app_implementation_icon.dart
Closes https://github.com/provokateurin/nextcloud-neon/issues/119
=> Separate notifications from other apps

packages/dynamite/lib/src/models/schema.dart, packages/dynamite/lib/src/models/schema.g.dart, packages/dynamite/lib/src/openapi_builder.dart
https://json-schema.org/draft/2020-12/json-schema-validation.html#name-a-vocabulary-for-the-conten
=> dynamite: Support JSON encoded string fields as per spec

packages/nextcloud/lib/src/helpers.dart, packages/nextcloud/lib/src/nextcloud.openapi.dart, packages/nextcloud/lib/src/nextcloud.openapi.g.dart, packages/nextcloud/lib/src/nextcloud.openapi.json, packages/nextcloud/test/core_test.dart, specs/core.json
https://github.com/provokateurin/nextcloud-neon/issues/1
=> specs,nextcloud: Add autocomplete API

packages/nextcloud/lib/src/webdav/client.dart, packages/nextcloud/test/webdav.dart
Closes https://github.com/provokateurin/nextcloud-neon/issues/174
=> nextcloud: Support setting last modified time when uploading

.vscode/settings.json
setting up vscode to use fvm.
https://fvm.app/docs/getting_started/configuration/#vs-code
=> make vscode use fvm

packages/dynamite/lib/src/openapi_builder.dart
Without this we could generate annotations like:
```dart
@JsonKey(
fromJson: String.fromJsonString,
toJson: String.toJsonString,
)
```
=> fix contentString with a base object contentSchema

packages/dynamite/lib/src/openapi_builder.dart, packages/nextcloud/lib/src/nextcloud.openapi.dart
Also adding an assertion for anyOf :)
=> Relax oneOf assertion

packages/nextcloud/lib/src/nextcloud.openapi.dart, packages/nextcloud/lib/src/nextcloud.openapi.json, specs/core.json
=> fix security for loginFlow2

packages/neon/lib/src/apps/news/blocs/articles.dart, packages/neon/lib/src/apps/news/blocs/news.dart, packages/neon/lib/src/apps/notes/blocs/notes.dart, packages/neon/lib/src/apps/notifications/blocs/notifications.dart, packages/neon/lib/src/blocs/apps.dart, packages/neon/lib/src/utils/request_manager.dart, packages/neon/pubspec.lock
last thing needed for us to land built_value.
I don't know if it makes sense to merge as we're gonna need to rebase it anyways :woman_shrugging:.
I've just changed the Types from `List` to `Iterable`. We could also keep the types and just cast it to a list (`.toList()`)
=> migrate neon

packages/dynamite/lib/src/openapi_builder.dart
=> header serialization

packages/neon/lib/src/apps/news/blocs/articles.dart, packages/neon/lib/src/apps/news/blocs/news.dart, packages/neon/lib/src/apps/notes/blocs/notes.dart, packages/neon/lib/src/apps/notifications/blocs/notifications.dart, packages/neon/lib/src/blocs/apps.dart
Just tried to run neon and found #252 to be fairly bad.
I shouldn't have changed it last minute without testing (passing analysis != running app) :sweat_smile:
=> migrate neon fix

.gitmodules, packages/app/.gitignore, packages/app/de.provokateurin.neon.yaml
Closes https://github.com/provokateurin/nextcloud-neon/issues/259
=> Build flatpaks

packages/neon/neon/lib/neon.dart, packages/neon/neon/lib/src/app.dart, packages/neon/neon/lib/src/pages/home.dart, packages/neon/neon/lib/src/pages/login.dart, packages/neon/neon/lib/src/router.dart, packages/neon/neon_files/lib/widgets/browser_view.dart, packages/neon/neon_news/lib/pages/article.dart, packages/neon/neon_notes/lib/pages/note.dart
Closes https://github.com/provokateurin/nextcloud-neon/issues/5
=> Add proper files navigation

packages/neon/neon/lib/l10n/en.arb, packages/neon/neon/lib/l10n/localizations.dart, packages/neon/neon/lib/l10n/localizations_en.dart, packages/neon/neon_files/lib/neon_files.dart, packages/neon/neon_files/lib/options.dart, packages/neon/neon_files/lib/sort/files.dart, packages/neon/neon_files/lib/widgets/browser_view.dart, packages/neon/neon_files/pubspec.yaml
Closes https://github.com/provokateurin/nextcloud-neon/issues/15
=> Sort files

packages/neon/neon/lib/src/blocs/accounts.dart, packages/nextcloud/lib/src/nextcloud.openapi.dart, packages/nextcloud/lib/src/nextcloud.openapi.json, specs/core.json
Closes https://github.com/provokateurin/nextcloud-neon/issues/285
=> Delete app password when logging out

packages/neon/neon/lib/src/pages/home.dart
=> neon: fix drawer scrolling

packages/neon/neon/lib/src/pages/login.dart
fixes #297 
While being in here I simplified the layout. There shouldn't be any visual changes.
Was there a reason to have `Column`s inside a `ListView`?
This usually only slows down the layout and can be achieved in other ways but I hope I didn't overlook something.
=> neon: fix LoginPage overflow

.fvm/fvm_config.json, packages/app/android/build.gradle, packages/app/pubspec.lock, packages/app/pubspec.yaml, packages/app/test_driver/integration_test.dart, packages/dynamite/pubspec.yaml, packages/file_icons/pubspec.yaml, packages/neon/neon/lib/src/pages/login.dart, packages/neon/neon/lib/src/utils/app_implementation.dart, packages/neon/neon/lib/src/widgets/cached_image.dart, packages/neon/neon/pubspec.yaml, packages/neon/neon_files/pubspec.yaml, packages/neon/neon_news/lib/dialogs/feed_update_error.dart, packages/neon/neon_news/lib/pages/article.dart, packages/neon/neon_news/pubspec.yaml, packages/neon/neon_notes/pubspec.yaml, packages/neon/neon_notifications/pubspec.yaml, packages/nextcloud/pubspec.yaml, packages/settings/pubspec.yaml, packages/sort_box/pubspec.yaml, packages/spec_templates/pubspec.yaml
Replaces https://github.com/provokateurin/nextcloud-neon/pull/309 and https://github.com/provokateurin/nextcloud-neon/pull/308 since it was a total mess with the new flutter version...
Depends on https://github.com/provokateurin/nextcloud-neon/pull/311
=> Fix and update dependencies and flutter

packages/neon/neon_files/lib/blocs/browser.dart, packages/nextcloud/lib/src/webdav/file.dart
Fixes https://github.com/provokateurin/nextcloud-neon/issues/315
=> nextcloud,neon: Fix toWebDavFiles removing first entry

packages/neon/neon/lib/src/blocs/accounts.dart, packages/neon/neon/lib/src/pages/home.dart, packages/neon/neon/lib/src/utils/bloc.dart
Fixes https://github.com/provokateurin/nextcloud-neon/issues/317
Also noticed the capabilities were dispose in the home page which was wrong.
=> neon: Fix theme switching when switching accounts

packages/neon/neon/lib/l10n/en.arb, packages/neon/neon/lib/l10n/localizations.dart, packages/neon/neon/lib/l10n/localizations_en.dart, packages/neon/neon/lib/src/pages/account_settings.dart, packages/neon/neon/lib/src/pages/home.dart, packages/neon/neon/lib/src/pages/login.dart, packages/neon/neon/lib/src/pages/nextcloud_app_settings.dart, packages/neon/neon/lib/src/pages/settings.dart, packages/neon/neon/lib/src/widgets/exception.dart, packages/neon/neon_files/lib/pages/main.dart, packages/neon/neon_files/lib/widgets/browser_view.dart, packages/neon/neon_news/lib/pages/article.dart, packages/neon/neon_news/lib/widgets/articles_view.dart, packages/neon/neon_news/lib/widgets/feed_floating_action_button.dart, packages/neon/neon_news/lib/widgets/feeds_view.dart, packages/neon/neon_news/lib/widgets/folder_floating_action_button.dart, packages/neon/neon_notes/lib/dialogs/select_category.dart, packages/neon/neon_notes/lib/pages/note.dart, packages/neon/neon_notes/lib/widgets/category_select.dart, packages/neon/neon_notes/lib/widgets/notes_floating_action_button.dart, packages/neon/neon_notes/lib/widgets/notes_view.dart, packages/neon/neon_notifications/lib/pages/main.dart
https://github.com/provokateurin/nextcloud-neon/issues/300
=> Add tooltips to all IconButtons

packages/dynamite/dynamite/lib/src/openapi_builder.dart, packages/dynamite/dynamite/lib/src/type_result/base.dart, packages/dynamite/dynamite/lib/src/type_result/enum.dart, packages/dynamite/dynamite/lib/src/type_result/list.dart, packages/dynamite/dynamite/lib/src/type_result/map.dart, packages/dynamite/dynamite/lib/src/type_result/object.dart, packages/dynamite/dynamite/lib/src/type_result/type_result.dart, packages/nextcloud/lib/src/nextcloud.openapi.dart, packages/nextcloud/test/core.dart
fixes: #321 
For now just tested on master and openapi-automatic.
Still needs testing on the spreed branch and some cleanups.
=> built_value followup

packages/neon/neon/lib/src/pages/home.dart, packages/nextcloud/lib/src/version_supported.dart, packages/nextcloud/test/core.dart, packages/nextcloud/test/news.dart, packages/nextcloud/test/notes.dart
Closes https://github.com/provokateurin/nextcloud-neon/issues/322
Already making use of new dart features :)
@adil192 does this interface work for you?
=> Expose supported versions

packages/app/pubspec.lock, packages/neon/neon/lib/neon.dart, packages/neon/neon/lib/src/utils/push_utils.dart, packages/neon/neon/pubspec.yaml
Closes https://github.com/provokateurin/nextcloud-neon/issues/264
Not tested as my Android emulator fails with an OpenGL unimplemented error. I guess I will have to test on a physical device.
=> neon: Add large icons for push notification

packages/neon/neon/lib/neon.dart, packages/neon/neon/lib/src/utils/push_utils.dart
We are not gaining anything :)
As mentioned it's more philosophical than practical.
=> neon: use size transformation

packages/dynamite/dynamite/lib/src/openapi_builder.dart, packages/nextcloud/lib/src/nextcloud.openapi.dart
It broke json_serializable the other way as it expects factories.
=> dynamite, nextcloud: make fromJson a factory instead of a static method

packages/dynamite/dynamite/lib/src/type_result/base.dart, packages/nextcloud/lib/src/nextcloud.openapi.dart
=> dynamite, neon: fix plain object deserialization

packages/neon/neon/lib/src/pages/home.dart
just restructuring some code so I can better start to implement go_router on an per app basis.
Shouldn't add any behavior changes.
=> neon: refractor HomePage

packages/neon/neon/lib/src/widgets/user_avatar.dart
Those went missing in https://github.com/provokateurin/nextcloud-neon/pull/344 but are required for https://github.com/provokateurin/nextcloud-neon/pull/366
=> Cleanup user avatars

packages/neon/neon_news/lib/dialogs/add_feed.dart, packages/neon/neon_news/lib/widgets/feed_floating_action_button.dart, packages/neon/neon_notes/lib/dialogs/create_note.dart, packages/neon/neon_notes/lib/widgets/notes_floating_action_button.dart
Improves typesafety and readability
=> neon_news, neon_notes: use records in dialogs

packages/neon/neon/lib/neon.dart, packages/neon/neon/lib/src/app.dart, packages/neon/neon/lib/src/blocs/apps.dart, packages/neon/neon/lib/src/interfaces/notifications.dart, packages/neon/neon/lib/src/pages/home.dart, packages/neon/neon/lib/src/utils/app_implementation.dart, packages/neon/neon_notifications/lib/blocs/notifications.dart, packages/neon/neon_notifications/lib/neon_notifications.dart, packages/neon/neon_notifications/lib/options.dart, packages/neon/neon_notifications/lib/pages/main.dart
does this work?
I couldn't test it :(
It might be broken when opening the app from a notification.
If not we really need to wrap the entire app in the providers.
=> neon: fix blocProvider of notifications app

.github/workflows/publish.yaml, tool/build-app.sh, tool/build/linux.sh
Paths that need to be mounted for building the app weren't included.
From https://github.com/provokateurin/nextcloud-neon/pull/372
=> tool: Cleanup building app

packages/neon/neon/lib/neon.dart, packages/neon/neon/lib/src/models/account.dart, packages/neon/neon/lib/src/utils/app_implementation.dart
We already depend on collection so why not use it :upside_down_face: 
It makes the entire extension method a bit unnecessary but :woman_shrugging:
=> neon: make use of collection in find extensions

packages/nextcloud/lib/src/webdav/client.dart, packages/nextcloud/lib/src/webdav/file.dart, packages/nextcloud/lib/src/webdav/webdav.dart, packages/nextcloud/lib/src/webdav/webdav.g.dart, packages/nextcloud/test/core.dart, packages/nextcloud/test/webdav.dart
Add some more tests to increase the code coverage and cover important endpoints
=> Add more tests

packages/neon/neon/lib/src/widgets/account_tile.dart, packages/nextcloud/lib/src/helpers.dart, packages/nextcloud/lib/src/nextcloud.openapi.dart, packages/nextcloud/lib/src/nextcloud.openapi.g.dart, packages/nextcloud/lib/src/nextcloud.openapi.json, packages/nextcloud/lib/src/version_supported.dart, packages/nextcloud/test/provisioning_api.dart, packages/nextcloud/test/webdav.dart, specs/core.json, specs/news.json, specs/notes.json, specs/notifications.json, specs/provisioning_api.json, specs/templates/appinfo_core.xml, specs/templates/core.json, specs/templates/news.json, specs/templates/notes.json, specs/templates/notifications.json, specs/templates/provisioning_api.json, specs/templates/user_status.json, specs/uppush.json, specs/user_status.json, tool/Dockerfile.dev, tool/update.sh
Closes https://github.com/provokateurin/nextcloud-neon/issues/391
The news app sadly hasn't been updated for/is broken on 27. It only affects the web UI which we don't care about (See https://github.com/nextcloud/news/issues/2242). @Leptopoda should we merge regardless or wait for the new app to get fixed? The linked issue sounded a bit like resolving the problem could take some time...
=> Support Nextcloud 27

packages/neon/neon/lib/src/widgets/drawer.dart
also make use of the new convenience methods provided by Result
=> neon: drawer use ResultBuilder

packages/neon/neon/lib/src/blocs/apps.dart, packages/neon/neon/lib/src/pages/account_settings.dart, packages/neon/neon/lib/src/pages/home.dart, packages/neon/neon/lib/src/pages/login.dart, packages/neon/neon/lib/src/pages/settings.dart, packages/neon/neon/lib/src/utils/account_options.dart, packages/neon/neon/lib/src/utils/request_manager.dart, packages/neon/neon/lib/src/utils/result.dart, packages/neon/neon/lib/src/widgets/account_tile.dart, packages/neon/neon/lib/src/widgets/cached_image.dart, packages/neon/neon/lib/src/widgets/drawer_destination.dart, packages/neon/neon/lib/src/widgets/user_avatar.dart, packages/neon/neon_files/lib/dialogs/choose_folder.dart, packages/neon/neon_files/lib/widgets/browser_view.dart, packages/neon/neon_news/lib/blocs/news.dart, packages/neon/neon_news/lib/dialogs/add_feed.dart, packages/neon/neon_news/lib/widgets/articles_view.dart, packages/neon/neon_news/lib/widgets/feeds_view.dart, packages/neon/neon_news/lib/widgets/folders_view.dart, packages/neon/neon_notes/lib/dialogs/create_note.dart, packages/neon/neon_notes/lib/dialogs/select_category.dart, packages/neon/neon_notes/lib/widgets/categories_view.dart, packages/neon/neon_notifications/lib/blocs/notifications.dart
Cleanup after https://github.com/provokateurin/nextcloud-neon/pull/395
=> Use Result helper methods

packages/neon/neon/lib/src/pages/home.dart
I'm not yet 100% convinced if this is the right way :thinking: 
What do you think?
=> neon: dispose appVersionCheck subscribtions

.github/workflows/publish.yaml
This repo once had F-Droid nightlies, but then they broke. This is an attempt to get them working again.
=> Bring back F-Droid nightlies

packages/neon/neon/lib/src/pages/home.dart, packages/neon/neon/lib/src/pages/settings.dart, packages/neon/neon/lib/src/widgets/cached_image.dart, packages/neon/neon_news/lib/widgets/feeds_view.dart, packages/neon/neon_notifications/lib/pages/main.dart
=> neon, neon_news, neon_notifications: use error color of the theme

packages/neon/neon/lib/src/app.dart, packages/neon/neon/lib/src/utils/sort_box_builder.dart, packages/settings/lib/src/options/option.dart, packages/settings/lib/src/options/select_option.dart, packages/settings/lib/src/options/toggle_option.dart, packages/settings/lib/src/widgets/checkbox_settings_tile.dart, packages/settings/lib/src/widgets/option_builder.dart
I'll probybly make OptionBuilder extend StreamBaseBuilder for better code readability and a way cleaner widget tree.
=> neon, settings: improve nullability of OptionBuilder

packages/neon/neon_news/lib/widgets/feeds_view.dart, packages/neon/neon_news/lib/widgets/folders_view.dart
Got broken in https://github.com/provokateurin/nextcloud-neon/pull/421
=> neon_news: Fix tile spacing

packages/dynamite/dynamite_runtime/test/content_string_test.dart
I assume you just forgot to enable them again. They all pass just fine.
=> dynamite_runtime: Enable skipped tests

packages/neon/neon/lib/src/app.dart, packages/neon/neon/lib/src/models/app_implementation.dart, packages/neon/neon/lib/src/utils/theme.dart
First step towards #349 
The NenTheme is currently unused but we can start migrating constants into it in future PRs.
=> neon: allow apps to define custom themes

packages/dynamite/dynamite/lib/dynamite.dart, packages/dynamite/dynamite/lib/src/openapi_builder.dart, packages/dynamite/dynamite/pubspec.yaml
When the optional security item was the last in the list it generated broken code.
=> dynamite: Fix optional security

packages/neon/neon_notifications/lib/blocs/notifications.dart
Closes https://github.com/provokateurin/nextcloud-neon/issues/450
=> neon_notifications: Poll notifications

packages/dynamite/dynamite/lib/src/openapi_builder.dart
HttpHeaders is not an Iterable
=> dynamite: Fix headers deserialization

packages/app/pubspec.lock, packages/app/pubspec.yaml, packages/app/pubspec_overrides.yaml, packages/neon/neon/lib/src/platform/android.dart, packages/neon/neon/lib/src/platform/linux.dart, packages/neon/neon/lib/src/platform/platform.dart, packages/neon/neon/pubspec.yaml, packages/neon/neon/pubspec_overrides.yaml, packages/neon/neon_news/lib/neon_news.dart, packages/neon/neon_news/lib/pages/article.dart, packages/neon/neon_news/pubspec.yaml, packages/neon/neon_news/pubspec_overrides.yaml, packages/neon/neon_notes/lib/neon_notes.dart, packages/neon/neon_notes/lib/pages/note.dart, packages/neon/neon_notes/pubspec.yaml, packages/neon/neon_notes/pubspec_overrides.yaml
Closes https://github.com/provokateurin/nextcloud-neon/issues/471
=> Fix wakelock

.github/workflows/conventional_commits.yaml, .husky/commit-msg, commitlint.yaml, pubspec.yaml, tool/setup.sh
Closes https://github.com/provokateurin/nextcloud-neon/issues/358
=> Use conventional commits

packages/neon/neon/lib/src/platform/android.dart, packages/neon/neon/lib/src/platform/linux.dart, packages/neon/neon/lib/src/platform/platform.dart
=> refactor(neon): make NeonPlatform an interface

.github/workflows/conventional_commits.yaml
PR from same repo see https://github.com/hyiso/commitlint/pull/11
=> fix: Github Action PR from fork

packages/nextcloud/lib/src/api/core.openapi.dart, packages/nextcloud/lib/src/api/core.openapi.g.dart, packages/nextcloud/lib/src/api/core.openapi.json, packages/nextcloud/test/core_test.dart
Extracted from https://github.com/provokateurin/nextcloud-neon/pull/399. Spec and adapted was copied from the automatic specs.
=> feat(nextcloud): Implement unified search

pubspec.yaml
Supports multiple scopes now https://github.com/hyiso/commitlint/issues/10
=> chore(tool): Update commitlint_cli

README.md, docs/README.md, docs/contributing.md
Closes https://github.com/provokateurin/nextcloud-neon/issues/469
@Leptopoda is this everything we need right now? I feel like there could be more explanation. We could add a sentence about the architecture and link to the other doc page.
=> feat(docs): Add contributing docs

packages/neon/neon/lib/src/utils/account_options.dart, packages/neon/neon/lib/src/utils/app_route.dart, packages/neon/neon/lib/src/utils/global_options.dart, packages/neon/neon/lib/src/utils/push_utils.dart, packages/neon/neon/lib/src/utils/request_manager.dart
Gives us the lint [prefer_const_constructors_in_immutables](https://dart.dev/tools/linter-rules/prefer_const_constructors_in_immutables).
=> refactor(neon): make stuff immutable

.husky/commit-msg
https://github.com/hyiso/commitlint/issues/6 has been resolved
=> chore(tool): Remove fixup commits workaround

packages/neon/neon/lib/src/pages/home.dart, packages/neon/neon/lib/src/utils/global_popups.dart
Popups were shown on platforms that don't even support push notifications.
=> fix(neon): Hide useless push notifications popups

packages/neon/neon_news/lib/options.dart
Force loading wasn't an option as the generic is not a String
=> fix(neon_news): NewsAppSpecificOptions.articleViewTypeOption persistence

packages/neon/neon/lib/src/settings/models/option.dart, packages/neon/neon/lib/src/settings/models/select_option.dart, packages/neon/neon/lib/src/settings/models/storage.dart, packages/neon/neon/lib/src/settings/models/toggle_option.dart, packages/neon/neon/test/option_test.dart
... getting there eventually.
Just tested it to a limited degree and I'd love to check everything to finally get it done right but review is still welcome.
=> fix(neon): option serialization and reset

packages/neon/neon/lib/src/pages/login.dart
This was only for debugging purposes and it must have slipped past the review as well
=> fix(neon): Fix login with QR code always available

.github/workflows/dart.yml
Saves some CI time and resources.
=> feat(ci): Cancel running Dart CI

tool/build-app.sh
https://github.com/nextcloud/neon/actions/runs/5888861326/job/15970958322
This step should be added to https://github.com/nextcloud/neon/issues/575, but I want to switch it against something based on `melos list` as that is way more dynamic and won't need to be update.
=> fix(tool): Fix building app in docker

packages/dynamite/dynamite/lib/src/openapi_builder.dart
https://github.com/nextcloud/neon/pull/581
=> feat(dynamite): Support application/javascript response

packages/neon/neon/lib/src/sort_box/sort_box_builder.dart, packages/neon/neon_files/lib/sort/files.dart, packages/neon/neon_files/lib/widgets/browser_view.dart, packages/neon/neon_news/lib/sort/articles.dart, packages/neon/neon_news/lib/sort/feeds.dart, packages/neon/neon_news/lib/sort/folders.dart, packages/neon/neon_notes/lib/options.dart, packages/neon/neon_notes/lib/sort/categories.dart, packages/neon/neon_notes/lib/sort/notes.dart, packages/neon/neon_notes/lib/widgets/notes_view.dart, packages/sort_box/lib/sort_box.dart, packages/sort_box/test/sort_box_test.dart
based on #590
I applied the requested changes from #585 and also some Dart3 cleanups.
Is the documentation enough?
=> Feat/sort box/multi sorting

packages/nextcloud/lib/src/webdav/client.dart
https://github.com/nextcloud/neon/pull/372
=> feat(nextcloud): Support progress on webdav put stream

.fvm/fvm_config.json, packages/app/pubspec.lock, packages/app/pubspec.yaml, packages/file_icons/pubspec.yaml, packages/neon/neon/pubspec.yaml, packages/neon/neon_files/pubspec.yaml, packages/neon/neon_news/pubspec.yaml, packages/neon/neon_notes/pubspec.yaml, packages/neon/neon_notifications/pubspec.yaml
https://github.com/nextcloud/neon/pull/372
https://github.com/flutter/flutter/issues/132711
=> chore(deps): Update to flutter 3.13.3

packages/neon/neon/lib/neon.dart
Fixes https://github.com/nextcloud/neon/pull/495#issuecomment-1694758240
=> fix(neon): Add missing platform setup

tool/Dockerfile.dev, tool/dev/install_app_version
Prerequisite for https://github.com/nextcloud/neon/issues/571
=> refactor(tool): Pin app versions

packages/neon/neon_files/lib/dialogs/choose_folder.dart, packages/neon/neon_files/lib/l10n/en.arb, packages/neon/neon_files/lib/l10n/localizations.dart, packages/neon/neon_files/lib/l10n/localizations_en.dart, packages/neon/neon_files/lib/options.dart, packages/neon/neon_files/lib/pages/main.dart, packages/neon/neon_files/lib/sort/files.dart, packages/neon/neon_files/lib/widgets/browser_view.dart, packages/neon/neon_files/lib/widgets/file_list_tile.dart, packages/nextcloud/lib/src/webdav/file.dart, packages/nextcloud/pubspec.yaml
- sort folders first (not configurable)
- hide hidden files (configurable)
- cleanup of some widgets
=> Feat/neon files/sort folders

packages/neon/neon_files/lib/options.dart
:)
My signing might have problems as I started to use my noreply github email and didn't update the gpg in my gihub settings yet; The Signature is still valid though.
I'll update this tomorrow/when I have more time
=> fix(neon): Fix FilesOptions key

packages/nextcloud/lib/src/api/core.openapi.dart, packages/nextcloud/lib/src/api/core.openapi.json
Found this with https://github.com/nextcloud/neon/pull/703, had to fix it in the server code first.
=> chore(nextcloud): Update to remove typo

packages/app/pubspec.lock
Updates the archive dependency to 3.3.8 to mitigate some minor CVEs
=> chore(app): update pubspec.lock

packages/app/lib/branding.dart, packages/neon/neon/lib/l10n/en.arb, packages/neon/neon/lib/l10n/localizations.dart, packages/neon/neon/lib/l10n/localizations_en.dart, packages/neon/neon/lib/src/pages/settings.dart, packages/neon/neon/lib/src/theme/branding.dart
Closes https://github.com/nextcloud/neon/issues/737
=> feat(neon,app): Add links to the source code and issue tracker

packages/dynamite/dynamite_runtime/lib/src/content_string.dart, packages/dynamite/dynamite_runtime/test/content_string_test.dart
Just found an old stash with this :)
bunps the ContentString coverage to 100%
=> test(dynamite_runtime): test serialization failure

packages/dynamite/dynamite/lib/src/openapi_builder.dart
I didn't have it staged and only commited part of it in #766
=> fix(dynamite): supported file extensions

packages/neon/neon/lib/src/bloc/bloc.dart, packages/neon/neon/lib/src/blocs/accounts.dart, packages/neon/neon/lib/src/blocs/apps.dart, packages/neon/neon/lib/src/models/account_cache.dart, packages/neon/neon/lib/src/models/app_implementation.dart, packages/neon/neon/lib/src/models/disposable.dart, packages/neon/neon/lib/src/settings/models/option.dart, packages/neon/neon/lib/src/settings/models/options_collection.dart, packages/neon/neon/test/account_cache_test.dart, packages/neon/neon/test/disposable_test.dart
=> fix(neon): remove and dispose dagnling blocs after logout

packages/neon/neon/lib/src/utils/relative_time.dart, packages/neon/neon/lib/src/widgets/relative_time.dart
As discussed this is more performant.
We can try to reproduce this tomorrow but I think it was most aparent with the listview PR
=> style(neon): make RelativeTime stateful

packages/neon/neon_files/lib/blocs/browser.dart, packages/neon/neon_files/lib/blocs/files.dart, packages/neon/neon_files/lib/widgets/actions.dart
Closes https://github.com/nextcloud/neon/issues/568
=> refactor(neon_files): Allow setting an intial path for files browser bloc

packages/nextcloud/lib/src/api/core.openapi.dart, packages/nextcloud/lib/src/api/core.openapi.g.dart, packages/nextcloud/lib/src/api/core.openapi.json, packages/nextcloud/lib/src/api/provisioning_api.openapi.dart, packages/nextcloud/lib/src/api/provisioning_api.openapi.g.dart, packages/nextcloud/lib/src/api/provisioning_api.openapi.json
Update to fix some bugs found in the generated specs.
=> fix(nextcloud): Fix core and provisioning_api specs

.github/renovate.json
Closes https://github.com/nextcloud/neon/issues/828
=> feat(tool): Configure renovate groups

packages/neon/neon/lib/src/widgets/app_implementation_icon.dart, packages/neon/neon/lib/src/widgets/user_avatar.dart
Closes https://github.com/nextcloud/neon/issues/801
=> refactor(neon): Use Stacks conditionally

.cspell/tools.txt, cspell.json
I though this was enabled by default (which would make a lot of sense imo) and the official configuration documentation doesn't mention this properly...
=> fix(tool): Fix cspell not using .gitignore

.github/workflows/neon.yml, packages/nextcloud/test/core_test.dart, packages/nextcloud/test/news_test.dart, tool/find-untested-neon-apis.sh
Closes https://github.com/nextcloud/neon/issues/867
=> Prevent untested Neon APIs

packages/neon/neon_files/pubspec.yaml, packages/neon/neon_news/pubspec.yaml, packages/neon/neon_notes/pubspec.yaml, packages/neon/neon_notifications/pubspec.yaml
Forgotten in https://github.com/nextcloud/neon/pull/778
=> Remove unused provider dependency

packages/dynamite/dynamite/lib/src/builder/client.dart, packages/dynamite/dynamite/lib/src/builder/resolve_mime_type.dart
=> gracefully handle multiple mimeTypes and default responses

.github/workflows/dart.yml, .github/workflows/publish.yaml, tool/build-app.sh, tool/build-dev-container.sh, tool/common.sh, tool/dev.sh, tool/generate-screenshots.sh, tool/send-push-notification-test.sh
Closes https://github.com/nextcloud/neon/issues/798
=> Cache docker images

.github/workflows/publish.yaml
Forgot to add this in https://github.com/nextcloud/neon/pull/917
=> fix(ci): Fix missing melos in publish workflow

packages/nextcloud/lib/src/api/core.openapi.dart, packages/nextcloud/lib/src/api/core.openapi.g.dart, packages/nextcloud/lib/src/api/core.openapi.json, packages/nextcloud/test/core_test.dart
Apparently I misunderstood the server code and there is no bug. Just an overcomplicated API that has weird quirks for historical reasons. Depends on https://github.com/nextcloud/server/pull/40660
=> fix(nextcloud): Fix autocomplete

packages/neon/neon/lib/src/blocs/accounts.dart, packages/neon/neon/lib/src/blocs/apps.dart, packages/neon/neon/lib/src/blocs/capabilities.dart, packages/neon/neon/lib/src/blocs/login_flow.dart, packages/neon/neon/lib/src/blocs/user_details.dart, packages/neon/neon/lib/src/blocs/user_statuses.dart, packages/neon/neon/lib/src/pages/home.dart, packages/neon/neon/lib/src/pages/settings.dart, packages/neon/neon/lib/src/utils/global_options.dart, packages/neon/neon/lib/src/widgets/app_bar.dart, packages/neon/neon/lib/src/widgets/image.dart, packages/neon/neon/lib/src/widgets/user_avatar.dart
Makes the code a bit more readable, especially for BehaviorSubjects with long type arguments.
=> style(neon): Remove automatically inferred generic type arguments

packages/dynamite/dynamite_runtime/test/content_string_test.dart, packages/neon/neon/test/app_implementation_test.dart, packages/neon/neon/test/disposable_test.dart, packages/neon/neon/test/settings_export_test.dart, packages/neon/neon/test/stream_listenable_test.dart, packages/neon/neon/test/timer_bloc_test.dart, packages/neon/neon_files/lib/utils/task.dart, packages/nextcloud/test/helper.dart
ignore_for_file should be avoided as much as possible and instead the problems should be fixed where possible.
=> refactor: Cleanup ignore_for_file's

.github/renovate.json, docs/README.md, docs/dependencies.md, packages/app/pubspec.lock, packages/app/pubspec.yaml, packages/dynamite/dynamite/pubspec.yaml, packages/dynamite/dynamite_runtime/pubspec.yaml, packages/file_icons/pubspec.yaml, packages/neon/neon/pubspec.yaml, packages/neon/neon_files/pubspec.yaml, packages/neon/neon_news/pubspec.yaml, packages/neon/neon_notes/pubspec.yaml, packages/neon/neon_notifications/pubspec.yaml, packages/neon_lints/pubspec.yaml, packages/nextcloud/pubspec.yaml, packages/sort_box/pubspec.yaml, pubspec.yaml
Closes https://github.com/nextcloud/neon/issues/932
Local renovate run confirms this works.
=> refactor(deps): Pin all dependencies to the lowest possible versions

packages/neon/neon/pubspec.yaml, packages/nextcloud/pubspec.yaml
Fixes https://github.com/nextcloud/neon/issues/965
=> fix(deps): Fix json_annotation constraints

.github/workflows/dart.yml, .github/workflows/publish.yaml
The caching wasn't properly working and filling up disks and then failing some workflows.
=> fix(ci): Remove caching

packages/neon/neon/lib/src/models/push_notification.dart
Circumvents: https://github.com/google/json_serializable.dart/issues/1360
Potential long term fix: #967
=> fix(neon): push notification build error

packages/dynamite/dynamite/lib/src/builder/client.dart, packages/dynamite/dynamite/lib/src/builder/header_serializer.dart, packages/dynamite/dynamite/lib/src/builder/resolve_interface.dart, packages/dynamite/dynamite/lib/src/builder/resolve_mime_type.dart, packages/dynamite/dynamite/lib/src/helpers/dynamite.dart, packages/dynamite/dynamite/lib/src/models/openapi/header.dart, packages/dynamite/dynamite/lib/src/models/openapi/header.g.dart, packages/dynamite/dynamite/lib/src/models/openapi/open_api.dart, packages/dynamite/dynamite/lib/src/models/openapi/open_api.g.dart, packages/dynamite/dynamite/lib/src/models/openapi/operation.dart, packages/dynamite/dynamite/lib/src/models/openapi/operation.g.dart, packages/dynamite/dynamite/lib/src/models/openapi/parameter.dart, packages/dynamite/dynamite/lib/src/models/openapi/parameter.g.dart, packages/dynamite/dynamite/lib/src/models/openapi/request_body.dart, packages/dynamite/dynamite/lib/src/models/openapi/request_body.g.dart, packages/dynamite/dynamite/lib/src/models/openapi/schema.dart, packages/dynamite/dynamite/lib/src/models/openapi/schema.g.dart
=> refactor(dynamite): add default values as described by openapi

packages/neon/neon/lib/src/app.dart, packages/neon/neon/lib/src/settings/models/options_collection.dart, packages/neon/neon/lib/src/widgets/options_collection_builder.dart
There is no real benefit of having this other than simpler code when depending on multiple options from a collection.
This might be needed to scale our global options further like in #943
=> feat(neon): add optons collection builder

packages/dynamite/dynamite/lib/src/builder/client.dart, packages/nextcloud/lib/src/api/core.openapi.dart, packages/nextcloud/lib/src/api/dashboard.openapi.dart, packages/nextcloud/lib/src/api/dav.openapi.dart, packages/nextcloud/lib/src/api/files.openapi.dart, packages/nextcloud/lib/src/api/files_external.openapi.dart, packages/nextcloud/lib/src/api/files_reminders.openapi.dart, packages/nextcloud/lib/src/api/files_sharing.openapi.dart, packages/nextcloud/lib/src/api/files_trashbin.openapi.dart, packages/nextcloud/lib/src/api/files_versions.openapi.dart, packages/nextcloud/lib/src/api/news.openapi.dart, packages/nextcloud/lib/src/api/notes.openapi.dart, packages/nextcloud/lib/src/api/notifications.openapi.dart, packages/nextcloud/lib/src/api/provisioning_api.openapi.dart, packages/nextcloud/lib/src/api/settings.openapi.dart, packages/nextcloud/lib/src/api/theming.openapi.dart, packages/nextcloud/lib/src/api/updatenotification.openapi.dart, packages/nextcloud/lib/src/api/uppush.openapi.dart, packages/nextcloud/lib/src/api/user_status.openapi.dart, packages/nextcloud/lib/src/api/weather_status.openapi.dart
=> refactor(dynamite,nextcloud): change path parameter construction.

.cspell/tools.txt, CONTRIBUTING.md
ticks of a bunch of tasks form #692
=> docs(docs): document git signatures and needed packages in CONTRIBUTING.MD

packages/neon/neon_files/lib/widgets/browser_view.dart
The entire
```dart
.where(
(final task) =>
sorted.where((final file) => _pathMatchesFile(task.path, file.name)).isEmpty,
)
```
Was just a remainder from when this variable handled both upload and download tasks. At least I couldn't find any behavior change after my refactor but correct me if something is off.
=> perf(neon_files): make displaying upload tasks more performant

.github/workflows/neon.yml, packages/app/integration_test/screenshot_test.dart, packages/app/pubspec.lock, packages/app/pubspec.yaml, packages/neon/neon/lib/src/app.dart, packages/neon/neon/lib/src/platform/linux.dart, packages/neon/neon/lib/src/platform/platform.dart, packages/neon/neon/lib/src/utils/global_options.dart, packages/neon/neon/lib/src/utils/save_file.dart, packages/neon/neon/lib/src/widgets/error.dart, packages/neon/neon/pubspec.yaml, packages/neon/neon_files/lib/neon_files.dart, packages/neon/neon_files/pubspec.yaml, packages/nextcloud/test/helper.dart, packages/nextcloud/test/news_test.dart, packages/nextcloud/test/webdav_test.dart, tool/find-dart-io-usage.sh
Towards https://github.com/nextcloud/neon/pull/372
=> Use universal_io instead of dart:io

packages/dynamite/dynamite_end_to_end_test/test/ensure_validity_test.dart
=> fix(dynamite_end_to_end_test): fix spec generation timeout

packages/neon/neon/lib/src/widgets/account_tile.dart, packages/neon/neon/lib/src/widgets/app_bar.dart, packages/neon/neon/lib/src/widgets/app_implementation_icon.dart, packages/neon/neon/lib/src/widgets/dialog.dart, packages/neon/neon/lib/src/widgets/drawer.dart, packages/neon/neon/lib/src/widgets/linear_progress_indicator.dart, packages/neon/neon/lib/src/widgets/user_avatar.dart, packages/neon/neon/lib/src/widgets/validation_tile.dart
=> docs(neon): document exported widgets

packages/neon/neon/lib/src/bloc/bloc.dart, packages/neon/neon/lib/src/blocs/accounts.dart, packages/neon/neon/lib/src/blocs/apps.dart, packages/neon/neon/lib/src/blocs/capabilities.dart
=> docs(neon): document neon blocs

packages/neon/neon/lib/src/models/account.dart, packages/neon/neon/lib/src/models/account_cache.dart, packages/neon/neon/lib/src/models/app_implementation.dart, packages/neon/neon/lib/src/models/disposable.dart, packages/neon/neon/lib/src/models/label_builder.dart, packages/neon/neon/lib/src/models/notifications_interface.dart
=> docs(neon): document neon models

packages/neon/neon/lib/src/settings/models/option.dart, packages/neon/neon/lib/src/settings/models/options_category.dart, packages/neon/neon/lib/src/settings/models/options_collection.dart, packages/neon/neon/lib/src/settings/models/storage.dart, packages/neon/neon/lib/src/settings/utils/settings_export_helper.dart, packages/neon/neon/lib/src/settings/widgets/account_settings_tile.dart
=> docs(neon): document neon settings

packages/neon/neon/lib/src/utils/account_options.dart, packages/neon/neon/lib/src/utils/global.dart, packages/neon/neon/lib/src/utils/global_options.dart, packages/neon/neon/lib/src/utils/global_popups.dart, packages/neon/neon/lib/src/utils/hex_color.dart, packages/neon/neon/lib/src/utils/save_file.dart, packages/neon/neon/lib/src/utils/validators.dart
=> docs(neon): document neon utils

packages/neon/neon/lib/src/pages/login.dart, packages/neon/neon_files/lib/pages/details.dart
Closes https://github.com/nextcloud/neon/issues/861
=> refactor(neon,neon_files): Remove unnecessary Scrollbars

tool/Dockerfile.dev, tool/send-push-notification-test.sh
Got broken with https://github.com/nextcloud/neon/pull/1067
=> fix(tool): Fix sending push notification test

packages/app/android/app/build.gradle
https://github.com/nextcloud/neon/issues/1004
Reverts https://github.com/nextcloud/neon/pull/914
=> Revert "build(app): Update compileSdkVersion to 34"

packages/neon/neon/lib/src/widgets/account_tile.dart, packages/neon/neon/lib/src/widgets/app_bar.dart, packages/neon/neon/lib/src/widgets/error.dart, packages/neon/neon/lib/src/widgets/image.dart
=> feat(neon): add ability to display NeonError as a ListTile

packages/neon/neon/lib/src/widgets/image.dart
With a Center around everything the BoxFit does not apply.
=> fix(neon): Fix NeonCachedImage BoxFit

packages/neon/neon/lib/src/bloc/bloc.dart
=> refactor(neon): rename action parameter of InteractiveBloc.wrapAction

packages/nextcloud/lib/src/webdav/client.dart, packages/nextcloud/lib/src/webdav/file.dart, packages/nextcloud/test/webdav_test.dart
Fixes https://github.com/nextcloud/neon/issues/1045
=> fix(nextcloud): Fix WebDAV path construction

packages/neon/neon/lib/src/utils/global_options.dart
Fixes https://github.com/nextcloud/neon/issues/1115
=> fix(neon): Fix UnifiedPush distributors not showing up in settings

packages/nextcloud/lib/src/api/spreed.openapi.dart, packages/nextcloud/lib/src/api/spreed.openapi.g.dart, packages/nextcloud/lib/src/api/spreed.openapi.json
API should be stable now for the 18 release.
=> chore(nextcloud): Update spreed spec

packages/nextcloud/lib/src/api/core.openapi.dart, packages/nextcloud/lib/src/api/core.openapi.g.dart, packages/nextcloud/lib/src/api/core.openapi.json, packages/nextcloud/lib/src/api/sharebymail.openapi.dart, packages/nextcloud/lib/src/api/sharebymail.openapi.g.dart, packages/nextcloud/lib/src/api/sharebymail.openapi.json, packages/nextcloud/lib/src/api/spreed.openapi.dart, packages/nextcloud/lib/src/api/spreed.openapi.json, packages/nextcloud/lib/src/api/user_status.openapi.dart, packages/nextcloud/lib/src/api/user_status.openapi.g.dart, packages/nextcloud/lib/src/api/user_status.openapi.json, packages/nextcloud/lib/src/patches/sharebymail/oneof-workaround.json, packages/nextcloud/lib/src/patches/spreed/oneof-workaround.json, packages/nextcloud/lib/src/patches/user_status/oneof-workaround.json
API should be stable now for the 28 release.
=> chore(nextcloud): Update server specs

packages/dynamite/dynamite/lib/src/models/type_result/base.dart, packages/dynamite/dynamite_end_to_end_test/lib/request_body.openapi.dart, packages/dynamite/dynamite_end_to_end_test/lib/request_body.openapi.json
Needed for https://github.com/nextcloud/neon/issues/761
=> fix(dynamite): Fix application/octet-stream encoding

packages/dynamite/dynamite/lib/src/builder/client.dart, packages/dynamite/dynamite/lib/src/models/openapi/security_scheme.dart, packages/dynamite/dynamite/lib/src/models/openapi/security_scheme.g.dart, packages/dynamite/dynamite_runtime/lib/src/dynamite_client.dart
Extracted from https://github.com/nextcloud/neon/pull/1137 with https://github.com/nextcloud/neon/pull/1137#discussion_r1392099983 applied
=> fix(dynamite,dynamite_runtime): Fix security schemes

.github/workflows/dart.yml, .github/workflows/generate.yaml, .github/workflows/neon.yml
Closes https://github.com/nextcloud/neon/issues/1110
=> chore(ci): Disable neon, dart and generate workflows on main

packages/neon_lints/lib/src/base.yaml
followup to #1143
I just noticed this when you already merged it :sweat_smile:
=> chore(neon_lints): update rules against dart 3.2

packages/neon/neon/lib/src/widgets/image.dart
Apps can also return inline SVGs as icons, so we need to support them as well.
=> feat(neon): Support data URIs in NeonUrlImage

packages/neon/neon_dashboard/lib/src/blocs/dashboard.dart
Apps can easily ignore the limit and return any amount they want. This also limits it in our logic side to avoid things like https://github.com/nextcloud/collectives/pull/1020.
=> fix(neon_dashboard): Limit dashboard widget items

packages/dynamite/dynamite/lib/src/builder/ofs_builder.dart, packages/dynamite/dynamite/lib/src/builder/resolve_interface.dart, packages/dynamite/dynamite_end_to_end_test/lib/all_of.openapi.dart, packages/dynamite/dynamite_end_to_end_test/lib/all_of.openapi.g.dart, packages/dynamite/dynamite_end_to_end_test/lib/all_of.openapi.json, packages/dynamite/dynamite_end_to_end_test/test/all_of_test.dart
fixes: #1098
depends on: #1155
=> fix allOf with primitive types

packages/dynamite/dynamite/lib/src/builder/resolve_object.dart
=> refactor(dynamite): manually resolve the interface in resolveObject

tool/generate-specs.sh
Just found about the `--in-place` flag.
=> refactor(tool): Simplify patching specs

packages/nextcloud/README.md
https://github.com/nextcloud/neon/issues/571
=> feat(nextcloud): Document compatibility policy

.vscode/settings.json
fixes: #1195
implements the solution outlined in #1219
=> fix(tool): fix nextcloud unit tests in vscode

packages/dynamite/dynamite/lib/src/models/type_result/some_of.dart, packages/dynamite/dynamite_end_to_end_test/lib/nested_ofs.openapi.dart, packages/dynamite/dynamite_end_to_end_test/lib/nested_ofs.openapi.json, packages/dynamite/dynamite_end_to_end_test/test/nested_ofs_test.dart
implements: #1104 
Depends on all the previous someOf work
=>  feat(dynamite,dynamite_end_to_end_test): flatten nested ofs of the same type

packages/neon/neon_dashboard/lib/neon_dashboard.dart, packages/neon/neon_dashboard/lib/src/app.dart
Should have been in https://github.com/nextcloud/neon/pull/1227
=> chore(neon_dashboard): Update library directive

packages/neon_framework/lib/src/router.dart
Closes https://github.com/nextcloud/neon/issues/594
=> refactor(neon_framework): Simplify and clarify login redirect logic

.github/workflows/dart.yml, melos.yaml
=> fix(ci): run dart tests with dart instead of flutter

.github/workflows/update_presets.yaml
Closes https://github.com/nextcloud/neon/issues/1275
Works as expected: https://github.com/provokateurin/neon/pull/1
=> feat(ci): Update presets automatically

packages/neon_framework/lib/src/blocs/capabilities.dart, packages/neon_framework/lib/src/blocs/first_launch.dart, packages/neon_framework/lib/src/blocs/login_check_account.dart, packages/neon_framework/lib/src/blocs/login_check_server_status.dart, packages/neon_framework/lib/src/blocs/login_flow.dart, packages/neon_framework/lib/src/blocs/next_push.dart, packages/neon_framework/lib/src/blocs/push_notifications.dart, packages/neon_framework/lib/src/blocs/timer.dart, packages/neon_framework/lib/src/blocs/unified_search.dart, packages/neon_framework/lib/src/blocs/user_details.dart, packages/neon_framework/lib/src/blocs/user_statuses.dart
Closes https://github.com/nextcloud/neon/issues/1381
=> docs(neon_framework): Document all public Bloc interfaces

packages/dynamite/dynamite/pubspec.yaml
=> chore(dynamite): bump code_builder to 4.9.0

packages/neon_framework/lib/src/blocs/user_statuses.dart, packages/neon_framework/lib/src/widgets/user_avatar.dart
Extracted from https://github.com/nextcloud/neon/pull/1378
=> refactor(neon_framework): Cleanup user statuses Bloc

packages/neon/neon_dashboard/pubspec.yaml, packages/neon_framework/pubspec.yaml, packages/neon_framework/test/account_cache_test.dart, packages/neon_framework/test/account_test.dart, packages/neon_framework/test/app_implementation_test.dart, packages/neon_framework/test/disposable_test.dart, packages/neon_framework/test/findable_test.dart, packages/neon_framework/test/hex_color_test.dart, packages/neon_framework/test/neon_platform_test.dart, packages/neon_framework/test/option_test.dart, packages/neon_framework/test/options_collection_test.dart, packages/neon_framework/test/relative_time_test.dart, packages/neon_framework/test/result_test.dart, packages/neon_framework/test/settings_export_test.dart, packages/neon_framework/test/storage_test.dart, packages/neon_framework/test/stream_listenable_test.dart, packages/neon_framework/test/timer_bloc_test.dart, packages/neon_framework/test/useragent_test.dart
Closes https://github.com/nextcloud/neon/issues/1393
=> chore(neon_framework): Use flutter_test instead of test

packages/neon_framework/lib/src/pages/home.dart, packages/neon_framework/lib/src/router.dart
Fixes https://github.com/nextcloud/neon/issues/1377
=> fix(neon_framework): Fix switching account

packages/dynamite/dynamite/lib/src/builder/resolve_type.dart, packages/dynamite/dynamite_end_to_end_test/lib/enum.openapi.dart, packages/dynamite/dynamite_end_to_end_test/lib/enum.openapi.g.dart, packages/dynamite/dynamite_end_to_end_test/lib/enum.openapi.json, packages/dynamite/dynamite_end_to_end_test/test/enum_test.dart
=> fix(dynamite): fix reference to enum types

packages/neon/neon_news/lib/src/blocs/articles.dart, packages/neon/neon_news/lib/src/blocs/news.dart, packages/neon/neon_news/lib/src/widgets/articles_view.dart, packages/neon/neon_news/lib/src/widgets/dialog.dart, packages/neon/neon_news/lib/src/widgets/feeds_view.dart, packages/neon/neon_news/lib/src/widgets/folder_select.dart, packages/neon/neon_news/lib/src/widgets/folders_view.dart, packages/neon/neon_news/pubspec.yaml, packages/neon/neon_notes/lib/src/blocs/notes.dart, packages/neon/neon_notes/lib/src/widgets/categories_view.dart, packages/neon/neon_notes/lib/src/widgets/dialog.dart, packages/neon/neon_notes/lib/src/widgets/notes_view.dart, packages/neon/neon_notifications/lib/src/blocs/notifications.dart, packages/neon/neon_notifications/lib/src/pages/main.dart, packages/neon/neon_notifications/pubspec.yaml, packages/neon_framework/lib/src/blocs/apps.dart, packages/neon_framework/pubspec.yaml
This should bring a minimal performance improvement and also helps with unwanted side effects.
once we have #1128 we should be able to further keep the lists immutable.
=> perf: avoid unwrapping BuiltList into a List

assets/BSD-3-Clause.txt
=> chore: Update license year

packages/neon_framework/lib/src/sort_box/sort_box_builder.dart, packages/sort_box/lib/src/sort_box.dart, packages/sort_box/pubspec.yaml, packages/sort_box/test/sort_box_test.dart
=> feat(sort_box): support sorting a ListBuilder

packages/dynamite/dynamite_runtime/pubspec.yaml, packages/dynamite/dynamite_runtime/test/client_test.dart
Closes https://github.com/nextcloud/neon/issues/1427
=> test(dynamite_runtime): Check cookies are loaded for requests and saved from responses

melos.yaml, packages/nextcloud/test/dashboard_test.dart
The dashboard seems to have a bug where in some cases no items are returned. This is not our fault so we have to work around it :/
=> fix(nextcloud): Fix flaky dashboard tests

.cspell/misc.txt, packages/neon_framework/lib/src/utils/request_manager.dart
=> fix(neon_framework): change sqflite queries to work on more devices

packages/dynamite/dynamite/README.md, packages/dynamite/dynamite/pubspec.yaml
Fixes https://github.com/nextcloud/neon/issues/1451
=> chore(dynamite): Fix pubspec description

packages/neon/neon_dashboard/lib/src/pages/main.dart, packages/neon/neon_dashboard/lib/src/widgets/widget_item.dart, packages/neon/neon_news/lib/src/widgets/articles_view.dart, packages/neon/neon_news/lib/src/widgets/feed_icon.dart, packages/neon/neon_notifications/lib/src/pages/main.dart, packages/neon_framework/lib/src/widgets/custom_background.dart, packages/neon_framework/lib/src/widgets/drawer.dart, packages/neon_framework/lib/src/widgets/image.dart, packages/neon_framework/lib/src/widgets/unified_search_results.dart
Towards https://github.com/nextcloud/neon/issues/1125
=> refactor(neon_framework): Migrate NeonUrlImage to use Uri

docs/workflows.md
Closes https://github.com/nextcloud/neon/issues/1524
=> feat(docs): Mention bumping dynamite_runtime constraints in packages publishing workflow

packages/nextcloud/lib/src/webdav/client.dart, packages/nextcloud/pubspec.yaml, packages/nextcloud/test/fixtures/webdav/upload_and_download_empty_file.regexp, packages/nextcloud/test/webdav_test.dart
=> fix(nextcloud): create file even if webdav response is empty

packages/nextcloud/lib/src/webdav/client.dart
Closes https://github.com/nextcloud/neon/issues/1535
=> feat(nextcloud)!: Support onProgress in WebDAV getStream

packages/dynamite/dynamite/lib/src/builder/built_object_serializer.dart, packages/dynamite/dynamite/lib/src/builder/client.dart, packages/dynamite/dynamite/lib/src/builder/generate_schemas.dart, packages/dynamite/dynamite/lib/src/builder/resolve_mime_type.dart, packages/dynamite/dynamite/lib/src/builder/resolve_object.dart, packages/dynamite/dynamite/lib/src/builder/resolve_ofs.dart, packages/dynamite/dynamite/lib/src/builder/resolve_type.dart, packages/dynamite/dynamite/lib/src/helpers/dart_helpers.dart, packages/dynamite/dynamite/lib/src/helpers/dynamite.dart, packages/dynamite/dynamite/test/dart_helpers_test.dart, packages/dynamite/dynamite_end_to_end_test/lib/enum.openapi.dart, packages/dynamite/dynamite_end_to_end_test/lib/enum.openapi.g.dart, packages/dynamite/dynamite_end_to_end_test/test/enum_test.dart, packages/nextcloud/generate_exports.dart, packages/nextcloud/lib/src/api/spreed.openapi.dart, packages/nextcloud/lib/src/api/spreed.openapi.g.dart
resolves: #1441
unblocks: #1514
=> refactor(dynamite)!: do not double escape names

packages/neon/neon_dashboard/pubspec.yaml, packages/neon/neon_dashboard/test/widget_test.dart, packages/neon_framework/lib/src/testing/mocks.dart, packages/neon_framework/test/account_cache_test.dart, packages/neon_framework/test/app_implementation_test.dart, packages/neon_framework/test/dialog_test.dart, packages/neon_framework/test/disposable_test.dart, packages/neon_framework/test/drawer_test.dart, packages/neon_framework/test/options_collection_test.dart, packages/neon_framework/test/request_manager_test.dart, packages/neon_framework/test/settings_export_test.dart, packages/neon_framework/test/storage_test.dart
Follow up to https://github.com/nextcloud/neon/pull/1547
=> refactor(neon_framework): Align mock class names

packages/neon_framework/lib/src/models/push_notification.dart, packages/neon_framework/lib/src/utils/push_utils.dart, packages/neon_framework/pubspec.yaml, packages/nextcloud/lib/src/helpers/notifications.dart, packages/nextcloud/test/notifications_test.dart
Fixes https://github.com/nextcloud/neon/issues/1559
=> fix(nextcloud): Stop exporting the crypton package

packages/neon/neon_dashboard/lib/src/blocs/dashboard.dart, packages/neon/neon_dashboard/lib/src/pages/main.dart, packages/neon/neon_dashboard/pubspec.yaml, packages/neon/neon_dashboard/test/bloc_test.dart, packages/neon_framework/lib/src/testing/mock_server.dart, packages/neon_framework/test/user_status_bloc_test.dart, packages/neon_framework/test/weather_status_bloc_test.dart
TODO:
-  [x] Write tests for the whole bloc
=> refactor(neon_dashboard): Cache widgets and items

.github/workflows/dart.yml, melos.yaml
Simplifies the test execution to use the exact same commands locally and in the CI.
=> refactor(ci): Use melos test for running tests

CHANGELOG.md, packages/app/pubspec.lock, packages/app/pubspec.yaml, packages/neon/neon_dashboard/pubspec.yaml, packages/neon/neon_files/pubspec.yaml, packages/neon/neon_news/pubspec.yaml, packages/neon/neon_notes/pubspec.yaml, packages/neon/neon_notifications/pubspec.yaml, packages/neon_framework/pubspec.yaml, packages/nextcloud/CHANGELOG.md, packages/nextcloud/pubspec.yaml, packages/nextcloud_test/pubspec.yaml
=> chore(release): publish packages

packages/neon/neon_dashboard/test/widget_test.dart, packages/neon_framework/test/dialog_test.dart, packages/neon_framework/test/weather_status_bloc_test.dart
Tiny cleanup to make the code more readable.
=> refactor: Stop using toBuilder()

packages/neon/neon_notes/lib/src/blocs/notes.dart, packages/neon/neon_notes/lib/src/widgets/categories_view.dart, packages/neon/neon_notes/lib/src/widgets/dialog.dart, packages/neon/neon_notes/lib/src/widgets/notes_view.dart, packages/neon/neon_notifications/lib/src/blocs/notifications.dart, packages/neon/neon_notifications/lib/src/pages/main.dart
The suffix is really irritating because we never use them anywhere else. It was only done because of the import alias which we can easily change.
=> Rename list subjects

packages/neon_framework/lib/src/utils/request_manager.dart, packages/neon_framework/test/request_manager_test.dart
Easier to read and understand and also harder to trigger an infinite loop.
=> refactor(neon_framework): Use loop for retries in RequestManager

packages/neon/neon_dashboard/test/widget_test.dart, packages/neon_framework/lib/src/widgets/image.dart, packages/neon_framework/lib/widgets.dart
The internal implementation shouldn't be used directly.
=> refactor(neon_framework): Hide NeonImage

packages/neon_framework/lib/src/widgets/app_bar.dart
I initially wanted to make the SearchBar adaptive for iOS but for various reasons this would've required further changes.
=> refactor(neon_framework): restructure NeonAppBar

packages/neon_framework/lib/src/blocs/unified_search.dart, packages/neon_framework/lib/src/widgets/unified_search_results.dart, packages/neon_framework/test/unified_search_bloc_test.dart
Required refactor for https://github.com/nextcloud/neon/issues/890.
This removes the nested results which is really ugly and not very usable.
=> refactor(neon_framework): Decouple nested data in UnifiedSearchBloc

packages/neon_framework/lib/src/widgets/unified_search_results.dart
=> feat(neon_framework): add cupertino design search results

packages/neon/neon_dashboard/test/bloc_test.dart, packages/neon_framework/test/user_status_bloc_test.dart, packages/neon_framework/test/weather_status_bloc_test.dart
Fixes https://github.com/nextcloud/neon/issues/1624
=> fix(neon_dashboard,neon_framework): Dispose Blocs after tests

packages/neon/neon_files/lib/src/blocs/browser.dart, packages/neon/neon_files/lib/src/blocs/files.dart, packages/neon/neon_news/lib/src/blocs/article.dart, packages/neon/neon_news/lib/src/blocs/articles.dart, packages/neon/neon_news/lib/src/blocs/news.dart, packages/neon/neon_notes/lib/src/blocs/notes.dart, packages/neon/neon_notifications/lib/src/blocs/notifications.dart, packages/neon_framework/lib/src/bloc/bloc.dart, packages/neon_framework/lib/src/blocs/user_status.dart, packages/neon_framework/lib/src/blocs/weather_status.dart
This is useful to be able to change some state after the action has finished regardless of the success.
Will help a lot with https://github.com/nextcloud/neon/pull/366 which has quite complex state management and currently relies on manual try catch in many places.
=> refactor(neon_framework): Make wrapAction properly async

packages/neon_framework/lib/widgets.dart
Extracted from https://github.com/nextcloud/neon/pull/366
=> feat(neon_framework): Export NeonUserAvatar widget

packages/neon/neon_files/lib/src/blocs/browser.dart, packages/neon/neon_files/lib/src/blocs/files.dart, packages/neon/neon_files/lib/src/widgets/browser_view.dart, packages/neon/neon_files/pubspec.yaml, packages/neon_framework/lib/src/blocs/apps.dart, packages/neon_framework/lib/src/blocs/user_status.dart, packages/neon_framework/lib/src/pages/home.dart
No immutable types left in the Bloc interfaces.
=> refactor(neon_framework,neon_files): Make all Blocs only use built_value types

packages/neon/neon_files/lib/src/blocs/files.dart
Sorts the methods in the same way they are sorted in the public interface.
=> refactor(neon_files): Sort FilesBloc implementation methods

.cspell/tools.txt, tool/build-app.sh
Reads the correct config file and no longer relies on the compatibility hack of fvm.
=> refactor(tool): Read .fvmrc file

packages/neon/neon_talk/lib/src/app.dart
Towards https://github.com/nextcloud/neon/issues/356
Extracted from https://github.com/nextcloud/neon/pull/366
=> feat(neon_talk): Add version check

packages/dynamite/dynamite/lib/src/builder/client.dart, packages/dynamite/dynamite/lib/src/helpers/dart_helpers.dart, packages/dynamite/dynamite/lib/src/helpers/dynamite.dart
=> feat(dynamite): allow escaping reserved method names

packages/nextcloud/lib/src/api/spreed.openapi.dart, packages/nextcloud/lib/src/api/spreed.openapi.g.dart, packages/nextcloud/lib/src/api/spreed.openapi.json, packages/nextcloud/lib/src/patches/spreed/3-enums.json
These were missing in my previous patch because they were not listed correctly in the source code (fix for that at https://github.com/nextcloud/spreed/pull/11696).
=> fix(nextcloud): Add missing spreed MessageTypes

packages/dynamite/dynamite/lib/src/helpers/dart_helpers.dart, packages/dynamite/dynamite_end_to_end_test/lib/request_body.openapi.dart, packages/dynamite/dynamite_end_to_end_test/lib/responses.openapi.dart, packages/dynamite/dynamite_end_to_end_test/test/request_body_test.dart, packages/dynamite/dynamite_runtime/lib/src/client/client.dart, packages/nextcloud/lib/src/api/spreed.openapi.dart, packages/nextcloud/lib/src/webdav/client.dart
=> feat(dynamite_runtime): make DynamiteClient extend http.Client

packages/neon_framework/lib/src/theme/icons.dart
Some of the icons and the documentation were not correct. I should have paid closer attention when reviewing it originally :sweat_smile:
=> fix(neon_framework): Use correct adapative icons

packages/app/pubspec_overrides.yaml
Did a `melos clean && melos bs`.
=> chore(app): Generate correct dependency overrides

packages/neon/neon_talk/test/message_test.dart
Missed in https://github.com/nextcloud/neon/pull/1694
=> refactor(neon_talk): Remove Material wrap in test

packages/neon_framework/lib/src/widgets/image.dart
The templates don't exist anymore.
=> fix(neon_framework): Fix missing doc macros

README.md
https://github.com/nextcloud/neon/issues/692
=> docs: Add links to the lightning talks

packages/neon/neon_notifications/lib/src/pages/main.dart
Same as https://github.com/nextcloud/neon/pull/1489
=> fix(neon_notifications): Fix invalid index access

packages/neon_framework/lib/l10n/en.arb, packages/neon_framework/lib/l10n/localizations.dart, packages/neon_framework/lib/l10n/localizations_en.dart, packages/neon_framework/lib/src/app.dart, packages/neon_framework/lib/src/blocs/unified_search.dart, packages/neon_framework/lib/src/pages/home.dart, packages/neon_framework/lib/src/theme/theme.dart, packages/neon_framework/lib/src/widgets/account_switcher_button.dart, packages/neon_framework/lib/src/widgets/app_bar.dart, packages/neon_framework/lib/src/widgets/unified_search_results.dart, packages/neon_framework/lib/src/widgets/user_avatar.dart, packages/neon_framework/test/unified_search_bloc_test.dart
The SearchBar TextField is a bit buggy because of https://github.com/flutter/flutter/issues/138099, but this UI is better than we had before so it is acceptable for now.
=> refactor(neon_framework): Migrate unified search to SearchBar

.github/renovate.json, packages/neon_framework/lib/src/utils/request_manager.dart, packages/neon_framework/pubspec.yaml, packages/neon_framework/test/request_manager_test.dart, packages/nextcloud/lib/src/webdav/file.dart, packages/nextcloud/lib/src/webdav/webdav.dart, packages/nextcloud/pubspec.yaml, packages/nextcloud/test/webdav_test.dart
=> refactor(neon_framework): use http_parser for http date parsing

.fvmrc
=> chore(deps): Update flutter to 3.19.3

packages/neon_framework/lib/src/blocs/apps.dart, packages/neon_framework/lib/src/pages/login_check_server_status.dart, packages/neon_framework/lib/src/utils/server_version.dart
Allows testing pre-releases of the server.
=> fix(neon_framework): Allow beta and rc server development versions

packages/neon/neon_dashboard/lib/src/pages/main.dart
Fixes https://github.com/nextcloud/neon/issues/1783
=> fix(neon_dashboard): Wrap statuses to avoid overflows

packages/neon_framework/lib/neon.dart, packages/neon_framework/lib/src/platform/android.dart, packages/neon_framework/lib/src/platform/linux.dart, packages/neon_framework/lib/src/platform/web.dart
Fixes https://github.com/nextcloud/neon/issues/1800
This needs to go through the platform because web is different.
=> fix(neon_framework): Initialize timezone database

.github/workflows/publish.yaml
Fixes https://github.com/nextcloud/neon/issues/1814
=> fix(ci): Use Java 17 for building the app

packages/neon/neon_talk/lib/l10n/en.arb, packages/neon/neon_talk/lib/l10n/localizations.dart, packages/neon/neon_talk/lib/l10n/localizations_en.dart, packages/neon/neon_talk/lib/src/blocs/talk.dart, packages/neon/neon_talk/lib/src/dialogs/create_room.dart, packages/neon/neon_talk/lib/src/pages/main.dart, packages/neon/neon_talk/test/bloc_test.dart, packages/neon/neon_talk/test/create_room_dialog_test.dart, packages/neon_framework/lib/src/widgets/autocomplete.dart, packages/neon_framework/lib/widgets.dart, packages/neon_framework/test/autocomplete_test.dart
Closes https://github.com/nextcloud/neon/issues/1780
=> feat(neon_talk): Implement creating rooms

.cspell/nextcloud.txt, packages/nextcloud_test/docker/Dockerfile
Closes https://github.com/nextcloud/neon/issues/1592
=> feat(nextcloud_test): Enable debug mode and set log level to debug

.fvmrc
=> chore(deps): Update flutter to 3.19.5

packages/neon/neon_files/lib/src/blocs/browser.dart, packages/neon/neon_files/lib/src/blocs/files.dart, packages/nextcloud/generate_props.dart, packages/nextcloud/lib/src/webdav/file.dart, packages/nextcloud/lib/src/webdav/props.dart, packages/nextcloud/lib/src/webdav/props.g.dart, packages/nextcloud/test/webdav_test.dart
Much better to use properly named variables.
=> refactor(nextcloud)!: Use camel case for WebDAV props

packages/dynamite/dynamite_runtime/lib/src/utils/byte_stream_extension.dart, packages/dynamite/dynamite_runtime/lib/utils.dart, packages/nextcloud/lib/src/webdav/client.dart, packages/nextcloud/lib/src/webdav/utils.dart
=> feat(dynamite_runtime): export HttpBytesStreamExtension

packages/dynamite/dynamite/lib/src/models/type_result/type_result.dart, packages/dynamite/dynamite/test/type_result_test.dart, packages/dynamite/dynamite_end_to_end_test/lib/any_of.openapi.dart, packages/dynamite/dynamite_end_to_end_test/lib/documentation.openapi.dart, packages/dynamite/dynamite_end_to_end_test/lib/nested_ofs.openapi.dart, packages/dynamite/dynamite_end_to_end_test/lib/one_of.openapi.dart, packages/dynamite/dynamite_end_to_end_test/lib/parameters.openapi.dart, packages/dynamite/dynamite_end_to_end_test/lib/some_of.openapi.dart, packages/dynamite/dynamite_end_to_end_test/lib/type_defs.openapi.dart, packages/nextcloud/lib/src/api/core.openapi.dart, packages/nextcloud/lib/src/api/files_sharing.openapi.dart, packages/nextcloud/lib/src/api/provisioning_api.openapi.dart, packages/nextcloud/lib/src/api/sharebymail.openapi.dart, packages/nextcloud/lib/src/api/spreed.openapi.dart, packages/nextcloud/lib/src/api/user_status.openapi.dart, packages/nextcloud/lib/src/api/weather_status.openapi.dart, tool/generate-nextcloud.sh
Towards https://github.com/nextcloud/neon/issues/1244
=> feat(dynamite): Remove need for double fix and format

packages/dynamite/dynamite_runtime/lib/src/client/client.dart, packages/dynamite/dynamite_runtime/test/client_test.dart
this does not fix our current 401 errors with webdav
=> fix(dynamite_runtime): cookie header format

packages/neon/neon_news/lib/src/sort/folders.dart, packages/neon/neon_news/lib/src/widgets/dialog.dart, packages/neon/neon_news/lib/src/widgets/feeds_view.dart, packages/neon/neon_news/lib/src/widgets/folders_view.dart
Closes https://github.com/nextcloud/neon/issues/2
=> feat(neon_news): Show feeds without folder

packages/neon_framework/lib/src/blocs/accounts.dart, packages/neon_framework/lib/src/blocs/maintenance_mode.dart, packages/neon_framework/lib/src/pages/home.dart, packages/neon_framework/test/maintenance_mode_bloc_test.dart
Closes https://github.com/nextcloud/neon/issues/898
=> refactor(neon_framework): Move maintenance mode check into a Bloc

.cspell/tools.txt, .gitignore, .gitmodules, packages/app/README.md, packages/app/de.provokateurin.neon.yaml, tool/build/Dockerfile.linux
Should have been done in https://github.com/nextcloud/neon/pull/1391 already.
=> chore(app,tool): Remove unused libayatana dependency

.vscode/settings.json
=> chore(tool): ignore external/ in vscode search

packages/neon_framework/lib/src/pages/login.dart, packages/neon_framework/lib/src/pages/login_check_server_status.dart, packages/neon_framework/lib/src/pages/login_flow.dart, packages/neon_framework/lib/src/pages/login_qr_code.dart
Fixes https://github.com/nextcloud/neon/issues/804
=> fix(neon_framework): Fix login navigation

packages/dynamite/dynamite/lib/src/models/type_result/enum.dart, packages/dynamite/dynamite/lib/src/models/type_result/list.dart, packages/dynamite/dynamite/lib/src/models/type_result/map.dart, packages/dynamite/dynamite/lib/src/models/type_result/object.dart, packages/dynamite/dynamite/lib/src/models/type_result/type_result.dart, packages/dynamite/dynamite/test/type_result_test.dart
=> fix(dynamite): recursively use for generic in TypeResult.dartType

packages/neon_framework/lib/src/pages/home.dart, packages/neon_framework/lib/src/widgets/app_bar.dart
Closes https://github.com/nextcloud/neon/issues/1463
=> refactor(neon_framework): Hide the drawer when only a single app is supported

packages/dynamite/dynamite/lib/src/models/openapi.dart, packages/dynamite/dynamite/lib/src/models/openapi/schema.dart, packages/dynamite/dynamite/test/openapi_spec.dart, packages/dynamite/dynamite_end_to_end_test/lib/types.openapi.dart, packages/dynamite/dynamite_end_to_end_test/lib/types.openapi.g.dart, packages/dynamite/dynamite_end_to_end_test/lib/types.openapi.json, packages/dynamite/dynamite_end_to_end_test/pubspec.yaml, packages/dynamite/dynamite_end_to_end_test/test/types_test.dart
=> fix(dynamite): allow boolean values for Schema.additionalProperties

.github/codecov.yaml
Annoying as hell when you want to review something
=> fix(ci): Disable codecov annotations

packages/neon/neon_dashboard/test/bloc_test.dart, packages/neon/neon_dashboard/test/widget_test.dart, packages/neon/neon_talk/test/actor_avatar_test.dart, packages/neon/neon_talk/test/bloc_test.dart, packages/neon/neon_talk/test/create_room_dialog_test.dart, packages/neon/neon_talk/test/message_test.dart, packages/neon/neon_talk/test/rich_object_test.dart, packages/neon/neon_talk/test/room_avatar_test.dart, packages/neon/neon_talk/test/room_bloc_test.dart, packages/neon/neon_talk/test/room_page_test.dart, packages/neon_framework/lib/src/testing/mocks.dart, packages/neon_framework/test/autocomplete_test.dart, packages/neon_framework/test/maintenance_mode_bloc_test.dart, packages/neon_framework/test/unified_search_bloc_test.dart, packages/neon_framework/test/user_avatar_test.dart, packages/neon_framework/test/user_details_bloc_test.dart, packages/neon_framework/test/user_status_bloc_test.dart, packages/neon_framework/test/weather_status_bloc_test.dart
This will make it a lot easier once the the NeonStorage also handles the cookie_jar
=> refactor(neon_framework): add NeonStorage fake for easier unit testing

packages/neon/neon_dashboard/lib/src/blocs/dashboard.dart, packages/neon/neon_files/lib/src/blocs/browser.dart, packages/neon/neon_files/lib/src/widgets/file_preview.dart, packages/neon/neon_news/lib/src/blocs/articles.dart, packages/neon/neon_news/lib/src/blocs/news.dart, packages/neon/neon_notes/lib/src/blocs/notes.dart, packages/neon/neon_notifications/lib/src/blocs/notifications.dart, packages/neon/neon_talk/lib/src/blocs/room.dart, packages/neon/neon_talk/lib/src/blocs/talk.dart, packages/neon/neon_talk/lib/src/widgets/rich_object/file.dart, packages/neon/neon_talk/lib/src/widgets/room_avatar.dart, packages/neon_framework/lib/src/blocs/apps.dart, packages/neon_framework/lib/src/blocs/capabilities.dart, packages/neon_framework/lib/src/blocs/unified_search.dart, packages/neon_framework/lib/src/blocs/user_details.dart, packages/neon_framework/lib/src/blocs/user_status.dart, packages/neon_framework/lib/src/blocs/weather_status.dart, packages/neon_framework/lib/src/testing/mocks.dart, packages/neon_framework/lib/src/utils/request_manager.dart, packages/neon_framework/lib/src/widgets/image.dart, packages/neon_framework/lib/src/widgets/user_avatar.dart, packages/neon_framework/test/image_test.dart, packages/neon_framework/test/request_manager_test.dart
The same request can not be used multiple times so a new request has to be created every time.
=> fix(neon_framework): Create new http.Request every time when retrying failed requests

packages/neon_framework/lib/l10n/en.arb, packages/neon_framework/lib/l10n/localizations.dart, packages/neon_framework/lib/l10n/localizations_en.dart, packages/neon_framework/lib/src/blocs/unified_search.dart, packages/neon_framework/lib/src/widgets/unified_search_results.dart, packages/neon_framework/test/unified_search_bloc_test.dart
Closes https://github.com/nextcloud/neon/issues/684
~~No tests added yet, but please already provide feedback @Leptopoda~~
=> feat(neon_framework): Only search in active app first

packages/dynamite/dynamite/lib/src/builder/client.dart, packages/dynamite/dynamite/lib/src/builder/resolve_mime_type.dart, packages/dynamite/dynamite/lib/src/helpers/logger.dart, packages/dynamite/dynamite/lib/src/models/openapi/parameter.dart, packages/dynamite/dynamite/lib/src/models/openapi/schema.dart, packages/dynamite/dynamite/lib/src/openapi_builder.dart, packages/dynamite/dynamite/pubspec.yaml, packages/file_icons/analysis_options.yaml, packages/neon_lints/lib/flutter.yaml, packages/neon_lints/lib/src/base.yaml, packages/neon_lints/lint_maker.yaml, packages/nextcloud/analysis_options.yaml
=> refactor(dynamite): use logger to display warnings

packages/neon_framework/pubspec.yaml, packages/nextcloud/pubspec.yaml
Since https://github.com/nextcloud/neon/pull/1968 this version is required
=> fix(deps): Require json_annotation ^4.9.0

.github/workflows/dart.yml
Closes https://github.com/nextcloud/neon/issues/1453
=> refactor(ci): Only build docker images when needed

packages/neon/neon_talk/lib/src/blocs/room.dart, packages/neon/neon_talk/test/room_bloc_test.dart, packages/neon/neon_talk/test/room_page_test.dart, packages/neon_framework/lib/src/testing/mock_server.dart
Closes https://github.com/nextcloud/neon/issues/1917
=> feat(neon_talk): Poll chat messages to receive updates

packages/dynamite/dynamite/lib/src/builder/generate_ofs.dart, packages/dynamite/dynamite/lib/src/builder/resolve_interface.dart, packages/dynamite/dynamite/lib/src/builder/resolve_mime_type.dart, packages/dynamite/dynamite/lib/src/builder/resolve_object.dart, packages/dynamite/dynamite/lib/src/builder/state.dart, packages/dynamite/dynamite/lib/src/helpers/dart_helpers.dart, packages/dynamite/dynamite/lib/src/models/type_result/some_of.dart
=> refactor(dynamite): remove unused resolvedInterfaces

packages/dynamite/dynamite/lib/src/builder/built_object_serializer.dart, packages/dynamite/dynamite/lib/src/builder/client.dart, packages/dynamite/dynamite/lib/src/builder/generate_ofs.dart, packages/dynamite/dynamite/lib/src/builder/generate_schemas.dart, packages/dynamite/dynamite/lib/src/builder/resolve_enum.dart, packages/dynamite/dynamite/lib/src/builder/resolve_interface.dart, packages/dynamite/dynamite/lib/src/builder/resolve_mime_type.dart, packages/dynamite/dynamite/lib/src/builder/resolve_object.dart, packages/dynamite/dynamite/lib/src/builder/resolve_ofs.dart, packages/dynamite/dynamite/lib/src/builder/resolve_type.dart, packages/dynamite/dynamite/lib/src/openapi_builder.dart
=> feat(dynamite): do not rely on the openapi spec for type resolving

packages/neon_framework/lib/src/pages/home.dart, packages/neon_framework/lib/src/widgets/app_bar.dart
Not sure how I messed this up...
=> fix(neon_framework): Show drawer when exactly two apps are available

packages/neon/neon_talk/lib/src/blocs/room.dart, packages/neon/neon_talk/lib/src/blocs/talk.dart, packages/neon/neon_talk/lib/src/pages/main.dart, packages/neon/neon_talk/test/bloc_test.dart, packages/neon/neon_talk/test/room_bloc_test.dart, packages/neon/neon_talk/test/testing.dart
Closes https://github.com/nextcloud/neon/issues/1918
=> Update room list automatically.

packages/neon/neon_notifications/lib/src/pages/main.dart, packages/neon/neon_notifications/pubspec.yaml
Towards https://github.com/nextcloud/neon/issues/212
=> feat(neon_notifications): Add buttons for notification actions

packages/neon/neon_talk/lib/src/blocs/room.dart, packages/neon/neon_talk/lib/src/utils/constants.dart, packages/neon/neon_talk/lib/src/widgets/message.dart, packages/neon/neon_talk/test/room_bloc_test.dart, packages/neon/neon_talk/test/testing.dart
Closes https://github.com/nextcloud/neon/issues/2064
=> feat(neon_talk): Update messages from polled hidden messages

packages/neon/neon_dashboard/test/widget_test.dart, packages/neon/neon_notifications/test/action_test.dart, packages/neon/neon_notifications/test/main_page_test.dart, packages/neon/neon_notifications/test/notification_test.dart, packages/neon/neon_talk/lib/src/widgets/rich_object/file.dart, packages/neon/neon_talk/test/message_test.dart, packages/neon/neon_talk/test/rich_object_test.dart, packages/neon_framework/lib/src/models/account.dart, packages/neon_framework/lib/src/testing/mocks.dart, packages/neon_framework/lib/src/testing/utils.dart, packages/neon_framework/test/image_test.dart
Found https://guillaume.bernos.dev/testing-go-router-2/ and it worked great :tada:
=> feat(neon_framework): Enable mocking of go_router in tests

packages/neon_framework/lib/src/blocs/unified_search.dart, packages/neon_framework/lib/src/widgets/unified_search_results.dart
Fixes https://github.com/nextcloud/neon/issues/1865
=> fix(neon_framework): Show no results message when unified search has no results at all

packages/nextcloud/README.md
As discusses here https://github.com/nextcloud/neon/issues/2123
=> docs(nextcloud): Internet permission hint for flutter multi-platform users

packages/app/pubspec.yaml, packages/dynamite/dynamite/example/pubspec.yaml, packages/dynamite/dynamite/pubspec.yaml, packages/dynamite/dynamite_end_to_end_test/pubspec.yaml, packages/dynamite/dynamite_runtime/pubspec.yaml, packages/file_icons/pubspec.yaml, packages/neon/neon_dashboard/pubspec.yaml, packages/neon/neon_files/pubspec.yaml, packages/neon/neon_news/pubspec.yaml, packages/neon/neon_notes/pubspec.yaml, packages/neon/neon_notifications/pubspec.yaml, packages/neon/neon_talk/pubspec.yaml, packages/neon_framework/pubspec.yaml, packages/neon_lints/example/pubspec.yaml, packages/neon_lints/pubspec.yaml, packages/nextcloud/pubspec.yaml, packages/nextcloud_test/pubspec.yaml, packages/sort_box/pubspec.yaml, pubspec.yaml
Closes https://github.com/nextcloud/neon/issues/2119
=> Require Dart ^3.0 and Flutter ^3.22

packages/neon/neon_talk/lib/src/widgets/message.dart
Closes https://github.com/nextcloud/neon/issues/2043
=> feat(neon_talk): Allow copying message text

.cspell/dart_flutter.txt, packages/neon/neon_talk/lib/src/pages/room.dart, packages/neon/neon_talk/test/room_page_test.dart
Fixes https://github.com/nextcloud/neon/issues/2148
=> fix(neon_talk): Use local timezone for date dividers

README.md
Removes duplicate Photos entry and uses a checkmark that's more visible.
=> docs: Improve features list

packages/nextcloud/lib/src/webdav/client.dart
Closes https://github.com/nextcloud/neon/issues/1998
=> refactor(nextcloud)!: Mark WebDAV contentLength parameters as required

.github/renovate.json, packages/neon/neon_dashboard/test/widget_test.dart, packages/neon_framework/build.yaml, packages/neon_framework/lib/src/blocs/login_check_account.dart, packages/neon_framework/lib/src/models/account.dart, packages/neon_framework/lib/src/models/account.g.dart, packages/neon_framework/lib/src/models/push_notification.dart, packages/neon_framework/lib/src/models/push_notification.g.dart, packages/neon_framework/lib/src/testing/mock_server.dart, packages/neon_framework/pubspec.yaml, packages/neon_framework/test/account_test.dart, packages/nextcloud/lib/src/helpers/notifications.dart, packages/nextcloud/lib/src/helpers/notifications.g.dart, packages/nextcloud/pubspec.yaml
Closes https://github.com/nextcloud/neon/issues/967
=> refactor(nextcloud,neon_framework)!: Move all json_serializable usage to built_value

packages/neon_framework/lib/src/utils/request_manager.dart, packages/neon_framework/test/request_manager_test.dart, packages/nextcloud/lib/src/webdav/csrf_client.dart, packages/nextcloud/pubspec.yaml
Fixes https://github.com/nextcloud/neon/issues/2213
=> fix(neon_framework): Retry WebDAV authorization errors in case an expired CSRF was the cause

packages/nextcloud/test/core_test.dart, packages/nextcloud/test/dashboard_test.dart, packages/nextcloud/test/fixtures/news/add_feed_to_folder.regexp, packages/nextcloud/test/fixtures/news/delete_feed.regexp, packages/nextcloud/test/fixtures/news/delete_folder.regexp, packages/nextcloud/test/fixtures/news/mark_article_as_read.regexp, packages/nextcloud/test/fixtures/news/mark_article_as_unread.regexp, packages/nextcloud/test/fixtures/news/mark_feed_as_read.regexp, packages/nextcloud/test/fixtures/news/mark_folder_as_read.regexp, packages/nextcloud/test/fixtures/news/move_feed_to_folder.regexp, packages/nextcloud/test/fixtures/news/rename_feed.regexp, packages/nextcloud/test/fixtures/news/rename_folder.regexp, packages/nextcloud/test/fixtures/news/star_article.regexp, packages/nextcloud/test/fixtures/news/unstar_article.regexp, packages/nextcloud/test/news_test.dart, packages/nextcloud/test/notes_test.dart, packages/nextcloud/test/notifications_test.dart, packages/nextcloud/test/provisioning_api_test.dart, packages/nextcloud/test/settings_test.dart, packages/nextcloud/test/spreed_test.dart, packages/nextcloud/test/uppush_test.dart, packages/nextcloud/test/user_status_test.dart, packages/nextcloud/test/weather_status_test.dart, packages/nextcloud/test/webdav_test.dart, packages/nextcloud_test/lib/src/docker_container.dart, packages/nextcloud_test/lib/src/fixtures.dart
Only brings 5-10s improvements, but needed for https://github.com/nextcloud/neon/issues/1901.
=> test(nextcloud): Reuse container for news tests

packages/neon/neon_dashboard/lib/src/blocs/dashboard.dart, packages/neon/neon_dashboard/pubspec.yaml, packages/neon/neon_files/lib/src/blocs/browser.dart, packages/neon/neon_files/pubspec.yaml, packages/neon/neon_news/lib/src/blocs/articles.dart, packages/neon/neon_news/lib/src/blocs/news.dart, packages/neon/neon_news/pubspec.yaml, packages/neon/neon_notes/lib/src/blocs/notes.dart, packages/neon/neon_notes/pubspec.yaml, packages/neon/neon_notifications/lib/src/blocs/notifications.dart, packages/neon/neon_notifications/pubspec.yaml, packages/neon/neon_talk/lib/src/blocs/room.dart, packages/neon/neon_talk/lib/src/blocs/talk.dart, packages/neon/neon_talk/pubspec.yaml, packages/neon/neon_talk/test/room_bloc_test.dart, packages/neon_framework/lib/src/blocs/apps.dart, packages/neon_framework/lib/src/blocs/capabilities.dart, packages/neon_framework/lib/src/blocs/unified_search.dart, packages/neon_framework/lib/src/blocs/user_details.dart, packages/neon_framework/lib/src/blocs/user_status.dart, packages/neon_framework/lib/src/blocs/weather_status.dart, packages/neon_framework/lib/src/utils/push_utils.dart, packages/neon_framework/lib/src/utils/request_manager.dart, packages/neon_framework/lib/src/widgets/image.dart, packages/neon_framework/test/image_test.dart, packages/neon_framework/test/request_manager_test.dart, packages/nextcloud/lib/src/webdav/client.dart
https://github.com/nextcloud/neon/issues/2155
=> refactor(neon_framework): Consolidate RequestManager wrap methods and only accept http.Request

.vscode/extensions.json, .vscode/settings.json
1. use google arb extension instead of a custom
instead of custom settings.
2. add recommended built_value extension
3. add codecov extension for yaml validation
=> chore(tool): update recommended extensions

packages/nextcloud/test/fixtures/notes/create_note_favorite.regexp, packages/nextcloud/test/fixtures/notes/create_note_not_favorite.regexp, packages/nextcloud/test/fixtures/notes/delete_note.regexp, packages/nextcloud/test/fixtures/notes/get_note.regexp, packages/nextcloud/test/fixtures/notes/get_notes.regexp, packages/nextcloud/test/fixtures/notes/update_note.regexp, packages/nextcloud/test/fixtures/notes/update_note_fail_changed_on_server.regexp, packages/nextcloud/test/fixtures/user_status/heartbeat/heartbeat.regexp, packages/nextcloud/test/fixtures/user_status/statuses/find_all.regexp, packages/nextcloud/test/fixtures/user_status/user_status/clear_message.regexp, packages/nextcloud/test/fixtures/user_status/user_status/find.regexp, packages/nextcloud/test/fixtures/user_status/user_status/get.regexp, packages/nextcloud/test/fixtures/user_status/user_status/set.regexp, packages/nextcloud/test/fixtures/user_status/user_status/set_custom_message.regexp, packages/nextcloud/test/fixtures/user_status/user_status/set_predefined_message.regexp, packages/nextcloud/test/notes_test.dart, packages/nextcloud/test/user_status_test.dart, packages/nextcloud_test/lib/src/fixtures.dart
1. makes the fixtures easier to read
2. makes test failures  easier to debug
=> feat(nextcloud_test): allow to reset the fixtures

packages/nextcloud_test/docker/Dockerfile
Docker just started to warn about this, so let's fix it.
=> chore(nextcloud_test): Fix Dockerfile FROM AS casing

packages/nextcloud/lib/src/api/core.openapi.dart, packages/nextcloud/lib/src/api/core.openapi.g.dart, packages/nextcloud/lib/src/api/core.openapi.json, packages/nextcloud/lib/src/patches/core/2-fix-references.json, packages/nextcloud/test/core_test.dart, packages/nextcloud/test/fixtures/core/references/extract.regexp, packages/nextcloud/test/fixtures/core/references/resolve.regexp, packages/nextcloud/test/fixtures/core/references/resolveone.regexp
Extracted from https://github.com/nextcloud/neon/pull/2167
=> fix(nextcloud)!: Fix core references nullability

packages/neon_framework/lib/src/router.dart, packages/neon_framework/lib/src/testing/mocks.dart, packages/neon_framework/test/router_test.dart
Extracted from https://github.com/nextcloud/neon/pull/2167, but with added tests :rocket:
=> fix(neon_framework): Only prepend index.php for URLs of the server

.cspell/misc.txt, packages/nextcloud/lib/src/client.dart, packages/nextcloud/lib/src/utils/cookie_jar_client.dart, packages/nextcloud/lib/src/webdav/csrf_client.dart, packages/nextcloud/pubspec.yaml, packages/nextcloud/test/client_conformance_test.dart
=> fix(nextcloud): close wrapped http clients

.idea/runConfigurations/Debug.xml, .idea/runConfigurations/Release.xml
Same as https://github.com/nextcloud/neon/pull/2299
=> feat(tool): Allow launching app in IntelliJ with web-security disabled

.cspell/nextcloud.txt, packages/neon_http_client/lib/src/interceptors/csrf_interceptor.dart, packages/neon_http_client/test/interceptors/csrf_interceptor_test.dart, packages/nextcloud/lib/src/api/webdav/csrf_client.dart, packages/nextcloud/test/webdav_test.dart, packages/nextcloud_test/lib/src/proxy_http_client.dart
https://github.com/nextcloud/server/pull/46761
=> Use dedicated endpoint for acquiring CSRF tokens

packages/neon_framework/lib/l10n/en.arb, packages/neon_framework/lib/l10n/localizations.dart, packages/neon_framework/lib/l10n/localizations_en.dart, packages/neon_framework/lib/src/widgets/error.dart
Closes https://github.com/nextcloud/neon/issues/1821
=> feat(neon_framework): Add error message for bruteforce throttling

packages/nextcloud_test/lib/src/fixtures.dart
https://github.com/nextcloud/neon/pull/2339
=> fix(nextcloud_test): Fail on missing fixture

.github/workflows/update_presets.yaml, packages/nextcloud/README.md
I forgot to do this, so I hope I won't forget it again in the future 😇
=> docs(nextcloud): Add missing supported app versions

packages/neon_framework/lib/src/pages/home.dart
Fixes https://github.com/nextcloud/neon/issues/942
=> fix(neon_framework): Fix shadow leaking over always visible drawer

packages/neon_framework/lib/src/pages/account_settings.dart, packages/neon_framework/lib/src/widgets/account_tile.dart
Fixes https://github.com/nextcloud/neon/issues/1824
=> fix(neon_framework): Fix active account propagation for account settings and tile

packages/nextcloud/lib/src/api/webdav/webdav_client.dart
Aligns the documentation of all methods and adds missing docs for parameters (also some slight wording changes).
=> docs(nextcloud): Improve method docs of WebDavClient 

README.md, packages/neon_framework/example/README.md
[Rendered Readme](https://github.com/wrenix/nextcloud-neon/blob/feat/readme/README.md)
=> chore(docs): add f-droid nightly in README

packages/nextcloud/lib/src/api/webdav/csrf_client.dart, packages/nextcloud/lib/src/api/webdav/webdav_client.dart, packages/nextcloud/lib/webdav.dart, packages/nextcloud/test/api/webdav/csrf_client_test.dart, packages/nextcloud/test/api/webdav/webdav_test.dart
Similar to #2502
I can split off the first two commit if you prefer a separate PR.
=> refactor(nextcloud): use nextcloud csrf client to obtain csrf tokens

packages/nextcloud/lib/src/api/webdav/webdav_client.dart, packages/nextcloud/test/api/webdav/webdav_test.dart, packages/nextcloud/test/fixtures/webdav/upload_overwrite/data.regexp, packages/nextcloud/test/fixtures/webdav/upload_overwrite/stream.regexp
Fixes https://github.com/nextcloud/neon/issues/2532
=> fix(nextcloud): Do not throw DynamiteStatusCodeException on WebDAV PUT 204 response

.github/workflows/update_presets.yaml, packages/nextcloud/README.md, packages/nextcloud/generate_support_table.dart, tool/generate-nextcloud.sh
Easier to keep it updated and allows us to automatically verify it is always up-to-date.
=> feat(nextcloud): Generate support table

packages/neon_framework/lib/src/utils/push_utils.dart, packages/neon_framework/test/push_utils_test.dart
=> fix(neon_framework): Fix Android push notification icon

packages/neon_framework/lib/src/utils/push_utils.dart, packages/neon_framework/test/push_utils_test.dart
Fixes https://github.com/nextcloud/neon/issues/2591
=> fix(neon_framework): Automatically cancel summary notification if needed

packages/nextcloud/packages/nextcloud_test_presets/docker/presets/cookbook/0.11, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/drop_account/2.4, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/drop_account/2.5, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/drop_account/2.6, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/news/25.0, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/notes/4.10, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/notes/4.11, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/notes/4.8, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/notes/4.9, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/server/28.0, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/server/29.0, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/server/30.0, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/spreed/18.0, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/spreed/19.0, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/spreed/20.0, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/tables/0.6, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/tables/0.7, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/tables/0.8, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/uppush/1.4, packages/nextcloud/packages/nextcloud_test_presets/docker/presets/uppush/1.5, packages/nextcloud/packages/nextcloud_test_presets/lib/src/generate_presets.dart, packages/nextcloud/test/api/files_sharing/files_sharing_test.dart
Needed manual fixing to add the missing News app version.
=> chore(nextcloud_test): Update presets

packages/neon_framework/example/android/.gitignore, packages/neon_framework/example/pubspec.lock, packages/neon_framework/packages/files_app/pubspec.yaml
Broken due to flutter 3.29.0, but wasn't caught in the PR CI because we don't build.
https://github.com/javaherisaber/open_filex/pull/19
=> fix(files_app): Fix Android build due to incompatible open_filex

packages/neon_framework/example/pubspec.lock, packages/neon_framework/packages/files_app/pubspec.yaml
https://github.com/nextcloud/neon/pull/2830
=> chore(files_app): Drop open_filex patch and update to ^4.7.0

.github/workflows/dependency_overrides.patch, packages/neon_framework/example/pubspec.lock, packages/neon_framework/pubspec.yaml, packages/neon_framework/test/push_utils_test.dart
Closes https://github.com/nextcloud/neon/pull/2871
Closes https://github.com/nextcloud/neon/pull/2870
=> fix(deps): update dependency flutter_local_notifications to v19
