- packages/neon/lib/l10n/en.arb
- packages/neon/lib/l10n/localizations.dart
- packages/neon/lib/l10n/localizations_en.dart
- packages/neon/lib/src/apps/news/options.dart
- packages/neon/lib/src/apps/news/pages/article.dart
Closes https://github.com/jld3103/nextcloud-neon/issues/17
> neon: Add option to disable mark as read timeout in news

- .vscode/settings.json
As I use both auto format on save and fairly often format using a keyboard shortcut it makes sense to configure the formatting options.
makes developing using vscode easier.
> add vscode formatting settings

- .gitmodules
This unifies the git submodule to always use https instead of git.
I think most people using ssh already have a redirect setup so we should settle on https as the default.
> use https for initializing git submodules

- packages/dynamite/lib/src/openapi_builder.dart
When the name provided to `_toDartName` starts with a `_isNonAlphaNumericString` the `uppercaseFirstCharacter` is not respected.
https://github.com/provokateurin/nextcloud-neon/blob/443c23d167b9eea4d01c18e39d5eabd413276757/packages/dynamite/lib/src/openapi_builder.dart#L972-L978
here the problem is that the position of the first character is hard coded to the first character of the input name thus the `uppercaseFirstCharacter` is ignored if the input starts with a special character.
The method is inspirerd by the `_toCamelCase` as can be found on the built_value branch and in the built_value package.
> fix _toDartName

- packages/dynamite/lib/src/openapi_builder.dart
- packages/dynamite/lib/src/type_result/base.dart
- packages/dynamite/lib/src/type_result/enum.dart
- packages/dynamite/lib/src/type_result/list.dart
- packages/dynamite/lib/src/type_result/map.dart
- packages/dynamite/lib/src/type_result/object.dart
- packages/dynamite/lib/src/type_result/type_result.dart
- packages/nextcloud/lib/src/nextcloud.openapi.dart
- packages/nextcloud/test/core.dart
- packages/nextcloud/test/notifications.dart
built_value works on types and does not know the concept of fields (foreshadowing the contentString PR) thus we can't use dynamic. Fortunately it provides a cool JsonObject class.
It also migrates to `BuiltMap` and `BuiltList`.
We need the `toBuilder` stuff for when we generate our custom serializers mostly someOfs. 
I'm not 100% sure what the serialize and deserialize methods are used for so I might need to also adjust:
https://github.com/provokateurin/nextcloud-neon/blob/4daeda84bdb503167bf655e9c02091129e3d99da/packages/dynamite/lib/src/type_result/base.dart#L7
for the JsonObject case
> migrate types to built_value

- packages/dynamite/lib/src/openapi_builder.dart
- packages/dynamite/lib/src/type_result/list.dart
- packages/dynamite/lib/src/type_result/object.dart
- packages/nextcloud/lib/src/nextcloud.openapi.dart
I've manually tested this with:
```json
"type": "string",
"application/json",
"contentSchema": {}
```
and
```json
"type": "string",
"application/json",
"contentSchema": {
"type": "string"
}
```
and here our generated stuff for better readability:
```dart
abstract class ContentString<T> implements Built<ContentString<T>, ContentStringBuilder<T>> {
const ContentString._();
factory ContentString([void Function(ContentStringBuilder<T>)? b]) = _$ContentString<T>;
/// decoded contentString
T get content;
static ContentString fromJson(Object json) => serializers.deserializeWith(serializer, json)!;
Map<String, dynamic> toJson() => serializers.serializeWith(serializer, this) as Map<String, dynamic>;
@BuiltValueSerializer(custom: true)
static Serializer<ContentString> get serializer => …
```
> migrate contentString

- packages/dynamite/lib/src/openapi_builder.dart
we only lose `'disallowUnrecognizedKeys': 'false',`  but that's the always the case with built_value anyways.
> remove extraJsonSerializableValues

- packages/neon/neon/lib/src/pages/home.dart
- packages/neon/neon/lib/src/utils/request_manager.dart
- packages/neon/neon/lib/src/widgets/account_avatar.dart
- packages/neon/neon/lib/src/widgets/cached_api_image.dart
- packages/neon/neon/lib/src/widgets/cached_image.dart
- packages/neon/neon/lib/src/widgets/cached_url_image.dart
- packages/neon/neon/lib/src/widgets/exception.dart
Previously error messages weren't shown if a cached version was available. This could lead to user confusion.
> Always display error messages

- packages/sort_box/.gitignore
- packages/sort_box/lib/sort_box.dart
https://github.com/Leptopoda/nextcloud-neon/blob/0cdd0c15da37cf30eb1dec556b31fd9e5f3730ea/packages/sort_box/lib/sort_box.dart#L24
Ideas for a better variable name are welcome :)
https://github.com/Leptopoda/nextcloud-neon/blob/0cdd0c15da37cf30eb1dec556b31fd9e5f3730ea/packages/sort_box/lib/sort_box.dart#L9
should we make the comparablegetter it's own typedef?
I don't think it's worth it but it went through my head so just asking.
---
I removed  `preventSecondarySort` from the api as I think it was only to make the recursiveness working but we can obviously still support it.
> sortbox: improve performance

- packages/neon/neon/lib/src/utils/localizations.dart
adds a defaultLocale to suppress an error being thrown.
The default it en_us as this is also the same for flutters WidgetApp and therefore also MaterialApp.
> neon: fix unsupported locale

- packages/neon/neon/lib/src/pages/home.dart
Fixes the icon color of the NC logo in LightMode
Before:
After:
Yes the notch is clipping a lot of the app and I wanted to fix this while discovering this easy one. Note that the clipping fix isn't in here yet as it is also present on a lot of other screens and I'll go through them one by one.
> neon: fix NC icon color of QuickBar

- packages/neon/neon/lib/src/app.dart
- packages/neon/neon/lib/src/blocs/accounts.dart
- packages/neon/neon/lib/src/blocs/capabilities.dart
- packages/neon/neon/lib/src/utils/theme.dart
- packages/neon/neon/lib/src/widgets/result_builder.dart
Finally fix https://github.com/provokateurin/nextcloud-neon/issues/317
This no longer uses a global notifier that was causing race conditions (and similar bugs).
> neon: Fix theme switching

- packages/nextcloud/lib/src/webdav/client.dart
Fixes https://github.com/provokateurin/nextcloud-neon/issues/332
@muelleel please test.
> nextcloud: Add Content-Length headers for uploading

- packages/neon/neon/lib/src/blocs/accounts.dart
- packages/neon/neon/lib/src/utils/global_options.dart
debugging the old implementation was not fun :)
I'd argue that the new one is also easier to read and less error prone as we filter out equal accounts on the stream level (`activeAccount..distinct()`) so we can't forget to check :)
> neon: cleanup account handling

- packages/neon/neon/lib/src/widgets/image_wrapper.dart
Only today I realized that a color filter is needed to fix this. Previously I was trying to do it using a Stack or the background color, but that didn't work out due to the antialiasing that is applied
Before:
After:
> neon: Fix image background antialiasing

- packages/neon/neon/lib/src/models/account.dart
- packages/neon/neon/lib/src/models/push_notification.dart
- packages/neon/neon_files/lib/models/file_details.dart
annotating models with `@immutable` will give us the lint that we should make the constructors const.
I've changed `Accounts.client` to be assigned by the constructor (I don't think we are hitting any performance problems from that)
> neon, neon_files: make models immutable

- packages/neon/neon/lib/src/blocs/apps.dart
An error message was printed if no app on the server is supported by the client and therefore the active app was set to null.
From https://github.com/provokateurin/nextcloud-neon/pull/372
> neon: Supress error when setting null active app

- packages/neon/neon_files/lib/models/file_details.dart
- packages/neon/neon_files/lib/pages/details.dart
- packages/neon/neon_files/lib/pages/main.dart
- packages/neon/neon_files/lib/widgets/browser_view.dart
Currently we expect the props to be returned when we request them, but it might not be always the case (failure on the server or a different implementation that doesn't support the requested props). Also useful for later if we want to support props that depend on an app being installed on the server which might not be installed on the particular instance.
From https://github.com/provokateurin/nextcloud-neon/pull/372
> neon_files: Do not expect props to be available

- packages/app/lib/branding.dart
- packages/app/pubspec.lock
- packages/app/pubspec.yaml
- packages/neon/neon/lib/src/pages/login.dart
- packages/neon/neon/lib/src/pages/settings.dart
- packages/neon/neon/lib/src/utils/branding.dart
From https://github.com/provokateurin/nextcloud-neon/pull/372
> Move logo to branding

- .github/workflows/publish.yaml
https://github.com/flutter/flutter/issues/116703 has been resolved and we should be able to build for arm64 again.
> ci: Enable arm64 builds

- packages/nextcloud/test/webdav.dart
Fixes https://github.com/provokateurin/nextcloud-neon/issues/400
Apparently the downloaded file doesn't always have the same hash. This must be a bug in the server code, not in ours.
> Fix flaky WebDAV test

- packages/app/test_driver/integration_test.dart
- packages/dynamite/dynamite_runtime/lib/src/content_string.dart
- packages/neon/neon/lib/src/pages/account_settings.dart
- packages/neon/neon/lib/src/pages/login.dart
- packages/neon/neon/lib/src/pages/nextcloud_app_settings.dart
- packages/neon/neon/lib/src/pages/settings.dart
- packages/neon/neon/lib/src/router.dart
- packages/neon/neon/lib/src/widgets/text_settings_tile.dart
- packages/neon/neon_files/lib/dialogs/choose_create.dart
- packages/neon/neon_files/lib/pages/main.dart
- packages/neon/neon_files/lib/widgets/browser_view.dart
- packages/neon/neon_news/lib/widgets/feeds_view.dart
- packages/neon/neon_news/lib/widgets/folders_view.dart
I removed all of the ignores and only added back where the linter complained. These were the ones that got removed and weren't necessary.
> app,dynamite_runtime,neon,neon_files,neon_news: Cleanup unused ignores

- packages/neon/neon/lib/src/pages/login.dart
- packages/neon/neon/lib/src/pages/login_check_account.dart
- packages/neon/neon/lib/src/pages/login_check_server_status.dart
- packages/neon/neon/lib/src/utils/theme.dart
Thinking a bit our login layouts are more like full screen dialogs (close button at the top, ...).
Thus we should the 560dp maxWidth, rather than the 640 I propposed last time.
https://m3.material.io/components/dialogs/specs
While being at it I also moved it into a subclass so we can access it through `NeonDialogTheme.of(context)`.
Maybe a bit overkill for now but if we also want to move the `Branding` into the `NeonTheme` we can better distinguish/access them.
> neon: rework DialogTheme

- packages/app/pubspec.lock
- packages/neon/neon/pubspec.yaml
Closes https://github.com/provokateurin/nextcloud-neon/issues/467
Was fixed in https://github.com/UnifiedPush/flutter-connector/commit/de9f39b5b6a8ad50af9b09eb93c52c2d71ce69f8, many thanks @p1gp1g
> neon: Upgrade unifiedpush_android to fix unreliable push notifications

- .github/workflows/publish.yaml
Fixes https://github.com/provokateurin/nextcloud-neon/issues/460
> ci: Fix publish workflow concurrency

- commitlint.yaml
Allows having an empty scope. Still shows a warning when the scope is missing
> fix(tool): Reduce empty scope to warning

- packages/neon/neon_notes/lib/widgets/category_select.dart
We can omit the `compare` function when sorting as `List.sort` will default to `Comparable.compare` wich itself already is `a.combareTo(b)`
Inserting the default category should also be faster and less memory intensive now.
The only downside could be that we now insert the default category in the provided list directly. This could be a side effect to the caller of `NotesCategorySelect.new` but I'd argue that this is intended.
> style(neon_notes): cleanup NotesCategorySelect

- packages/nextcloud/lib/src/webdav/client.dart
Discovered during https://github.com/provokateurin/nextcloud-neon/pull/513
> fix(nextcloud): Downloading file via WebDAV to memory

- packages/nextcloud/lib/src/client.dart
- packages/nextcloud/lib/src/webdav/client.dart
- packages/nextcloud/lib/src/webdav/file.dart
- packages/nextcloud/test/webdav_test.dart
Discovered during https://github.com/provokateurin/nextcloud-neon/pull/513
> refactor(nextcloud): Use WebDAV endpoint that does not require the username

- packages/app/pubspec.lock
- packages/neon/neon/lib/src/utils/push_utils.dart
- packages/neon/neon/pubspec.yaml
The bitmap library randomly broke my build so I checked the alternatives and the image library can actually encode bitmaps. Now the encoding doesn't use any platform specific code anymore and we pull in one less dependency (at least in the app). I didn't check for performance, but it works as expected.
> refactor(neon): Use image instead of bitmap library to encode bitmaps

- packages/nextcloud/lib/nextcloud.dart
- packages/nextcloud/lib/src/client.dart
Forgot this in https://github.com/provokateurin/nextcloud-neon/pull/465
> fix(nextcloud): Fix exported clients

- packages/neon/neon_notes/lib/widgets/category_select.dart
The sort already puts the empty string in the beginning. We only need to add the empty category if there are no categories at all.
https://github.com/nextcloud/neon/pull/528
> fix(neon_files): Fix empty categories

- .github/dependabot.yml
- tool/generate-dependabot.sh
Accidentally removed in https://github.com/nextcloud/neon/pull/547
> fix(tool): Add missing workspace package to dependabot

- packages/app/pubspec.lock
We have to do it manually as dependabot doesn't respect our dependency_overrides and doesn't even update this lockfile if one of the other packages is updated.
Maybe we should add a CI workflow that runs once a day and submits the updated lockfile?
OTOH from now on we should update the lockfile directly, I just didn't do it as there were so many updates at once.
> chore(app): Update pubspec.lock

- packages/neon/neon/test/timer_bloc_test.dart
- packages/nextcloud/test/webdav_test.dart
Since switching to the org these tests are failing quite often because the runners seem to be slower.
> test(neon,nextcloud): Fix flaky tests

- packages/neon/neon/lib/src/blocs/push_notifications.dart
Push notifications were only working directly after registering because the listener was not called initially.
> fix(neon): Fix not receiving push notifications

- tool/Dockerfile.dev
Makes it easier to work with connected device that are not your host machine. Security wise this is fine as the container is only used for development and testing.
> feat(tool): Allow all domains in dev container

- packages/app/pubspec.lock
Renovate doesn't update this pubspec.lock file which is not great but I don't think we can do something about it. Just need to do this manually whenever there is an update in the future.
> chore(app): Fix pubspec.lock

- packages/neon/neon_notifications/lib/blocs/notifications.dart
Got broken in https://github.com/nextcloud/neon/pull/710
We should probably add serializers for all the `*Response<*, *>` at some point.
> fix(neon_notifications): Fix serialization

- packages/neon/neon/lib/src/pages/account_settings.dart
> feat(neon): use logout icon instead of delete on account_settings page

- packages/neon/neon/lib/src/models/app_implementation.dart
- packages/neon/neon/lib/src/pages/home.dart
- packages/neon/neon/lib/src/theme/sizes.dart
- packages/neon/neon/lib/src/widgets/app_bar.dart
- packages/neon/neon/lib/src/widgets/app_implementation_icon.dart
- packages/neon/neon/lib/src/widgets/drawer_destination.dart
- packages/neon/neon/lib/src/widgets/unified_search_results.dart
- packages/neon/neon/lib/src/widgets/user_avatar.dart
- packages/neon/neon/lib/theme.dart
- packages/neon/neon_files/lib/neon_files.dart
- packages/neon/neon_files/lib/widgets/browser_view.dart
- packages/neon/neon_files/lib/widgets/file_list_tile.dart
- packages/neon/neon_files/lib/widgets/file_preview.dart
- packages/neon/neon_news/lib/neon_news.dart
- packages/neon/neon_news/lib/widgets/articles_view.dart
- packages/neon/neon_news/lib/widgets/feed_icon.dart
- packages/neon/neon_news/lib/widgets/folders_view.dart
- packages/neon/neon_notes/lib/neon_notes.dart
- packages/neon/neon_notes/lib/widgets/categories_view.dart
- packages/neon/neon_notes/lib/widgets/notes_view.dart
- packages/neon/neon_notifications/lib/neon_notifications.dart
- packages/neon/neon_notifications/lib/pages/main.dart
The `kAvatarSize` constant was way overused. Also doing the 2/3 thing lead to odd sizes and it seems like scaling vector graphics with that leads to bad results.
> refactor(neon): Refactor icon sizes

- packages/dynamite/dynamite/lib/src/openapi_builder.dart
- packages/dynamite/dynamite/pubspec.yaml
This was surprisingly simple.
I tested it on the [petstore example](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml) and we might need to use it for the cookbook app.
> feat(dynamite): support yaml specs

- packages/nextcloud/lib/src/client.dart
Forgot to export all of the serializers. This part should also be generated automatically once we automate the client generation even further.
> fix(nextcloud): Export all serializers in the merged serializers

- packages/dynamite/dynamite_runtime/lib/src/content_string.dart
Together with #846 we could enable the rule `public_member_api_docs` for dynamite_runtime
> docs(dynamite_runtime): document content string

- packages/neon/neon/lib/src/platform/android.dart
- packages/neon/neon/lib/src/platform/linux.dart
- packages/neon/neon/lib/src/platform/platform.dart
- packages/neon/neon_files/lib/blocs/files.dart
- packages/neon/neon_files/lib/l10n/en.arb
- packages/neon/neon_files/lib/l10n/localizations.dart
- packages/neon/neon_files/lib/l10n/localizations_en.dart
- packages/neon/neon_files/lib/neon_files.dart
- packages/neon/neon_files/lib/widgets/actions.dart
- packages/neon/neon_files/pubspec.yaml
Closes https://github.com/nextcloud/neon/issues/42
> feat(neon_files): Implement sharing file natively

- packages/neon/neon/lib/src/widgets/list_view.dart
When hiding and showing these widgets the list view would resized. This lead to quite some flicker if the network request was fast and additionally if there were images in the rendered list.
> fix(neon): Fix list view flicker when loading

- .github/workflows/neon.yml
Just use the provided GH runners, self-hosted seems to be quite broken on some days...
> fix(ci): Fix stuck CI jobs

- .github/workflows/spellcheck.yaml
- cspell.json
The action enables dot matching by default, while it is disabled by default on cli.
The option to disable dot matching in the config file also wasn't documented at all...
Cspell should now also always run on all files, so we shouldn't trigger random spelling errors in unrelated PRs.
> Fix cspell CI

- packages/neon/neon/lib/src/widgets/image.dart
The fallback value was explicitly overwritten by other widgets like NewsFeedIcon or FilePreview because they allowed passing in a borderRadius, but defaulting to null.
> fix(neon): Fix NeonImageWrapper borderRadius fallback

- packages/neon/neon/lib/src/widgets/server_icon.dart
- packages/neon/neon/lib/src/widgets/unified_search_results.dart
For the user status indicator we want to use null as the color because the icon should be rendered with the color the icon actually has in the SVG. Switching to providing the color filter option makes this possible in an explicit way. The other option would be to not use the icon theme color, but that would be weird. This way it's even more flexible since you can pass different color filters now.
> fix(neon): Fix server icon explicit null color

- packages/dynamite/dynamite_runtime/lib/src/dynamite_client.dart
Previously a trailing `?` was added to the URL when no query parameters were specified.
> fix(dynamite_runtime): Skip empty query parameters

- tool/common.sh
`--push` was not necessary, but `--load` is always necessary.
> fix(tool): Fix loading cached docker images

- packages/neon/neon/lib/src/widgets/image.dart
- packages/neon/neon_news/lib/widgets/feed_icon.dart
- packages/neon/neon_notifications/lib/pages/main.dart
Color filter is more flexible to use. The feed icon should have never been colored since we want to display those images exactly as they are.
> fix(neon): Fix cached image SVG color

- packages/app/android/app/build.gradle
Since https://github.com/nextcloud/neon/pull/908 unifiedpush_android has the compileSdkVersion set to 34 and we get a warning because we use a lower version.
> build(app): Update compileSdkVersion to 34

- .github/workflows/publish.yaml
https://github.com/nextcloud/neon/pull/919 forgot that melos also requires the flutter sdk provided by fvm and so on. Full setup is required for everything to work.
> fix(ci): Fix publish workflow

- .github/workflows/.gitattributes
- .github/workflows/dart.yml
- .husky/pre-commit
- melos.yaml
Closes https://github.com/nextcloud/neon/issues/494
The script is a bit more complicated because melos does not care about the order of arguments.
First we need to find the changed packages and the dependents.
Then all tests of those packages need to run.
Putting both conditions into a single command does not work.
> feat(tool,ci): Only run tests of changed packages and their dependents

- packages/neon/neon/lib/src/platform/android.dart
- packages/neon/neon/lib/src/platform/linux.dart
- packages/neon/neon/lib/src/platform/platform.dart
- packages/neon/neon/lib/src/utils/save_file.dart
Fixes #785 
Ios support (#755 , #754 ) needs to reimplement this
> refactor(neon): unify file dialog capabilities

- packages/app/pubspec.lock
- packages/neon/neon_files/pubspec.yaml
- packages/neon/neon_news/pubspec.yaml
Reverts https://github.com/nextcloud/neon/pull/948. Seems like the version was retracted :woman_shrugging:
> Revert "fix(deps): update dependency share_plus to v8"

- packages/neon/neon/lib/src/blocs/push_notifications.dart
- packages/neon/neon/lib/src/models/push_notification.dart
- packages/neon/neon/lib/src/utils/push_utils.dart
extracted from #886
I really dislike this approach. I think we should just have a second method like `PushNotification.fromEncrypted` similar to the fromJson one. We could also do something similar with `DecryptedSubject`.
What do you think.
> refactor(neon,nextcloud): cleanup PushNotification decryption

- packages/neon/neon_files/lib/widgets/browser_view.dart
- packages/neon/neon_files/lib/widgets/file_list_tile.dart
How didn't we realize that the files view was broken :thinking: 
I think this was introduced with the NeonListView rework.
> fix(neon_files): empty browser view

- packages/dynamite/dynamite/lib/src/builder/client.dart
- packages/dynamite/dynamite_runtime/lib/src/dynamite_client.dart
- packages/neon/neon/lib/src/widgets/drawer.dart
- packages/neon/neon/lib/src/widgets/image.dart
- packages/neon/neon/lib/src/widgets/unified_search_results.dart
- packages/neon/neon/lib/src/widgets/user_avatar.dart
- packages/neon/neon_news/lib/widgets/articles_view.dart
- packages/neon/neon_news/lib/widgets/feed_icon.dart
- packages/neon/neon_notifications/lib/pages/main.dart
- packages/nextcloud/lib/nextcloud.dart
- packages/nextcloud/lib/src/api/core.openapi.dart
- packages/nextcloud/lib/src/api/dashboard.openapi.dart
- packages/nextcloud/lib/src/api/dav.openapi.dart
- packages/nextcloud/lib/src/api/files.openapi.dart
- packages/nextcloud/lib/src/api/files_external.openapi.dart
- packages/nextcloud/lib/src/api/files_reminders.openapi.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.dart
- packages/nextcloud/lib/src/api/files_trashbin.openapi.dart
- packages/nextcloud/lib/src/api/files_versions.openapi.dart
- packages/nextcloud/lib/src/api/news.openapi.dart
- packages/nextcloud/lib/src/api/notes.openapi.dart
- packages/nextcloud/lib/src/api/notifications.openapi.dart
- packages/nextcloud/lib/src/api/provisioning_api.openapi.dart
- packages/nextcloud/lib/src/api/settings.openapi.dart
- packages/nextcloud/lib/src/api/theming.openapi.dart
- packages/nextcloud/lib/src/api/updatenotification.openapi.dart
- packages/nextcloud/lib/src/api/uppush.openapi.dart
- packages/nextcloud/lib/src/api/user_status.openapi.dart
- packages/nextcloud/lib/src/api/weather_status.openapi.dart
- tool/find-untested-neon-apis.sh
Required for https://github.com/nextcloud/neon/pull/940
Previously a confusing mix of different classes and constructors was used, but now it is much cleaner.
By default the active account is used to fetch an image from the API or a URL, but can always be overridden.
> refactor(neon): Simplify account handling for API and URL images

- tool/generate-nextcloud.sh
I quickly tested it with subsequent runs so only the `dart fix` part is really invoked but changing something in the dynamite package still correctly rebuilds the specs.
Please also test this on your side. As said I only quickly tested it for now
> perf(tool): avoid rebuilding the specs if nothing changed

- packages/neon/neon_dashboard/lib/src/widgets/widget_item.dart
Seems like icon URLs can be empty. The question mark is also how it is implemented in the web frontend.
> fix(neon_dashboard): Fix empty widget item icon urls

- packages/neon/neon/lib/src/widgets/list_view.dart
- packages/neon/neon/lib/src/widgets/unified_search_results.dart
- packages/neon/neon_dashboard/lib/src/pages/main.dart
- packages/neon/neon_dashboard/lib/src/widgets/widget.dart
When the dashboard was reloading everything was resetting the scroll so it was very ugly.
Also enforced to always set a scroll key for NeonListView (and only unified search was missing one).
> fix(neon_dashboard): Fix widgets reloading scrolling back up

- packages/dynamite/dynamite/lib/src/builder/ofs_builder.dart
- packages/dynamite/dynamite/lib/src/helpers/built_value.dart
- packages/nextcloud/lib/src/api/core.openapi.dart
- packages/nextcloud/lib/src/api/core.openapi.g.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.g.dart
- packages/nextcloud/lib/src/api/provisioning_api.openapi.dart
- packages/nextcloud/lib/src/api/provisioning_api.openapi.g.dart
- packages/nextcloud/lib/src/api/user_status.openapi.dart
- packages/nextcloud/lib/src/api/user_status.openapi.g.dart
extracted from #1009
When having `allOf[ oneOf[ ... ], ... ]` the helper field `data` would have been added to the interface of the object using the allOf.
I already tested this on the spreed branch and I couldn't find any obvious errors.
> fix(dynamite): do not add someOf.data to the interface

- packages/dynamite/dynamite/lib/src/builder/imports.dart
- packages/dynamite/dynamite/lib/src/builder/serializer.dart
- packages/dynamite/dynamite/lib/src/models/openapi.g.dart
- packages/dynamite/dynamite/lib/src/models/openapi/parameter.dart
- packages/dynamite/dynamite/lib/src/models/openapi/parameter.g.dart
- packages/dynamite/dynamite/lib/src/openapi_builder.dart
- packages/dynamite/dynamite_end_to_end_test/lib/parameters.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/parameters.openapi.json
- packages/dynamite/dynamite_end_to_end_test/pubspec.yaml
Needed for the upcoming change with https://github.com/nextcloud/openapi-extractor/pull/22.
Content parameters are basically just content strings, but already available in OpenAPI 3.0.
I'm not sure if the way I implemented it is a good idea, but I felt it would be annoying to always check for both schema and content and then do the conversion manually all the time.
> feat(dynamite): Support content in parameters

- packages/dynamite/dynamite/pubspec.yaml
- packages/dynamite/dynamite_end_to_end_test/pubspec.yaml
- packages/dynamite/dynamite_runtime/pubspec.yaml
- packages/neon/neon/pubspec.yaml
- packages/nextcloud/pubspec.yaml
- packages/sort_box/pubspec.yaml
Replaces https://github.com/nextcloud/neon/pull/1002 because it is broken
> chore(deps): update dependency test to ^1.24.9

- packages/neon_lints/lib/src/base.yaml
- packages/neon_lints/lint_maker.yaml
- packages/neon_lints/pubspec.yaml
I needed to manually remove `avoid_unstable_final_fields` for now as it is not available in dart `3.1.4` yet but marked as available since `3.1`.
> feat(neon_lints): use published lint_maker package

- packages/dynamite/dynamite_runtime/pubspec.yaml
Towards https://github.com/nextcloud/neon/pull/372
Before this version using the cookie jar on web would lead to an exception.
> fix(dynamite_runtime): Require cookie_jar ^4.0.7 for web support

- .gitmodules
These are not required because we don't use their source code to generate specs. With https://github.com/nextcloud/neon/issues/537 they will of course be reintroduced but until then we don't need them.
> chore(deps): Remove unnecessary submodules

- packages/nextcloud/test/core_test.dart
This broke with https://github.com/nextcloud/neon/pull/1043, but we didn't notice because it didn't trigger the nextcloud tests.
> fix(nextcloud): Fix 27.1.3 tests

- packages/dynamite/dynamite/README.md
- packages/dynamite/dynamite/lib/builder.dart
- packages/dynamite/dynamite/lib/src/builder/imports.dart
- packages/dynamite/dynamite/lib/src/builder/state.dart
- packages/dynamite/dynamite/lib/src/models/config.dart
- packages/dynamite/dynamite/lib/src/models/dynamite_config/config.dart
- packages/dynamite/dynamite/lib/src/models/dynamite_config/config.g.dart
- packages/dynamite/dynamite/lib/src/openapi_builder.dart
- packages/dynamite/dynamite_end_to_end_test/build.yaml
- packages/dynamite/dynamite_end_to_end_test/lib/headers.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/nested_ofs.openapi.dart
We should probably first wait for #1024
I hope that we can leverage the config more in the future.  I disabled coverage ignores in the dynamite_e2e  tests as we should get the real data once coverage reports are set up.
> feat(dynamite): introduce dynamite config to set ignore directives

- packages/dynamite/dynamite/lib/src/builder/ofs_builder.dart
- packages/dynamite/dynamite_end_to_end_test/lib/nested_ofs.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/nested_ofs.openapi.g.dart
- packages/dynamite/dynamite_end_to_end_test/lib/nested_ofs.openapi.json
- packages/dynamite/dynamite_end_to_end_test/pubspec.yaml
- packages/dynamite/dynamite_end_to_end_test/test/nested_ofs_test.dart
- packages/nextcloud/lib/src/api/core.openapi.dart
- packages/nextcloud/lib/src/api/core.openapi.g.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.g.dart
- packages/nextcloud/lib/src/api/provisioning_api.openapi.dart
- packages/nextcloud/lib/src/api/provisioning_api.openapi.g.dart
- packages/nextcloud/lib/src/api/user_status.openapi.dart
- packages/nextcloud/lib/src/api/user_status.openapi.g.dart
Also correctly requires oneOf to only have one matching member.
Depends on #999 thus also blocked on the spec being corrected
> make oneOf and anyOf throw at build time rather then on deserialization

- packages/dynamite/dynamite/lib/src/builder/client.dart
- packages/dynamite/dynamite_end_to_end_test/lib/responses.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/responses.openapi.json
Closes https://github.com/nextcloud/neon/issues/871
I had this laying around from the petstore example. Might as well merge it already now that we have tests for dynamite.
> feat(dynamite): Support default responses

- packages/neon/neon/lib/src/pages/account_settings.dart
- packages/neon/neon/lib/src/pages/home.dart
- packages/neon/neon/lib/src/pages/settings.dart
> docs(neon): document neon pages

- .cspell/tools.txt
- dartdoc_options.yaml
- packages/dynamite/dynamite/lib/dynamite.dart
- packages/neon/neon/lib/models.dart
- packages/neon/neon/lib/src/models/app_implementation.dart
- packages/neon/neon/lib/src/widgets/image.dart
- packages/neon/neon_dashboard/lib/src/app.dart
- packages/neon/neon_files/lib/neon_files.dart
- packages/neon/neon_files/lib/utils/task.dart
- packages/neon/neon_news/lib/neon_news.dart
- packages/neon/neon_notes/lib/neon_notes.dart
- packages/neon/neon_notifications/lib/neon_notifications.dart
- packages/nextcloud/lib/src/helpers/spreed.dart
Adds a very strict dartdoc configuration.
It also already adjusts some errors found in the neon package.
The configuration is taken straight from the [flutter repo](https://github.com/flutter/flutter/blob/master/dartdoc_options.yaml) as I couldn't find any complete list of dartdoc options that can easily be parsed.
Having it in the project root allows all packages to use it.
> chore: test for dart doc errors

- packages/neon/neon/lib/src/pages/account_settings.dart
- packages/neon/neon/lib/src/pages/home.dart
- packages/neon/neon/lib/src/pages/login.dart
- packages/neon/neon/lib/src/pages/login_check_account.dart
- packages/neon/neon/lib/src/pages/login_check_server_status.dart
- packages/neon/neon/lib/src/pages/login_flow.dart
- packages/neon/neon/lib/src/pages/login_qr_code.dart
- packages/neon/neon/lib/src/pages/nextcloud_app_settings.dart
- packages/neon/neon/lib/src/pages/route_not_found.dart
- packages/neon/neon/lib/src/pages/settings.dart
- packages/neon/neon/lib/src/widgets/app_bar.dart
- packages/neon/neon_files/lib/pages/details.dart
- packages/neon/neon_news/lib/pages/article.dart
- packages/neon/neon_news/lib/pages/feed.dart
- packages/neon/neon_news/lib/pages/folder.dart
- packages/neon/neon_notes/lib/pages/category.dart
- packages/neon/neon_notes/lib/pages/note.dart
Fixes https://github.com/nextcloud/neon/issues/294
I tested with both the normal drawer and the always visible one and both work with this in portrait and landscape mode.
> fix(neon,neon_files,neon_news,neon_notes): Fix notch clipping content

- packages/neon/neon/lib/src/utils/push_utils.dart
- packages/neon/neon/lib/src/utils/universal_svg_file_loader.dart
Extracted from https://github.com/nextcloud/neon/pull/372
This wasn't compiling before because it was relying on dart:io code internally.
> fix(neon): Fix SVG code compilation for web

- packages/app/linux/flutter/generated_plugin_registrant.cc
- packages/app/linux/flutter/generated_plugins.cmake
- packages/app/pubspec.lock
- packages/neon/neon/lib/l10n/en.arb
- packages/neon/neon/lib/l10n/localizations.dart
- packages/neon/neon/lib/l10n/localizations_en.dart
- packages/neon/neon/lib/src/app.dart
- packages/neon/neon/lib/src/pages/settings.dart
- packages/neon/neon/lib/src/theme/theme.dart
- packages/neon/neon/lib/src/utils/global_options.dart
- packages/neon/neon/pubspec.yaml
Fixes https://github.com/nextcloud/neon/issues/975
I'm not sure if there is a better name for the option since even without it the Nextcloud theme is used, but I think this is the easiest to understand for end-users.
I noticed that buttons are now way more readable... We should have really done this earlier.
> fix(neon): Separate Nextcloud and device theme to fix contrast problems

- packages/nextcloud/lib/src/client.dart
towards: #696 
The nextcloud package still uses them in the dev only generation script but it would make the code uglier and isn't released so performance isn't a concern.
> perf(nextcloud): do not use the spread operator for building lists

- packages/dynamite/dynamite_end_to_end_test/lib/all_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/all_of.openapi.g.dart
- packages/dynamite/dynamite_end_to_end_test/lib/all_of.openapi.json
- packages/dynamite/dynamite_end_to_end_test/lib/any_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/any_of.openapi.g.dart
- packages/dynamite/dynamite_end_to_end_test/lib/any_of.openapi.json
- packages/dynamite/dynamite_end_to_end_test/lib/one_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/one_of.openapi.g.dart
- packages/dynamite/dynamite_end_to_end_test/lib/one_of.openapi.json
Adds basic tests to the ofs schemas.
I added all scenarios I consider problematic and where I want to work on in the coming weeks (namely #1082 and #1049) minus the allOf issues I found (#1098 and #1099).
Arrays are also still untested and left for #1056 and #1058.
I also still left out unit tests for the generated code as I will first want to implement the changes.
After this we can also unit test the generated code to help us keep a stable api within the generated code.
> test(dynamite_end_to_end_test): test problematic ofs

- packages/nextcloud/lib/src/client.dart
- packages/nextcloud/lib/src/webdav/client.dart
In widget tests we need to be able to mock the HttpClient.
> feat(nextcloud): Expose custom HttpClient

- .gitmodules
I removed them in https://github.com/nextcloud/neon/pull/1047 because we don't use them for generating specs. That was right but we also use them to generate the app icons so we still need them.
> fix: Add back Nextcloud News and Notes submodules

- packages/neon/neon/lib/src/models/push_notification.dart
- packages/neon/neon/lib/src/utils/push_utils.dart
The accountID is a custom field we inject, so we have to provide it explicitly when parsing from an encrypted push notification.
> fix(neon): Fix push notification decryption

- tool/find-untested-neon-apis.sh
Extracted from https://github.com/nextcloud/neon/pull/366.
Now it is also allowed to use `client[0-9]` in the unit tests instead of just `client`.
> fix(tool): Fix finding untested APIs for multiple clients

- packages/nextcloud/lib/src/helpers/spreed.dart
- packages/nextcloud/test/spreed_test.dart
Extracted from https://github.com/nextcloud/neon/pull/366
> refactor(nextcloud): Cleanup spreed helpers

- packages/neon/neon_files/lib/blocs/browser.dart
- packages/neon/neon_files/lib/blocs/files.dart
- packages/neon/neon_files/lib/dialogs/choose_create.dart
- packages/neon/neon_files/lib/dialogs/choose_folder.dart
- packages/neon/neon_files/lib/dialogs/create_folder.dart
- packages/neon/neon_files/lib/models/file_details.dart
- packages/neon/neon_files/lib/pages/details.dart
- packages/neon/neon_files/lib/pages/main.dart
- packages/neon/neon_files/lib/utils/task.dart
- packages/neon/neon_files/lib/widgets/actions.dart
- packages/neon/neon_files/lib/widgets/browser_view.dart
- packages/neon/neon_files/lib/widgets/file_list_tile.dart
- packages/neon/neon_files/lib/widgets/file_preview.dart
- packages/neon/neon_files/lib/widgets/navigator.dart
- packages/nextcloud/lib/src/webdav/client.dart
- packages/nextcloud/lib/src/webdav/file.dart
- packages/nextcloud/lib/src/webdav/path_uri.dart
- packages/nextcloud/lib/webdav.dart
- packages/nextcloud/test/webdav_test.dart
Based on https://github.com/nextcloud/neon/pull/1096
I still need to test everything and I'm pretty sure I broke some stuff.
> refactor(nextcloud,neon_files): Introduce PathUri for WebDAV path handling

- packages/nextcloud/test/dashboard_test.dart
These got broken with https://github.com/nextcloud/neon/pull/980. I assumed this was the case and a git bisect confirmed it (automatic git bisect is quite cool hehe).
Looking at the [last CI run of that PR](https://github.com/nextcloud/neon/actions/runs/6695950172/job/18192627269) the tests passed just fine. There were no relevant changes to the docker image since then that could have caused this. This is completely reproducible locally, even on the exact commit that ran in the CI.
What is even weirder is that since then the CI ran these tests a bunch of times and was completely fine (and locally it was the same). I honestly have no clue how this happened.
> fix(nextcloud): Fix dashboard tests

- .cspell/tools.txt
- .github/workflows/generate.yaml
- .gitmodules
- commitlint.yaml
- cspell.json
- packages/dynamite/dynamite_petstore_example/LICENSE
- packages/dynamite/dynamite_petstore_example/README.md
- packages/dynamite/dynamite_petstore_example/build.yaml
- packages/dynamite/dynamite_petstore_example/lib/petstore.openapi.dart
- packages/dynamite/dynamite_petstore_example/lib/petstore.openapi.g.dart
- packages/dynamite/dynamite_petstore_example/lib/petstore.openapi.json
- packages/dynamite/dynamite_petstore_example/pubspec.yaml
- packages/dynamite/dynamite_petstore_example/pubspec_overrides.yaml
- tool/generate-dynamite-petstore-example.sh
Depends on https://github.com/nextcloud/neon/pull/1136
https://github.com/nextcloud/neon/issues/761
> feat(dynamite_petstore_example): Init

- packages/neon/neon_dashboard/lib/src/widgets/widget.dart
Some dashboard widgets use iconClass instead of iconUrl.
> feat(neon_dashboard): Support server icons as dashboard widget icons

- packages/nextcloud/README.md
- packages/nextcloud/example/example.dart
Closes https://github.com/nextcloud/neon/issues/1087
I'm not sure how much further usage instructions we can give without going into specific endpoints. Most of it should be easily discoverable after reading the readme.
> Update nextcloud package docs

- .github/workflows/publish.yaml
Closes https://github.com/nextcloud/neon/issues/476
I chose 5am because it seems to be the time when the runners are least used during the night. Many other repos create jobs during the nights so we don't want add ours on top.
> chore(ci): Run publish workflow once per day

- packages/dynamite/dynamite/lib/src/builder/ofs_builder.dart
- packages/dynamite/dynamite_end_to_end_test/lib/all_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/all_of.openapi.g.dart
- packages/dynamite/dynamite_end_to_end_test/lib/all_of.openapi.json
> fix class name collision on single member allOf

- packages/dynamite/dynamite_runtime/lib/src/dynamite_client.dart
I don't expect any performance gains from this as deserializing the headers usually isn't expensive.
> DynamiteRawResponse deserialize headers while waiting for the body

- packages/neon/neon/lib/src/blocs/apps.dart
- packages/neon/neon/lib/src/models/app_implementation.dart
- packages/neon/neon/lib/src/pages/home.dart
- packages/neon/neon/lib/src/pages/login_check_server_status.dart
- packages/neon/neon/pubspec.yaml
- packages/neon/neon_news/lib/neon_news.dart
- packages/neon/neon_notes/lib/neon_notes.dart
- packages/nextcloud/lib/src/helpers/common.dart
- packages/nextcloud/lib/src/helpers/core.dart
- packages/nextcloud/lib/src/helpers/news.dart
- packages/nextcloud/lib/src/helpers/notes.dart
- packages/nextcloud/lib/src/helpers/spreed.dart
- packages/nextcloud/test/core_test.dart
- packages/nextcloud/test/news_test.dart
- packages/nextcloud/test/notes_test.dart
- packages/nextcloud/test/spreed_test.dart
- packages/nextcloud/test/version_check_test.dart
Towards https://github.com/nextcloud/neon/issues/571
Allows to define proper minimum and maximum versions.
> refactor(nextcloud): Rework version checks

- packages/nextcloud/test/dashboard_test.dart
- tool/Dockerfile.dev
Reverts https://github.com/nextcloud/neon/pull/1145 and also changes the order of setting up users and installing apps.
As far as I understand this problem comes from the user initialization. With Talk being installed it gets broken because it creates a Talk/ folder and makes the recommendations empty (which sounds like a bug itself).
> fix(nextcloud): Fix dashboard tests for real

- packages/dynamite/dynamite_runtime/lib/src/http_extensions.dart
- packages/dynamite/dynamite_runtime/pubspec.yaml
- packages/nextcloud/lib/src/webdav/client.dart
Leftover from my investigation for #1085
I don't expect any significant performance gains from this. Some quick testing revealed a 3% gain at most which I consider margin of error.
> BytesStreamExtension add stream based xml decoding

- packages/dynamite/dynamite_runtime/lib/src/http_extensions.dart
running the `large_get` test with a 5GB payload resulted in a 10% performance gain (21s -> 19s) and 44s -> 39s for a 10GB file.
Tested on my dev machine. Performance gain on low end devices will probably be higher.
> perf(dynamite_runtime): improve the performance of collecting bytes

- packages/app/pubspec_overrides.yaml
- packages/neon/neon/pubspec_overrides.yaml
- packages/neon/neon_files/pubspec_overrides.yaml
- packages/neon/neon_news/pubspec_overrides.yaml
- packages/neon/neon_notes/pubspec_overrides.yaml
- packages/neon/neon_notifications/pubspec_overrides.yaml
Ever since `neon_lints` and now with `neon_dashboard` the overrides weren't sorted alphabetically anymore.
This means running `melos bs` on a fresh clone (or after a `melos clean`) would generate a diff. This is really annoying as I regularly run into this.
Looks like it also cleans up a leftover transitive dependency that still had a registered  plugin.
> chore: run melos bootstrap from a clean state

- tool/Dockerfile.dev
- tool/dev/install_app_version
Towards https://github.com/nextcloud/neon/issues/571
Using multiple stages allows caching the app downloads.
> Optimize Dockerfile

- packages/nextcloud/lib/src/helpers/core.dart
We actually don't support 27.0 because of the new dashboard API.
Will be fixed with https://github.com/nextcloud/neon/issues/571
> fix(nextcloud): Only advertise server 27.1 compatibility

- packages/nextcloud/lib/src/helpers/spreed.dart
Same as https://github.com/nextcloud/neon/pull/1187
Will be fixed with https://github.com/nextcloud/neon/issues/571
> fix(nextcloud): Only advertise spreed 17.1 compatibility

- packages/dynamite/dynamite/lib/src/openapi_builder.dart
from the dart builder documentation:
> NOTE: Most Builder implementations should not need to await this Future since the runner will be responsible for waiting until all outputs are written.
> fix(dynamite): do not await writing the output string.

- packages/neon_framework/LICENSE
Forgot to adjust it in https://github.com/nextcloud/neon/pull/1230
> chore(neon_framework): Fix license symlink

- packages/app/android/app/src/main/AndroidManifest.xml
https://github.com/nextcloud/neon/issues/566
Comes from the camera plugin, we don't need it.
> chore(app): Remove record audio permission

- packages/app/.metadata
- packages/app/android/app/build.gradle
- packages/app/android/app/src/debug/AndroidManifest.xml
- packages/app/android/app/src/main/AndroidManifest.xml
- packages/app/android/app/src/profile/AndroidManifest.xml
- packages/app/android/build.gradle
- packages/app/android/gradle.properties
- packages/app/android/gradle/wrapper/gradle-wrapper.properties
- packages/app/android/settings.gradle
Fixes https://github.com/nextcloud/neon/issues/1004
> chore(deps): Upgrade to gradle 8

- packages/nextcloud/lib/src/webdav/client.dart
Missing Content-Length causes Nextcloud to write empty files.
Please see the discussion here:
https://github.com/saber-notes/saber/issues/945#issuecomment-1848069199
> nextcloud: Add Content-Length headers in WebDavClient.put

- packages/nextcloud/pubspec.yaml
- packages/nextcloud/test/core_test.dart
- packages/nextcloud/test/dashboard_test.dart
- packages/nextcloud/test/news_test.dart
- packages/nextcloud/test/notes_test.dart
- packages/nextcloud/test/notifications_test.dart
- packages/nextcloud/test/provisioning_api_test.dart
- packages/nextcloud/test/settings_test.dart
- packages/nextcloud/test/spreed_test.dart
- packages/nextcloud/test/uppush_test.dart
- packages/nextcloud/test/user_status_test.dart
- packages/nextcloud/test/webdav_test.dart
- packages/nextcloud_test/lib/src/docker_container.dart
We don't want to use the `printOnFailure` method directly because collecting the logs is expensive and would slow down our test (especially since the logs will almost always get discarded because the tests pass).
> feat(nextcloud): Print logs on test failure

- packages/neon_framework/lib/src/blocs/apps.dart
- packages/neon_framework/lib/src/pages/login_check_server_status.dart
Useful when testing/developing directly against a git version of Nextcloud.
> feat(neon_framework): Allow dev servers in version checks

- packages/dynamite/dynamite_petstore_example/README.md
The patch was never there because we switched to a different spec.
> chore(dynamite_petstore_example): Remove wrong patch notice

- packages/app/README.md
The issue was closed because we now use (multiple) milestones.
> chore(app): Remove link to the release todo issue

- .github/workflows/lint.yml
- packages/app/README.md
- packages/dynamite/dynamite_end_to_end_test/README.md
- packages/dynamite/dynamite_petstore_example/README.md
- packages/neon_lints/README.md
- packages/nextcloud/README.md
- packages/nextcloud_test/README.md
- tool/find-relative-markdown-links.sh
Depends on https://github.com/nextcloud/neon/pull/1268
Outside of the packages it is fine to use relative links, so we don't need to check there.
> feat(tool,ci): Check for relative markdown links

- packages/nextcloud/test/core_test.dart
- packages/nextcloud/test/dashboard_test.dart
- packages/nextcloud/test/news_test.dart
- packages/nextcloud/test/notes_test.dart
- packages/nextcloud/test/notifications_test.dart
- packages/nextcloud/test/provisioning_api_test.dart
- packages/nextcloud/test/settings_test.dart
- packages/nextcloud/test/spreed_test.dart
- packages/nextcloud/test/uppush_test.dart
- packages/nextcloud/test/user_status_test.dart
- packages/nextcloud/test/webdav_test.dart
- packages/nextcloud_test/lib/src/presets.dart
Previously the groups could look something like `notes 4.9 notes ...` while they are just `notes 4.9 ...`. For test that use the server preset though we want to keep the app. For those the groups are now `server notifications 27.1 ...` instead of `server 27.1 notifications ...` which is also better.
Best reviewed without whitespace diff: https://github.com/nextcloud/neon/pull/1266/files?w=1
> refactor(nextcloud): Remove duplicate nested test groups

- packages/dynamite/dynamite_end_to_end_test/build.yaml
- packages/dynamite/dynamite_end_to_end_test/lib/all_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/any_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/enum.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/enum.openapi.g.dart
- packages/dynamite/dynamite_end_to_end_test/lib/enum.openapi.json
- packages/dynamite/dynamite_end_to_end_test/lib/headers.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/interfaces.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/nested_ofs.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/one_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/parameters.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/pattern_check.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/request_body.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/responses.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/some_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/type_defs.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/types.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/test/enum_test.dart
Closes https://github.com/nextcloud/neon/issues/1241
Depends on https://github.com/google/built_value.dart/pull/1284
> feat(dynamite_end_to_end_test): Add string enum with a keyword value

- packages/dynamite/dynamite/README.md
- packages/dynamite/dynamite/lib/src/helpers/version_checker.dart
- packages/dynamite/dynamite/lib/src/openapi_builder.dart
- packages/dynamite/dynamite/pubspec.yaml
> feat(dynamite)!: validate version of dynamite_runtime when generating

- .github/renovate.json
Will fix the problems in https://github.com/nextcloud/neon/pull/1290 and https://github.com/nextcloud/neon/pull/1291
> fix(ci): Group test packages in renovate

- .github/renovate.json
https://github.com/nextcloud/neon/pull/1296#issuecomment-1855452982
Fixes the problem where the dependencies in nextcloud_test are not updated on minor/patch updates leading to conflicts with the dev_dependencies in other packages that got updated.
I used the exclude pattern instead of the include pattern so we don't accidentally update minor/patch versions for a package where it is not intended.
> fix(ci): Upgrade dependencies of internal packages with renovate

- packages/nextcloud/test/core_test.dart
- packages/nextcloud/test/notes_test.dart
- packages/nextcloud/test/webdav_test.dart
Some tests would sometimes fail randomly and looking at the fixtures it revealed that requests were not sent in the correct order. This should also fix the locking problem of https://github.com/nextcloud/neon/issues/1299
> fix(nextcloud): Avoid race conditions in tests

- packages/neon_framework/lib/src/settings/models/option.dart
- packages/neon_framework/lib/src/utils/global_options.dart
- packages/neon_framework/test/option_test.dart
Towards https://github.com/nextcloud/neon/issues/892, but it doesn't fix it because the AppsBloc is still making problems.
> feat(neon): Reset SelectOption if value is not in values

- packages/dynamite/dynamite/lib/src/models/type_result/some_of.dart
- packages/dynamite/dynamite_end_to_end_test/lib/parameters.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/parameters.openapi.json
- packages/dynamite/dynamite_end_to_end_test/test/parameters_test.dart
> fix(dynamite): Fix nullable someOf parameters

- packages/dynamite/dynamite/lib/src/builder/client.dart
- packages/dynamite/dynamite/lib/src/builder/resolve_object.dart
- packages/dynamite/dynamite/lib/src/helpers/pattern_check.dart
- packages/dynamite/dynamite_end_to_end_test/lib/parameters.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/parameters.openapi.g.dart
- packages/dynamite/dynamite_end_to_end_test/lib/parameters.openapi.json
- packages/dynamite/dynamite_end_to_end_test/lib/pattern_check.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/test/pattern_check_test.dart
- packages/dynamite/dynamite_runtime/lib/src/utils/string_checker.dart
- packages/nextcloud/lib/src/api/files.openapi.dart
- packages/nextcloud/lib/src/api/files_reminders.openapi.dart
- packages/nextcloud/lib/src/api/provisioning_api.openapi.dart
- packages/nextcloud/lib/src/api/spreed.openapi.dart
- packages/nextcloud/lib/src/api/theming.openapi.dart
The pattern has to be checked after the value has been serialized (not only applies to enums, but that's the only use case so far).
> fix(dynamite): Fix pattern check for enums

- packages/dynamite/dynamite/lib/src/builder/client.dart
- packages/dynamite/dynamite_end_to_end_test/lib/headers.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/parameters.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/request_body.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/responses.openapi.dart
- packages/dynamite/dynamite_petstore_example/lib/petstore.openapi.dart
- packages/dynamite/dynamite_runtime/lib/src/dynamite_client.dart
- packages/nextcloud/lib/src/api/core.openapi.dart
- packages/nextcloud/lib/src/api/dashboard.openapi.dart
- packages/nextcloud/lib/src/api/dav.openapi.dart
- packages/nextcloud/lib/src/api/files.openapi.dart
- packages/nextcloud/lib/src/api/files_external.openapi.dart
- packages/nextcloud/lib/src/api/files_reminders.openapi.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.dart
- packages/nextcloud/lib/src/api/files_trashbin.openapi.dart
- packages/nextcloud/lib/src/api/files_versions.openapi.dart
- packages/nextcloud/lib/src/api/news.openapi.dart
- packages/nextcloud/lib/src/api/notes.openapi.dart
- packages/nextcloud/lib/src/api/notifications.openapi.dart
- packages/nextcloud/lib/src/api/provisioning_api.openapi.dart
- packages/nextcloud/lib/src/api/settings.openapi.dart
- packages/nextcloud/lib/src/api/spreed.openapi.dart
- packages/nextcloud/lib/src/api/theming.openapi.dart
- packages/nextcloud/lib/src/api/updatenotification.openapi.dart
- packages/nextcloud/lib/src/api/uppush.openapi.dart
- packages/nextcloud/lib/src/api/user_status.openapi.dart
- packages/nextcloud/lib/src/api/weather_status.openapi.dart
as discussed in https://github.com/nextcloud/neon/pull/1324#discussion_r1432505618
> perf(dynamite): avoid duplicate uri parsing

- packages/neon/neon_dashboard/lib/src/app.dart
- packages/neon/neon_dashboard/lib/src/options.dart
- packages/neon/neon_files/lib/src/app.dart
- packages/neon/neon_files/lib/src/blocs/browser.dart
- packages/neon/neon_files/lib/src/blocs/files.dart
- packages/neon/neon_files/lib/src/options.dart
- packages/neon/neon_news/lib/src/app.dart
- packages/neon/neon_news/lib/src/blocs/articles.dart
- packages/neon/neon_news/lib/src/blocs/news.dart
- packages/neon/neon_news/lib/src/options.dart
- packages/neon/neon_notes/lib/src/app.dart
- packages/neon/neon_notes/lib/src/blocs/note.dart
- packages/neon/neon_notes/lib/src/blocs/notes.dart
- packages/neon/neon_notes/lib/src/options.dart
- packages/neon/neon_notifications/lib/src/app.dart
- packages/neon/neon_notifications/lib/src/blocs/notifications.dart
- packages/neon/neon_notifications/lib/src/options.dart
- packages/neon_framework/lib/src/blocs/accounts.dart
- packages/neon_framework/lib/src/blocs/apps.dart
- packages/neon_framework/lib/src/models/app_implementation.dart
- packages/neon_framework/lib/src/models/notifications_interface.dart
- packages/neon_framework/lib/src/pages/app_implementation_settings.dart
- packages/neon_framework/lib/src/pages/settings.dart
- packages/neon_framework/lib/src/router.dart
- packages/neon_framework/lib/src/router.g.dart
- packages/neon_framework/lib/src/settings/models/options_collection.dart
- packages/neon_framework/lib/src/settings/models/storage.dart
- packages/neon_framework/lib/src/utils/account_options.dart
- packages/neon_framework/test/options_collection_test.dart
- packages/neon_framework/test/settings_export_test.dart
Needed for https://github.com/nextcloud/neon/pull/600
The `Specific` and `App` parts were never needed in the class names. Also more aligned with the rest, using `AppImplementation` instead of `NextcloudApp`.
> refactor(neon_framework): Cleanup settings and options related class names

- packages/nextcloud/lib/src/api/core.openapi.dart
- packages/nextcloud/lib/src/api/core.openapi.g.dart
- packages/nextcloud/lib/src/api/core.openapi.json
- packages/nextcloud/lib/src/api/dav.openapi.dart
- packages/nextcloud/lib/src/api/dav.openapi.g.dart
- packages/nextcloud/lib/src/api/dav.openapi.json
- packages/nextcloud/lib/src/api/files_sharing.openapi.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.g.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.json
- packages/nextcloud/lib/src/api/spreed.openapi.dart
- packages/nextcloud/lib/src/api/spreed.openapi.g.dart
- packages/nextcloud/lib/src/api/spreed.openapi.json
- packages/nextcloud/lib/src/api/theming.openapi.dart
- packages/nextcloud/lib/src/api/theming.openapi.json
- packages/nextcloud/lib/src/patches/core/0-compatibility-27.1.json
- packages/nextcloud/test/spreed_test.dart
Closes https://github.com/nextcloud/neon/issues/1226
Draft for now, I'll wait until 28.0.1 has been tagged on server and notifications (although there are no diffs using the stable28 branches).
> chore(nextcloud): Update specs to 28.0.1

- packages/dynamite/dynamite_petstore_example/analysis_options.yaml
- packages/dynamite/dynamite_petstore_example/lib/petstore.openapi.dart
- packages/dynamite/dynamite_petstore_example/pubspec.yaml
- packages/dynamite/dynamite_petstore_example/pubspec_overrides.yaml
> feat(dynamite_petstore_example): add linting

- packages/neon/neon_dashboard/lib/src/pages/main.dart
- packages/neon_framework/lib/l10n/en.arb
- packages/neon_framework/lib/l10n/localizations.dart
- packages/neon_framework/lib/l10n/localizations_en.dart
- packages/neon_framework/lib/src/app.dart
- packages/neon_framework/lib/src/pages/settings.dart
- packages/neon_framework/lib/src/theme/server.dart
- packages/neon_framework/lib/src/theme/theme.dart
- packages/neon_framework/lib/src/utils/global_options.dart
- packages/neon_framework/lib/src/widgets/custom_background.dart
- packages/neon_framework/lib/widgets.dart
Closes https://github.com/nextcloud/neon/issues/939
I'm pretty sure this whole feature but also the way I implemented it is going to be quite controversial, but please go ahead reviewing :)
> feat(neon_framework): Support custom backgrounds

- packages/dynamite/dynamite/README.md
- packages/dynamite/dynamite/lib/src/models/dynamite_config/config.dart
- packages/dynamite/dynamite/lib/src/models/dynamite_config/config.g.dart
- packages/dynamite/dynamite/lib/src/openapi_builder.dart
- packages/nextcloud/build.yaml
- packages/nextcloud/lib/src/api/news.openapi.dart
- packages/nextcloud/lib/src/api/notes.openapi.dart
- packages/nextcloud/lib/src/api/uppush.openapi.dart
I don't think we should merge this without using it.
I just wanted to get feedback and avoid letting the branch just rot on my machine
> feat(dynamite): allow per spec configuration

- .github/renovate.json
The second rule is there to still disable patch updates.
I checked locally and it correctly generates a pr for the intl package which pana complained about in the nextcloud package.
> fix(ci): Let renovate update dependencies with zero as major version

- packages/file_icons/pubspec.yaml
- packages/sort_box/pubspec.yaml
Leaves nextcloud, dynamite and dynamite_runtime as non-private packages.
> chore: Set correct publish_to

- packages/neon_framework/lib/src/widgets/user_avatar.dart
If the user status was set to offline and error was thrown because there is no icon for offline and it shouldn't be shown anyway.
> fix(neon_framework): Skip displaying user status icon if offline

- packages/neon_framework/lib/src/widgets/linear_progress_indicator.dart
We always want to display it with the exact height to prevent items in a listview or column from jumping around because of the height difference.
> fix(neon_framework): Remove progress indicator height jumping around

- packages/neon_framework/analysis_options.yaml
- packages/neon_framework/lib/src/bloc/result.dart
- packages/neon_framework/lib/src/blocs/timer.dart
- packages/neon_framework/lib/src/pages/login_qr_code.dart
- packages/neon_framework/lib/src/settings/widgets/settings_category.dart
- packages/neon_framework/lib/src/settings/widgets/settings_list.dart
- packages/neon_framework/lib/src/utils/confirmation_dialog.dart
- packages/neon_framework/lib/src/utils/findable.dart
- packages/neon_framework/lib/src/utils/rename_dialog.dart
- packages/neon_framework/lib/src/utils/request_manager.dart
- packages/neon_framework/lib/src/widgets/custom_background.dart
- packages/neon_framework/lib/src/widgets/drawer_destination.dart
- packages/neon_framework/lib/src/widgets/image.dart
- packages/neon_framework/lib/src/widgets/list_view.dart
When adding new things now we are properly warned when there are missing docs.
> chore(neon_framework): Switch to file-level missing docs ignores

- commitlint.yaml
Melos uses the release scope when creating releases.
> chore(tool): Add commitlint release scope

- CHANGELOG.md
- packages/dynamite/dynamite/CHANGELOG.md
- packages/dynamite/dynamite/pubspec.yaml
- packages/dynamite/dynamite_runtime/CHANGELOG.md
- packages/dynamite/dynamite_runtime/pubspec.yaml
- packages/nextcloud/pubspec.yaml
Fix the mess from https://github.com/nextcloud/neon/pull/1361
> Fix publishing mess

- packages/nextcloud/README.md
Now live at https://pub.dev/packages/nextcloud, so no git dependency needed anymore :tada:
> chore(nextcloud): Remove outdated installation instructions

- packages/neon_framework/lib/src/blocs/apps.dart
Fixes https://github.com/nextcloud/neon/issues/1264
Fixes https://github.com/nextcloud/neon/issues/892
Initially I only wanted to fix the problem with the bloc of the notifications app getting disposed, but then I realized I also fixed case where the initial app is no longer available.
> fix(neon_framework): Correctly handle disappearing apps and the notifications app

- packages/dynamite/dynamite/lib/src/builder/built_object_serializer.dart
- packages/dynamite/dynamite/lib/src/builder/client.dart
- packages/dynamite/dynamite/lib/src/builder/generate_ofs.dart
- packages/dynamite/dynamite/lib/src/builder/resolve_enum.dart
- packages/dynamite/dynamite/lib/src/builder/resolve_mime_type.dart
- packages/dynamite/dynamite/lib/src/builder/serializer.dart
- packages/dynamite/dynamite/lib/src/helpers/built_value.dart
- packages/dynamite/dynamite/lib/src/helpers/type_result.dart
- packages/dynamite/dynamite/lib/src/models/type_result/base.dart
- packages/dynamite/dynamite/lib/src/models/type_result/some_of.dart
- packages/dynamite/dynamite/lib/src/models/type_result/type_result.dart
- packages/dynamite/dynamite/test/type_result_test.dart
- packages/dynamite/dynamite_end_to_end_test/lib/nested_ofs.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/request_body.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/responses.openapi.dart
- packages/nextcloud/lib/src/api/core.openapi.dart
towards: #1244
The main issue is some missing comma in the fulltype but propperly fixing this is a bit harder.
I've some eperiments locally but they require major restructures of dynamite so probably something I'll come back to after the neon release.
> refactor(dynamite): only use raw strings where necessary

- packages/neon/neon_dashboard/lib/src/blocs/dashboard.dart
- packages/neon/neon_dashboard/pubspec.yaml
- packages/neon/neon_files/lib/src/blocs/browser.dart
- packages/neon/neon_files/lib/src/blocs/files.dart
- packages/neon/neon_news/lib/src/blocs/article.dart
- packages/neon/neon_news/lib/src/blocs/articles.dart
- packages/neon/neon_news/lib/src/blocs/news.dart
- packages/neon/neon_news/pubspec.yaml
- packages/neon/neon_notes/lib/src/blocs/note.dart
- packages/neon/neon_notes/lib/src/blocs/notes.dart
- packages/neon/neon_notes/pubspec.yaml
- packages/neon/neon_notifications/lib/src/blocs/notifications.dart
- packages/neon/neon_notifications/pubspec.yaml
- packages/neon_framework/lib/src/blocs/accounts.dart
- packages/neon_framework/lib/src/blocs/apps.dart
- packages/neon_framework/lib/src/blocs/capabilities.dart
- packages/neon_framework/lib/src/blocs/first_launch.dart
- packages/neon_framework/lib/src/blocs/login_check_account.dart
- packages/neon_framework/lib/src/blocs/login_check_server_status.dart
- packages/neon_framework/lib/src/blocs/login_flow.dart
- packages/neon_framework/lib/src/blocs/next_push.dart
- packages/neon_framework/lib/src/blocs/push_notifications.dart
- packages/neon_framework/lib/src/blocs/unified_search.dart
- packages/neon_framework/lib/src/blocs/user_details.dart
- packages/neon_framework/lib/src/blocs/user_statuses.dart
Closes https://github.com/nextcloud/neon/issues/1372
For the neon_* packages this has not effect since they still have the global ignore set (which we should change eventually).
> refactor: Only make bloc factories internal

- packages/neon/neon_files/lib/l10n/en.arb
- packages/neon/neon_files/lib/l10n/localizations.dart
- packages/neon/neon_files/lib/l10n/localizations_en.dart
- packages/neon/neon_files/lib/src/blocs/files.dart
- packages/neon/neon_files/lib/src/widgets/actions.dart
- packages/neon_framework/lib/src/platform/android.dart
- packages/neon_framework/lib/src/platform/linux.dart
- packages/neon_framework/lib/src/platform/platform.dart
Closes https://github.com/nextcloud/neon/issues/1251
The sync is not well implemented, a bit broken and incompatible with web. On top of that is it not very useful in the current state. https://github.com/nextcloud/neon/issues/21 will reintroduce syncing but in a better way.
> fix(neon_files): Remove broken sync

- LICENSE
Without it GH complains we have no license set. I set it to AGPL-3.0 because most of the code is licensed under that license with a few exceptions.
> chore: Add license to root directory

- packages/neon_framework/lib/src/blocs/accounts.dart
- packages/neon_framework/lib/src/blocs/user_status.dart
- packages/neon_framework/lib/src/widgets/user_avatar.dart
This name is a bit simpler to use and is more aligned with the name of the app: user_status. Sometimes this was even already used incorrectly.
> refactor(neon_framework): Rename UserStatusBloc

- packages/dynamite/dynamite/example/lib/petstore.openapi.dart
- packages/dynamite/dynamite/example/lib/petstore.openapi.g.dart
- packages/dynamite/dynamite/lib/src/builder/resolve_interface.dart
- packages/dynamite/dynamite/lib/src/builder/resolve_ofs.dart
- packages/dynamite/dynamite_end_to_end_test/lib/all_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/all_of.openapi.g.dart
- packages/dynamite/dynamite_end_to_end_test/lib/nested_ofs.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/nested_ofs.openapi.g.dart
- packages/nextcloud/lib/src/api/dav.openapi.dart
- packages/nextcloud/lib/src/api/dav.openapi.g.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.g.dart
- packages/nextcloud/lib/src/api/spreed.openapi.dart
- packages/nextcloud/lib/src/api/spreed.openapi.g.dart
- packages/nextcloud/lib/src/api/user_status.openapi.dart
- packages/nextcloud/lib/src/api/user_status.openapi.g.dart
Cleaner code and allows us to easily document all generated interfaces.
This is breaking (also for NC)
> refactor(dynamite)!: remove unecessary allOf interfaces

- .github/renovate.json
- packages/nextcloud/pubspec.yaml
Fixes https://github.com/nextcloud/neon/issues/1445
0.17.0 is the first version that has null-safety, so we can't go lower (although I couldn't find any breaking changes within the last few years).
I had to update the renovate config as version ranges don't play nice with our current dependency update strategy.
> fix(nextcloud): Use version range for intl dependency

- .github/renovate.json
Fixes the wrong bumps from https://github.com/nextcloud/neon/pull/1347 introduced by https://github.com/nextcloud/neon/pull/1446
(I tested this locally and it works)
> fix(ci): Limit intl range updates to nextcloud package

- .gitmodules
- packages/nextcloud/lib/src/api/core.openapi.dart
- packages/nextcloud/lib/src/api/core.openapi.g.dart
- packages/nextcloud/lib/src/api/core.openapi.json
- packages/nextcloud/lib/src/api/files.openapi.dart
- packages/nextcloud/lib/src/api/files.openapi.g.dart
- packages/nextcloud/lib/src/api/files.openapi.json
- packages/nextcloud/lib/src/api/files_sharing.openapi.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.g.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.json
- packages/nextcloud/lib/src/api/files_trashbin.openapi.dart
- packages/nextcloud/lib/src/api/files_trashbin.openapi.g.dart
- packages/nextcloud/lib/src/api/files_trashbin.openapi.json
- packages/nextcloud/lib/src/api/spreed.openapi.dart
- packages/nextcloud/lib/src/api/spreed.openapi.g.dart
- packages/nextcloud/lib/src/api/spreed.openapi.json
- packages/nextcloud/lib/src/api/theming.openapi.dart
- packages/nextcloud/lib/src/api/theming.openapi.g.dart
- packages/nextcloud/lib/src/api/theming.openapi.json
- tool/generate-specs.sh
It allows us to get improvements and fixes from openapi-extractor much quicker. This is especially helpful since there are multiple repos we get the specs from and each of those would need to individually update their version.
It was like this some time ago and I removed it to avoid running into compatibility problems, but I don't think any problems will appear in the future, so it should be safe to track our own version again.
> refactor(tool)!: Pin our own version of openapi-extractor

- packages/app/linux/flutter/generated_plugin_registrant.cc
- packages/app/linux/flutter/generated_plugins.cmake
- packages/app/pubspec.lock
- packages/neon_framework/lib/src/theme/dialog.dart
- packages/neon_framework/lib/src/widgets/dialog.dart
- packages/neon_framework/pubspec.yaml
- packages/neon_framework/test/dialog_test.dart
Extracted from https://github.com/nextcloud/neon/pull/1378 and added a test so it can be merged already.
> feat(neon_framework): Add emoji picker dialog

- packages/neon_framework/test/dialog_test.dart
When hitting enter on the keyboard the dialog should (and does) automatically submit the result and pop.
We do not need to tap the save action anymore. Doing so produces a warning that the save action is no longer present on the screen.
> fix(neon_framework): warning in the dialog unit tests 

- tool/find-untested-neon-apis.sh
After moving the neon_framework package this script didn't check it any more.
We didn't use any untested APIs since the, but it should have been failing on https://github.com/nextcloud/neon/pull/1486.
> fix(tool): Fix finding untested Neon APIs

- packages/neon/neon_news/lib/src/widgets/articles_view.dart
The line `final article = sorted[index];` was failing when opening the articles view initially, because the length was null which lead to an infinite amount of items. The length should always be passed and not conditionally.
> fix(neon_news): Fix invalid index access

- packages/neon_framework/lib/src/widgets/image.dart
Some endpoints return 201 which is of course not correct, but this is the only way we can fix it.
Disabling the status code check is not a good idea and allowing all 2xx neither.
> fix(neon_framework): Allow 201 status code when loading images

- packages/app/android/app/build.gradle
With any version lower than 24 we can't build the app in debug mode (release mode works though :woman_shrugging:).
This means only support Android 7.0+ which is ok IMO because it was released in 2016.
> fix(app): Increase Android minSdkVersion to 24 to fix debug builds

- packages/neon_framework/lib/src/theme/dialog.dart
- packages/neon_framework/lib/src/widgets/dialog.dart
Fixes https://github.com/nextcloud/neon/issues/1478
The height constraint should have never been there. In the emoji picker dialog we still need it.
> fix(neon_framework): Fix settings page height

- packages/neon/neon_files/lib/src/blocs/browser.dart
- packages/neon/neon_files/lib/src/widgets/browser_view.dart
- packages/neon_framework/lib/src/utils/request_manager.dart
- packages/neon_framework/test/request_manager_test.dart
depends on: #1505 
All in all this does improve the performance if an api request fails or completes before the cache has emitted a value.
> refactor(neon_framework)!: remove emitEmptyCache option from request manager

- packages/app/pubspec.lock
- packages/dynamite/dynamite/example/pubspec.yaml
- packages/dynamite/dynamite/lib/src/helpers/version_checker.dart
- packages/dynamite/dynamite/pubspec.yaml
- packages/dynamite/dynamite_end_to_end_test/pubspec.yaml
- packages/dynamite/dynamite_runtime/pubspec.yaml
- packages/nextcloud/pubspec.yaml
Looks like renovate has beaten me by a few minutes.
This replaces: #1509
> chore: update built_value to 8.9.0

- packages/dynamite/dynamite/lib/src/builder/serializer.dart
- packages/dynamite/dynamite_end_to_end_test/lib/any_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/documentation.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/nested_ofs.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/one_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/one_of.openapi.g.dart
- packages/dynamite/dynamite_end_to_end_test/lib/one_of.openapi.json
- packages/dynamite/dynamite_end_to_end_test/lib/parameters.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/some_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/type_defs.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/test/one_of_test.dart
- packages/nextcloud/lib/src/api/core.openapi.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.dart
- packages/nextcloud/lib/src/api/provisioning_api.openapi.dart
- packages/nextcloud/lib/src/api/sharebymail.openapi.dart
- packages/nextcloud/lib/src/api/spreed.openapi.dart
- packages/nextcloud/lib/src/api/user_status.openapi.dart
towards #1058 
Looks like that migrating to records already fixed the deserialization. And now only serialization is broken.
This is due to a limitation/oversight in the upstream `StandartJsonPlugin` that is responsible to convert the intermediate built_value wire format into a Json output.
```dart
@override
Object? afterSerialize(Object? object, FullType specifiedType) {
if (object is List &&
specifiedType.root != BuiltList &&
specifiedType.root != BuiltSet &&
specifiedType.root != JsonObject) {
if (specifiedType.isUnspecified) {
return _toMapWithDiscriminator(object);
} else {
return _toMap(object, _needsEncodedKeys(specifiedType));
}
} else {
return object;
}
}
```
I'll ask upstream. Maybe we can find a simple solution (I don't really want to write a replacement to the json plugin).
> fix(dynamite): serialization of someOfs with an array member

- packages/neon_framework/lib/src/models/account.dart
- packages/neon_framework/lib/src/widgets/image.dart
- packages/neon_framework/test/account_test.dart
Closes https://github.com/nextcloud/neon/issues/1462
In the end I needed this change for https://github.com/nextcloud/neon/issues/1125 and this way it was easy to add tests.
> refactor(neon_framework): Move authorization headers to Account

- packages/nextcloud_test/bin/generate_presets.dart
https://github.com/nextcloud/neon/pull/1527#discussion_r1467241825
> fix(nextcloud_test): Sort server versions to correctly get the highest one

- packages/nextcloud/test/dashboard_test.dart
With https://github.com/nextcloud/neon/pull/1527 (27.1.6) we get the changes from https://github.com/nextcloud/recommendations/pull/668 so that no app supports v2 anymore (at least of the ones that are displayed). Now this change isn't present in the 28 version so it gets really messy. For now I just removed the check to ensure it will work correctly. It's sad that the dashboard tests cause so much trouble and we are not really able to test them (although we have shown already that they are working correctly).
> fix(nextcloud): Fix dashboard v2 tests

- packages/dynamite/dynamite_runtime/lib/http_client.dart
- packages/dynamite/dynamite_runtime/test/client_test.dart
- packages/neon_framework/lib/src/models/account.dart
- packages/neon_framework/pubspec.yaml
- packages/nextcloud/lib/nextcloud.dart
- packages/nextcloud_test/lib/src/test_client.dart
- packages/nextcloud_test/pubspec.yaml
…t is persiststent
#1434 for dynamite_runtime
towards:: #1536 
Long term we should use the neon sqflite backend for this (I'll open an issue after this lands).
> refactor(dynamite_runtime): stop exporting cookie_jar

- packages/dynamite/dynamite/lib/src/helpers/dart_helpers.dart
- packages/neon/neon_dashboard/lib/src/pages/main.dart
- packages/neon_framework/lib/src/widgets/dialog.dart
- packages/neon_framework/lib/src/widgets/user_avatar.dart
- packages/neon_framework/test/dialog_test.dart
- packages/neon_framework/test/user_status_bloc_test.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.json
- packages/nextcloud/lib/src/api/spreed.openapi.dart
- packages/nextcloud/lib/src/api/spreed.openapi.json
- packages/nextcloud/lib/src/api/theming.openapi.dart
- packages/nextcloud/lib/src/api/theming.openapi.json
- packages/nextcloud/lib/src/api/user_status.openapi.dart
- packages/nextcloud/lib/src/api/user_status.openapi.g.dart
- packages/nextcloud/lib/src/api/user_status.openapi.json
- packages/nextcloud/lib/src/api/weather_status.openapi.dart
- packages/nextcloud/lib/src/api/weather_status.openapi.g.dart
- packages/nextcloud/lib/src/api/weather_status.openapi.json
- packages/nextcloud/test/user_status_test.dart
Depends on https://github.com/nextcloud/neon/issues/1441 (then the first commit won't be breaking).
> feat(nextcloud)!: Update server to 28.0.2

- packages/neon_framework/lib/src/blocs/apps.dart
Fix https://github.com/nextcloud/neon/issues/1454
The problem was that the active app was overridden after it was set by the quick action shortcut.
To prevent it we need to skip setting the active app if there is one already, but that breaks updating the active app in case the current active app is not supported anymore, so I fixed that too.
> Fix quick actions not working

- .github/workflows/lint.yml
- tool/find-dart-html-usage.sh
- tool/find-dart-io-usage.sh
dart:html is not used yet anywhere, but will be in the future. The proper replacement is universal_html that also allows being compiled on vm.
> feat(tool,ci): Check for dart:html usage

- packages/neon/neon_dashboard/lib/src/pages/main.dart
In case the weather status was disabled a widget would still be returned and the intersperse would insert a spacing. Each status needs to individually add the padding so that it is only there in case it is actually displayed.
> fix(neon_dashboard): Correctly center statuses in case some are missing

- packages/neon_framework/lib/src/testing/mock_server.dart
- packages/neon_framework/lib/testing.dart
- packages/neon_framework/test/user_status_bloc_test.dart
- packages/neon_framework/test/weather_status_bloc_test.dart
A single reusable implementation.
> refactor(neon_framework): Deduplicate mock server implementation in tests

- packages/app/lib/apps.dart
- packages/app/pubspec.lock
- packages/app/pubspec.yaml
- packages/neon/neon_notifications/lib/src/pages/main.dart
- packages/neon_framework/lib/neon.dart
- packages/neon_framework/lib/src/app.dart
- packages/neon_framework/lib/src/blocs/accounts.dart
- packages/neon_framework/lib/src/blocs/apps.dart
- packages/neon_framework/lib/src/pages/home.dart
- packages/neon_framework/lib/src/pages/settings.dart
- packages/neon_framework/lib/src/router.dart
- packages/neon_framework/lib/src/settings/utils/settings_export_helper.dart
- packages/neon_framework/lib/src/widgets/app_bar.dart
- packages/neon_framework/test/drawer_test.dart
- packages/neon_framework/test/settings_export_test.dart
We only accept a Set to begin with, so we can make it a Set everywhere.
> refactor(neon_framework): Make AppImplementations a BuiltSet

- packages/neon_framework/lib/src/router.dart
Extracted from https://github.com/nextcloud/neon/pull/372
> chore(neon_framework): Remove unnecessary asserts ensuring nothing is leaked to the browser history

- packages/neon/neon_dashboard/pubspec.yaml
- packages/neon/neon_dashboard/test/bloc_test.dart
No need to pull in a dependency for such a simple thing.
> refactor(neon_dashboard): Stop using collection

- packages/app/pubspec.lock
- packages/app/pubspec.yaml
- packages/app/pubspec_overrides.yaml
- packages/neon_framework/pubspec.yaml
- packages/neon_framework/pubspec_overrides.yaml
The new package_info_plus is not going to be released soon [comment](https://github.com/fluttercommunity/plus_plugins/pull/2605#issuecomment-1954955437).
Let's override it for now to unblock:
#1609 
#1607
#1627
> chore(deps): override package_info_plus to allow web 0.5.0

- packages/neon_framework/lib/src/blocs/user_status.dart
Apparently the endpoint can return 404 without any data, instead of returning an empty status.
> fix(neon_framework): Handle missing user status

- packages/nextcloud/lib/src/helpers/core.dart
Aligned with https://github.com/nextcloud/server/blob/master/lib/public/Share/IShare.php
I had to use the value backed enum because it seems like 14 was just skipped. In the future we might also want to just remove the deprecated values, so this prepares us for that as well.
> fix(nextcloud): Add missing share types

- packages/neon_framework/lib/src/blocs/apps.dart
- packages/neon_framework/lib/src/models/app_implementation.dart
Will help with https://github.com/nextcloud/neon/issues/356 (different ID spreed vs. talk) and https://github.com/nextcloud/neon/issues/355 (multiple IDs photos vs. memories).
Sadly it's not possible to add tests because the whole Bloc has no tests yet.
> feat(neon_framework): Allow additional matching app IDs

- .github/workflows/publish.yaml
Avoids cancelling the other jobs when a job in the matrix fails.
> fix(ci): Do not fail-fast in publish matrix

- packages/neon/neon_talk/lib/src/widgets/message_preview.dart
- packages/neon/neon_talk/test/message_preview_test.dart
System messages already contain the user's name as a mention, so it doesn't need to be displayed again.
> fix(neon_talk): Hide the user name in previews for system messages

- packages/neon/neon_talk/lib/src/pages/main.dart
No need to access the active account as the room already contains the actorId.
> refactor(neon_talk): Use the already available actorId

- tool/generate-dynamite-e2e-test.sh
- tool/generate-dynamite-petstore-example.sh
- tool/generate-nextcloud.sh
The logs say that `dart pub run` is deprecated, so we shouldn't use it anymore.
> chore(tool): Use `dart run` instead of deprecated `dart pub run`

- packages/neon/neon_talk/lib/src/pages/main.dart
- packages/neon/neon_talk/lib/src/widgets/room_avatar.dart
- packages/neon/neon_talk/test/room_avatar_test.dart
- packages/nextcloud/test/fixtures/spreed/avatar/delete_avatar.regexp
- packages/nextcloud/test/fixtures/spreed/avatar/get_avatar.regexp
- packages/nextcloud/test/fixtures/spreed/avatar/get_avatar_dark.regexp
- packages/nextcloud/test/fixtures/spreed/avatar/set_emoji_avatar.regexp
- packages/nextcloud/test/spreed_test.dart
Towards https://github.com/nextcloud/neon/issues/356
The coverage is not 100% as I see no point in testing all the other room types just to see that they have the correct icon.
> feat(neon_talk): Add room avatars

- packages/neon/neon_talk/lib/src/widgets/room_avatar.dart
- packages/neon_framework/lib/src/widgets/account_switcher_button.dart
- packages/neon_framework/lib/src/widgets/account_tile.dart
- packages/neon_framework/lib/src/widgets/user_avatar.dart
Will help with https://github.com/nextcloud/neon/pull/1661.
NeonApiImage and NeonUriImage already provide this kind of API, so this just makes it easier to use all of them when the used account is the currently active one.
> refactor(neon_framework): Allow using NeonUserAvatar without specifying the account

- packages/neon/neon_talk/lib/src/utils/message.dart
- packages/neon/neon_talk/lib/src/widgets/message_preview.dart
- packages/neon/neon_talk/test/message_preview_test.dart
A user might send a formatted message that includes newlines. This looks pretty bad in previews because only the first line will be shown.
> feat(neon_talk): Remove newlines in message previews

- packages/dynamite/dynamite/lib/src/builder/generate_ofs.dart
- packages/dynamite/dynamite_end_to_end_test/lib/any_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/documentation.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/nested_ofs.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/one_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/parameters.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/some_of.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/type_defs.openapi.dart
- packages/dynamite/dynamite_runtime/lib/src/utils/some_of_validators.dart
- packages/nextcloud/lib/src/api/core.openapi.dart
- packages/nextcloud/lib/src/api/files_sharing.openapi.dart
- packages/nextcloud/lib/src/api/provisioning_api.openapi.dart
- packages/nextcloud/lib/src/api/sharebymail.openapi.dart
- packages/nextcloud/lib/src/api/spreed.openapi.dart
- packages/nextcloud/lib/src/api/user_status.openapi.dart
- packages/nextcloud/lib/src/api/weather_status.openapi.dart
An error message like `At least one of [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null] must not be null` for anyOf is really not helpful and we should show the field names instead.
> feat(dynamite)!: Show field names in oneOf/anyOf validation errors

- packages/neon_framework/test/image_test.dart
We already have those mocks in our common mocks, so we don't need to redefine them here.
> refactor(neon_framework): Remove duplicate mock types

- packages/neon_framework/lib/src/widgets/user_avatar.dart
https://github.com/nextcloud/neon/pull/1664 introduced the problem that the scaled size was selected based on the emoji which wasn't accounting for the DND status. Just removing the SizedBox fixed the problem entirely.
The emoji was also a bit big compared to the other icons, so decreased it's size a bit.
> fix(neon_framework): Fix NeonUserAvatar status sizes

- .fvmrc
Fixes https://github.com/nextcloud/neon/pull/1714 introduced by https://github.com/nextcloud/neon/pull/1712.
This change gets auto-generated, so we have to add it.
> chore(tool): Update fvm config

- packages/neon_framework/lib/src/pages/route_not_found.dart
- packages/neon_framework/lib/src/router.dart
- packages/neon_framework/lib/src/router.g.dart
Fixes https://github.com/nextcloud/neon/issues/1649
I didn't know about GoRouter.onException before, it's exactly what should have been used from the beginning.
> fix(neon_framework): Handle unknown routes better

- packages/neon_framework/lib/src/widgets/user_avatar.dart
It should only take up the size of the status indicator and not the whole avatar.
> fix(neon_framework): Correctly scale status loading indicator in NeonUserAvatar

- .cspell/misc.txt
- packages/neon_framework/lib/src/utils/request_manager.dart
- packages/neon_framework/pubspec.yaml
- packages/neon_framework/test/request_manager_test.dart
- packages/nextcloud/lib/src/utils/http_date_parser.dart
- packages/nextcloud/lib/src/webdav/file.dart
- packages/nextcloud/lib/utils.dart
- packages/nextcloud/pubspec.yaml
- packages/nextcloud/test/http_date_test.dart
- packages/nextcloud/test/webdav_test.dart
Fixes the issue of parsing an RFC822 date with a timezone offset.
The code is pulled in from the upstream http_parser package and adjusted to also handle our use case.
I disabled failing lint rules instead of fixing them to keep the code similar to upstream.
As a bonus I also converted the code to directly use a tz.TZDateTime so we can avoid parsing it later on.
> feat(nextcloud): add custom http date parser to support rfc822 time zone offsets

- packages/neon_framework/lib/src/utils/request_manager.dart
This error is triggered when a bloc or widget is disposed while the request is still running. Usually only happens in the NeonImage widgets.
Best reviewed with https://github.com/nextcloud/neon/pull/1767/files?w=1
> fix(neon_framework): Supress subject closed errors in RequestManager

- packages/neon_framework/lib/src/storage/request_cache.dart
- packages/neon_framework/lib/src/utils/request_manager.dart
- packages/neon_framework/test/persistence_test.dart
- packages/neon_framework/test/request_manager_test.dart
> refactor(neon_framework): add account column to RequestCache

- packages/nextcloud/README.md
Forgot to add it in https://github.com/nextcloud/neon/pull/1775
> chore(nextcloud): Advertise drop_account 2.5 compatibility

- packages/neon/neon_talk/lib/src/pages/room.dart
Closes https://github.com/nextcloud/neon/issues/1778
No extra check for the room type is necessary because the status will just be null for rooms that are not 1:1s.
> feat(neon_talk): Show user status on room page

- packages/neon/neon_talk/lib/src/widgets/room_avatar.dart
Testing the other cases has no point, so we don't do it. The added ignores bump the coverage to 100%
> chore(neon_talk): Ignore irrelevant coverage parts in room avatar

- packages/neon_framework/lib/src/utils/request_manager.dart
- packages/nextcloud/lib/src/webdav/file.dart
Fixes https://github.com/nextcloud/neon/issues/1762
> fix(neon_framework): Catch FormatExceptions when parsing Http-dates in RequestManager

- .cspell/tools.txt
- packages/neon/neon_talk/test/room_bloc_test.dart
- packages/neon_framework/lib/src/storage/request_cache.dart
- packages/neon_framework/lib/src/utils/request_manager.dart
- packages/neon_framework/test/persistence_test.dart
- packages/neon_framework/test/request_manager_test.dart
No matter what the cache parameters are we will always also query the cached data.
Doing both in one go saves us a round trip to the DB and imo also makes the request manager a bit easier to read.
This is the result of my effort to validate the `etag` and `expires` field in DB which turned out to not be viable.
> feat(neon_framework): request cache return CacheParameters on get

- packages/neon_framework/lib/src/utils/request_manager.dart
- packages/neon_framework/test/request_manager_test.dart
As discussed in: https://github.com/nextcloud/neon/pull/1787#discussion_r1540738969
This will result in faster loading of the cached data with an extra ui refresh when the loading is done.
> feat(neon_framework): emit cached data before fetching new cache parameters

- packages/neon/neon_talk/lib/src/pages/room.dart
Instead of using the room that is passed to the widget the room of the bloc should be used because it will be updated on refresh. In case the room avatar would change it will be correctly reflected now while previously the room page had to be closed, the room list reloaded and the room page opened again.
> refactor(neon_talk): Use room of RoomBloc on RoomPage

- packages/nextcloud/test/spreed_test.dart
Should have been removed in https://github.com/nextcloud/neon/pull/1832 because we no longer test against spreed 16.
> chore(nextcloud): Remove test skip on spreed 16

- packages/dynamite/dynamite/lib/src/helpers/dart_helpers.dart
- packages/dynamite/dynamite_runtime/lib/src/client/client.dart
- packages/dynamite/dynamite_runtime/test/client_test.dart
- packages/neon_framework/lib/src/utils/request_manager.dart
- tool/find-untested-neon-apis.sh
I noticed these tests are no longer used by any generated code and can be replaced by just using the send method.
> refactor(dynamite_runtime)!: Remove executeRequest and executeRawRequest methods

- packages/neon/neon_dashboard/lib/src/pages/main.dart
- packages/neon_framework/lib/src/blocs/weather_status.dart
- packages/neon_framework/test/weather_status_bloc_test.dart
Fixes https://github.com/nextcloud/neon/issues/1555
> fix(neon_framework): Stop loading forecast in weather status without location

- packages/dynamite/dynamite/lib/src/builder/client.dart
- packages/file_icons/bin/file_icons.dart
- packages/neon/neon_files/lib/src/pages/details.dart
- packages/neon/neon_news/lib/src/widgets/articles_view.dart
- packages/neon_framework/lib/src/pages/app_implementation_settings.dart
- packages/neon_framework/lib/src/pages/login_check_account.dart
- packages/neon_framework/lib/src/pages/login_check_server_status.dart
- packages/neon_framework/lib/src/pages/settings.dart
- packages/neon_framework/lib/src/widgets/app_bar.dart
Towards https://github.com/nextcloud/neon/issues/696
> refactor: Stop using spread list operator

- .github/workflows/publish.yaml
The Publish workflow also needs to use melos to generate the overrides which are no longer committed https://github.com/nextcloud/neon/pull/1876.
> fix(ci): Use melos for building the app

- .gitignore
- packages/app/pubspec.lock
- packages/app/pubspec_overrides.yaml
- packages/dynamite/dynamite/example/pubspec_overrides.yaml
- packages/dynamite/dynamite/pubspec_overrides.yaml
- packages/dynamite/dynamite_end_to_end_test/pubspec_overrides.yaml
- packages/dynamite/dynamite_runtime/pubspec_overrides.yaml
- packages/file_icons/pubspec_overrides.yaml
- packages/neon/neon_dashboard/pubspec_overrides.yaml
- packages/neon/neon_files/pubspec_overrides.yaml
- packages/neon/neon_news/pubspec_overrides.yaml
- packages/neon/neon_notes/pubspec_overrides.yaml
- packages/neon/neon_notifications/pubspec_overrides.yaml
- packages/neon/neon_talk/pubspec_overrides.yaml
- packages/neon_framework/pubspec_overrides.yaml
- packages/neon_lints/example/pubspec_overrides.yaml
- packages/nextcloud/pubspec_overrides.yaml
- packages/nextcloud_test/pubspec_overrides.yaml
- packages/sort_box/pubspec_overrides.yaml
With https://github.com/nextcloud/neon/pull/1876 we no longer have the overrides because melos generates them in the CI for us, but renovate doesn't do that so it picks up the git references which lead to https://github.com/nextcloud/neon/pull/1879.
> Revert "chore: Add pubspec_overrides.yaml to .gitignore"

- packages/neon_framework/lib/src/blocs/maintenance_mode.dart
When switching to another account and back will throw an error because the home page listens to the same stream again.
> fix(neon_framework): Use broadcast stream in maintenance mode bloc

- packages/neon_framework/lib/src/theme/icons.dart
- packages/neon_framework/lib/src/utils/adaptive.dart
The target platform can not be overridden in tests (while the theme can), so it should not be used anywhere. For the icons we still have to use it because only on Apple platforms the Cupertino icons are actually available.
> refactor(neon_framework): Move cupertino platform check to AdaptiveIcons

- packages/neon/neon_talk/lib/neon_talk.dart
- packages/neon/neon_talk/lib/src/pages/room.dart
- packages/neon/neon_talk/lib/src/theme.dart
- packages/neon_framework/lib/src/models/app_implementation.dart
Fixes https://github.com/nextcloud/neon/issues/1740
This not only adds the padding so that the scroll bar never overlaps the message time, but also moves the constraint into the list itself so that the scrollbar is always at the most right position regardless of the list width and you can scroll everywhere.
I didn't find any way to use SliverConstrainedCrossAxis because it aligns everything to the left but the messages should be centered. Maybe @Leptopoda you know what would make this work.
> fix(neon_talk): Improve message list constraints

- packages/neon/neon_talk/lib/src/theme.dart
I thought this method didn't need to be implement if not called manually, but I just saw the UnimplementedError show up.
> fix(neon_talk): Add missing TalkTheme.lerp implementation

- packages/dynamite/dynamite/build.yaml
before that running build_runner inside dynamite also tried to execute dynamite itself.
Also formats the build.yaml to use single quotes. The same we have everywhere else in the project.
> fix(dynamite): build config to allow built_value_generator running inside dynamite

- packages/neon/neon_talk/lib/src/theme.dart
This file is not relevant for testing and coverage, so it can just be ignore to avoid dragging down the coverage rate.
> chore(neon_talk): Remove TalkTheme from coverage

- packages/neon/neon_talk/test/room_bloc_test.dart
Forgot to write these tests in https://github.com/nextcloud/neon/pull/1935
> test(neon_talk): Test last common read emitted

- packages/dynamite/dynamite/lib/src/builder/resolve_type.dart
- packages/dynamite/dynamite/lib/src/builder/state.dart
- packages/dynamite/dynamite/lib/src/models/openapi/schema.dart
- packages/dynamite/dynamite/lib/src/models/openapi/schema.g.dart
- packages/dynamite/dynamite/lib/src/openapi_builder.dart
- packages/dynamite/dynamite/pubspec.yaml
- packages/dynamite/dynamite/test/openapi_spec_test.dart
I did not find a better solution yet.
In theory this already allows us to fetch schemas fro other sources like local filesystem or remote servers.
I did not observe any performance penalty.
Towards: #933
> fix(dynamite): json schema reference resolving

- packages/nextcloud/README.md
Forgot to remove it when dropping server 26.
> chore(nextcloud): Remove notifications 26 from support table

- .github/workflows/dart.yml
This should fail right now because of https://github.com/nextcloud/neon/pull/1970, but once that is merged and this is rebased it should pass.
> feat(ci): Fail on outdated pubspec.lock

- packages/nextcloud/lib/src/webdav/client.dart
- packages/nextcloud/test/webdav_test.dart
Fixes https://github.com/nextcloud/neon/issues/1988
I'm unsure how to actually test this, as the PHP internal server doesn't return chunked responses itself. The only way I see is by mocking the client and returning a chunked response manually, but that could still go wrong.
> fix(nextcloud): Make WebDAV get operations work with chunked responses

- packages/neon/neon_dashboard/lib/src/widgets/widget_item.dart
This can happen for example with formatted Talk messages that have more than one line which is used as the subtitle. Did the same for the title to prevent the same problem there if it would ever happen.
> fix(neon_dashboard): Only allow single lines in items

- packages/neon/neon_files/lib/src/utils/task.dart
- packages/nextcloud/lib/src/webdav/client.dart
Replaces https://github.com/nextcloud/neon/pull/1987
For reference: https://github.com/saber-notes/saber/issues/945 https://github.com/saber-notes/saber/issues/1232
> docs(nextcloud): Clarify why setting Content-Length for WebDAV PUT requests is important

- packages/app/android/app/build.gradle
The ndk version will fall back to the one supported by the Android Gradle Plugin
Should be safe to do: https://github.com/flutter/flutter/issues/139427#issuecomment-1989024985
> fix(app): remove ndk version constraint

- packages/neon_framework/lib/src/router.dart
Closes https://github.com/nextcloud/neon/issues/1720
Apps shouldn't have to match against `/index.php/...` routes as well. In case the route is not found and opened in a browser the index.php is prepended again conditionally (mod rewrite means / will point to /index.php in the web server).
> fix(neon_framework): Use clean URLs for routing

- packages/neon_framework/lib/neon.dart
- packages/neon_framework/lib/src/platform/android.dart
- packages/neon_framework/lib/src/platform/linux.dart
- packages/neon_framework/lib/src/platform/web.dart
The database was loading successfully on web in debug mode, but not in release mode. As per https://github.com/srawlins/timezone/issues/68#issuecomment-1366153638 the "normal" way to load the database just works fine on web, so we don't need to have the platform handle it and can use a single method for it.
> fix(neon_framework): Fix loading timezone database on web

- packages/nextcloud/test/fixtures/weather_status/set_location.regexp
- packages/nextcloud/test/fixtures/weather_status/use_personal_address.regexp
- packages/nextcloud/test/weather_status_test.dart
Possible since https://github.com/nextcloud/neon/issues/1492
> test(nextcloud): Add test for weather_status usePersonalAddress

- packages/neon_framework/lib/src/blocs/accounts.dart
- packages/neon_framework/lib/src/blocs/apps.dart
- packages/neon_framework/lib/src/utils/account_options.dart
Fixes https://github.com/nextcloud/neon/pull/2020
I had to revert some of the changes of that PR because the two methods were calling each other causing an infinite loop resulting in a stackoverflow.
> fix(neon_framework): Fix cyclic dependency between AccountOptions and AppsBloc

- packages/neon/neon_talk/lib/src/widgets/rich_object/file.dart
If the photos app is not installed or the size metadata is somehow not available the desired size is not passed to the API call. Unintuitively this doesn't mean the image is returned in it's original size, but instead a very small square image is returned. The -1 value is not documented anywhere (I'll fix that in the upstream docs) but I found it while checking how the web frontend handles this problem.
> fix(neon_talk): Use automatic sizing for image file rich objects

- packages/neon/neon_dashboard/test/widget_test.dart
- packages/neon/neon_talk/test/actor_avatar_test.dart
- packages/neon/neon_talk/test/main_page_test.dart
- packages/neon/neon_talk/test/message_test.dart
- packages/neon/neon_talk/test/rich_object_test.dart
- packages/neon/neon_talk/test/room_avatar_test.dart
- packages/neon/neon_talk/test/room_page_test.dart
- packages/neon_framework/lib/src/testing/utils.dart
- packages/neon_framework/test/dialog_test.dart
- packages/neon_framework/test/drawer_test.dart
- packages/neon_framework/test/user_avatar_test.dart
Avoids nesting multiple providers in the tests or having to use MultiProvider manually.
> feat(neon_framework): Allow passing Providers through TestApp

- .cspell/misc.txt
- commitlint.yaml
- packages/cookie_store/BSD-3-Clause.txt
- packages/cookie_store/analysis_options.yaml
- packages/cookie_store/lib/cookie_store.dart
- packages/cookie_store/lib/src/cookie_persistence.dart
- packages/cookie_store/lib/src/cookie_store.dart
- packages/cookie_store/lib/src/storable_cookie.dart
- packages/cookie_store/lib/src/utils.dart
- packages/cookie_store/pubspec.yaml
- packages/cookie_store/pubspec_overrides.yaml
- packages/cookie_store/test/cookie_store_conformance_test.dart
- packages/cookie_store/test/storable_cookie_test.dart
- packages/cookie_store/test/utils_test.dart
- packages/cookie_store_conformance_tests/BSD-3-Clause.txt
- packages/cookie_store_conformance_tests/analysis_options.yaml
- packages/cookie_store_conformance_tests/lib/cookie_store_conformance_tests.dart
- packages/cookie_store_conformance_tests/lib/src/deletion_tests.dart
- packages/cookie_store_conformance_tests/lib/src/domain_matching_tests.dart
- packages/cookie_store_conformance_tests/lib/src/expiration_tests.dart
- packages/cookie_store_conformance_tests/lib/src/http_only_cookie_tests.dart
- packages/cookie_store_conformance_tests/lib/src/path_matching_tests.dart
- packages/cookie_store_conformance_tests/lib/src/persist_cookies_tests.dart
- packages/cookie_store_conformance_tests/lib/src/secure_cookie_tests.dart
- packages/cookie_store_conformance_tests/lib/src/sorting_tests.dart
- packages/cookie_store_conformance_tests/lib/src/utils.dart
- packages/cookie_store_conformance_tests/pubspec.yaml
- packages/cookie_store_conformance_tests/pubspec_overrides.yaml
extracted from: #1907
Just a cherry pick with the `CookieJarAdapter` removed and the fixed typo
> feat(cookie_store): add compliance oriented cookie_jar alternative

- packages/neon_framework/lib/src/blocs/apps.dart
- packages/neon_framework/lib/src/pages/home.dart
- packages/neon_framework/lib/src/pages/login_check_server_status.dart
- packages/neon_framework/lib/src/utils/server_version.dart
- packages/nextcloud/lib/src/helpers/common.dart
- packages/nextcloud/lib/src/helpers/core.dart
Exposes all checks which will be necessary for apps to check what version is actually used.
> refactor(neon_framework): Cleanup version checks

- .cspell/misc.txt
- packages/app/pubspec.lock
- packages/app/pubspec_overrides.yaml
- packages/cookie_store/lib/cookie_store.dart
- packages/cookie_store/lib/src/cookie_jar_adapter.dart
- packages/cookie_store/pubspec.yaml
- packages/neon/neon_dashboard/pubspec_overrides.yaml
- packages/neon/neon_files/pubspec_overrides.yaml
- packages/neon/neon_news/pubspec_overrides.yaml
- packages/neon/neon_notes/pubspec_overrides.yaml
- packages/neon/neon_notifications/pubspec_overrides.yaml
- packages/neon/neon_talk/pubspec_overrides.yaml
- packages/neon_framework/lib/src/models/account.dart
- packages/neon_framework/lib/src/storage/sqlite_cookie_persistence.dart
- packages/neon_framework/lib/src/storage/storage_manager.dart
- packages/neon_framework/lib/src/testing/mocks.dart
- packages/neon_framework/pubspec.yaml
- packages/neon_framework/pubspec_overrides.yaml
- packages/neon_framework/test/persistence_test.dart
- packages/nextcloud/pubspec_overrides.yaml
- packages/nextcloud_test/lib/src/test_client.dart
- packages/nextcloud_test/pubspec.yaml
- packages/nextcloud_test/pubspec_overrides.yaml
Tests are missing and the `allowedBaseUri` might not be 100% correct yet but an initial feedback would be appreciated.
The code is written in a way that easily allows us to move it into a separate package.
I wonder if we should already do that or even require our interface in the nextcloud package and force other users to use an adapter if they want to use the cookie_jar interface.
> feat(neon_framework): implement custom cookie store flow 

- packages/neon_framework/lib/src/models/account.dart
https://github.com/nextcloud/neon/pull/1907/commits/e82b46964cb4e76522e918f55dff3af86dafc428
The NextcloudClient is not even serializable, so json_serializable fails when build_runner is executed.
> fix(neon_framework): Exclude computed fields from Account JSON

- tool/build-app.sh
- tool/build-dev-container.sh
- tool/build/linux.sh
- tool/cloc.sh
- tool/common.sh
- tool/dev.sh
- tool/find-relative-markdown-links.sh
- tool/find-untested-neon-apis.sh
- tool/generate-assets.sh
- tool/generate-docs.sh
- tool/generate-dynamite-e2e-test.sh
- tool/generate-dynamite-petstore-example.sh
- tool/generate-file-icons.sh
- tool/generate-nextcloud-test-presets.sh
- tool/generate-nextcloud.sh
- tool/generate-specs.sh
- tool/send-push-notification-test.sh
- tool/setup.sh
- tool/update-cspell-dictionaries.sh
Not all linux distributions have bash installed at `/bin/bash`. Using the current path to search for the bash executable.
Another idea would be to directly use `/bin/sh` although I did not want to check whether all our scripts are compatible with plain posix shell (I doubt it).
I did succesfully test that this also works on OSX
> fix(tool): search for bash in path

- packages/neon_framework/lib/src/blocs/apps.dart
Closes https://github.com/nextcloud/neon/issues/814
Unfortunately I can not add tests in this PR because the whole bloc is not tested yet. Just verifying manually that this works should be enough though.
> feat(neon_framework): Respect the configured apps order

- packages/dynamite/dynamite/lib/dynamite.dart
- packages/dynamite/dynamite_runtime/lib/built_value.dart
- packages/dynamite/dynamite_runtime/lib/http_client.dart
- packages/dynamite/dynamite_runtime/lib/models.dart
- packages/dynamite/dynamite_runtime/lib/utils.dart
- packages/neon/neon_dashboard/lib/neon_dashboard.dart
- packages/neon/neon_files/lib/neon_files.dart
- packages/neon/neon_news/lib/neon_news.dart
- packages/neon/neon_notes/lib/neon_notes.dart
- packages/neon/neon_notifications/lib/neon_notifications.dart
- packages/neon/neon_talk/lib/neon_talk.dart
- packages/neon_framework/lib/models.dart
- packages/neon_lints/lib/src/base.yaml
fixes the `unnecessary_library_name` rule.
I initially thought that this might be breaking but according to the lint documentation:
> The only use of a library name is for a `part` file to refer back to its owning library, but part files should prefer to use a string URI to refer back to the library file, not a library name.
> chore: update lints to dart 3.4.0

- packages/neon/neon_talk/lib/src/widgets/rich_object/file.dart
- packages/neon/neon_talk/lib/src/widgets/rich_object/file_preview.dart
- packages/neon/neon_talk/test/rich_object_test.dart
Fixes https://github.com/nextcloud/neon/issues/2045
I should have add tests for the preview size calculations from the start...
> fix(neon_talk): Ensure constraints for rich object file previews are set correctly

- tool/build-app.sh
Fixes https://github.com/nextcloud/neon/issues/2104
For some reasons the pub stdout started [containing messages like `'MSG : Logs written to /home/runner/.pub-cache/log/pub_log.txt./lib'`](https://github.com/nextcloud/neon/actions/runs/9313314365/job/25635538275) which were added as paths, but obviously they don't exist so this made the mounting fail.
This just filters all lines that are actually paths, so no other logs can sneak in there.
> fix(tool): Filter out logs in build-app script when getting mounts

- packages/neon/neon_dashboard/test/set_weather_location_dialog_test.dart
- packages/neon/neon_dashboard/test/widget_test.dart
Simple wins to increase code coverage.
> test(neon_dashboard): Test for widget item without iconUrl

- .github/workflows/dart.yml
- tool/common.sh
Fixes https://github.com/nextcloud/neon/issues/2128
Forks now skip pushing the images which was always failing: https://github.com/nextcloud/neon/actions/runs/9378866792/job/25822785309?pr=2130
And running on this repo still pushes the images to the cache: https://github.com/nextcloud/neon/actions/runs/9378920660/job/25822950408?pr=2131
> fix(tool): Skip pushing docker images when PR is from a fork

- packages/neon/neon_notifications/lib/neon_notifications.dart
Fixes https://github.com/nextcloud/neon/issues/2125
Using the public interface is how it should be done as the framework and other apps might want to access it too, but the AppImplementation was only advertising it as the internal interface.
> fix(neon_notifications): Expose Bloc using public interface

- packages/neon/neon_talk/lib/src/widgets/rich_object/file_preview.dart
- packages/neon/neon_talk/test/rich_object_test.dart
In case the image width was still too big after rescaling the image by the height it needs to be rescaled again by the width to ensure the constraints are always correct.
Also reworked the tests to do the calculations on the fly as I couldn't even understand myself what I wrote there just a few days ago...
Best reviewed with https://github.com/nextcloud/neon/pull/2136/files?w=1
> fix(neon_talk): Rescale rich object file preview if width is too big

- packages/neon/neon_files/lib/src/pages/main.dart
- packages/neon/neon_files/lib/src/widgets/browser_view.dart
- packages/neon/neon_news/lib/src/pages/article.dart
- packages/neon/neon_news/lib/src/pages/main.dart
- packages/neon/neon_news/lib/src/widgets/articles_view.dart
- packages/neon/neon_notes/lib/src/pages/main.dart
- packages/neon/neon_notes/lib/src/pages/note.dart
- packages/neon/neon_notifications/lib/src/pages/main.dart
- packages/neon/neon_talk/lib/src/pages/main.dart
- packages/neon_framework/lib/src/blocs/apps.dart
- packages/neon_framework/lib/src/blocs/next_push.dart
- packages/neon_framework/lib/src/blocs/unified_search.dart
- packages/neon_framework/lib/src/pages/home.dart
- packages/neon_framework/lib/src/pages/login_flow.dart
- packages/neon_framework/lib/src/pages/settings.dart
- packages/neon_framework/lib/src/settings/widgets/option_settings_tile.dart
- packages/neon_framework/lib/src/widgets/dialog.dart
- packages/neon_framework/lib/src/widgets/drawer.dart
This should be all of them. I chose not to add subscriptions inside blocs where we also manage the stream controller. The controller and subscription would be disposed at the same time anyway and thus we can just close the controller and call it a day.
> fix: Dispose all state and cancel all stream subscriptions

- packages/neon/neon_talk/lib/src/widgets/reactions.dart
The reactions widget always filled the full width of the message. If you put the cursor into the window and then scrolled up the reactions for all messages were loaded because the hover was triggered.
> fix(neon_talk): Shrink reactions width to avoid unnecessary reactions loading on hover

- packages/dynamite/dynamite_runtime/lib/src/client/response.dart
- packages/neon_framework/lib/src/storage/request_cache.dart
- packages/neon_framework/lib/src/utils/request_manager.dart
- packages/neon_framework/test/persistence_test.dart
- packages/neon_framework/test/request_manager_test.dart
Closes https://github.com/nextcloud/neon/issues/2160
I didn't do any performance comparisons (maybe @Leptopoda you can do that on one of your aging devices?), but at least the image flickering seems to be less which would indicate the cache is faster for binary data.
> perf(neon_framework): Store cached requests as BLOB

- packages/dynamite/dynamite/lib/src/builder/client.dart
Fixes CI failure https://github.com/nextcloud/neon/actions/runs/9523085914/job/26253858939?pr=2173
The warning was added in collection 1.19.0.
> chore(dynamite): Fix deprecation warning

- packages/dynamite/dynamite/lib/src/builder/resolve_enum.dart
- packages/dynamite/dynamite/lib/src/builder/resolve_interface.dart
- packages/dynamite/dynamite/lib/src/builder/resolve_object.dart
- packages/dynamite/dynamite/lib/src/builder/resolve_ofs.dart
- packages/dynamite/dynamite/lib/src/builder/resolve_type.dart
- packages/dynamite/dynamite/lib/src/builder/serializer.dart
- packages/dynamite/dynamite/lib/src/builder/state.dart
- packages/dynamite/dynamite/lib/src/models/type_result/type_result.dart
- packages/dynamite/dynamite_end_to_end_test/lib/types.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/types.openapi.g.dart
- packages/dynamite/dynamite_end_to_end_test/lib/types.openapi.json
- packages/nextcloud/lib/src/api/core.openapi.dart
- packages/nextcloud/lib/src/api/core.openapi.g.dart
- packages/nextcloud/lib/src/api/provisioning_api.openapi.dart
- packages/nextcloud/lib/src/api/provisioning_api.openapi.g.dart
- packages/nextcloud/lib/src/api/spreed.openapi.dart
- packages/nextcloud/lib/src/api/spreed.openapi.g.dart
Technically these are two separate fixes, but one doesn't work without the other, so I kept them together.
1. The serializers have to be handled separately, because the type equality check of TypeResult doesn't consider the the nullability, while it is important for the serializer. Making the check consider the nullability would result in duplicate types generated in the code as those don't care about the nullability in the end, so that is not possible.
2. The other part was simply allowing to generate types with nullable generics.
> fix(dynamite)!: Handle nullable generics and serializers correctly

- packages/neon/neon_talk/lib/src/widgets/rich_object/file_preview.dart
- packages/neon/neon_talk/test/rich_object_test.dart
Fixes https://github.com/nextcloud/neon/issues/2166
Previews for animated GIFs are not animated, so we have to request the full file.
I'm pretty sure this is an upstream bug, I already asked if this behavior is intended.
The web frontend is not affected because it always requests the full file instead of the preview (which is pretty inefficient because the images are usually displayed in a lot smaller resolution than the original file).
> fix(neon_talk): Fix animated GIFs not being animated inside chat messages

- packages/neon_framework/lib/neon.dart
- packages/neon_framework/lib/src/utils/timezone.dart
Fixes https://github.com/nextcloud/neon/issues/2147
I'm not 100% sure this is the correct way to fix it, but the available flutter plugins for getting the device timezone all don't work anymore.
The only problem I can imagine is that a location without DST is picked, but then while the app is running the actual location changes it's timezone due to DST and the user would get wrong times displayed. I'm not sure if that can actually happen, but I think it is still better to have this super tiny chance of wrong time display over everything being displayed in UTC as it is right now.
> fix(neon_framework): Use the local timezone

- packages/neon_framework/lib/src/blocs/accounts.dart
- packages/neon_framework/lib/src/models/account.dart
- packages/neon_framework/lib/src/models/account_cache.dart
- packages/neon_framework/lib/src/pages/login_check_account.dart
- packages/neon_framework/test/account_cache_test.dart
Fixes https://github.com/nextcloud/neon/issues/741
There were two problems:
1. AccountCache only compared by ID, so pruneAgainst never removed "old" Blocs since the ID was still the same after updating an Account.
2. The HomePage and everything below it still had references to the "old" Blocs, so a force refresh is necessary.
> Correctly refresh everything after updating Account credentials

- packages/neon/neon_dashboard/lib/src/blocs/dashboard.dart
- packages/neon/neon_files/lib/src/blocs/browser.dart
- packages/neon/neon_files/lib/src/widgets/file_preview.dart
- packages/neon/neon_news/lib/src/blocs/articles.dart
- packages/neon/neon_news/lib/src/blocs/news.dart
- packages/neon/neon_notes/lib/src/blocs/notes.dart
- packages/neon/neon_notifications/lib/src/blocs/notifications.dart
- packages/neon/neon_talk/lib/src/blocs/room.dart
- packages/neon/neon_talk/lib/src/blocs/talk.dart
- packages/neon/neon_talk/lib/src/widgets/rich_object/file_preview.dart
- packages/neon/neon_talk/lib/src/widgets/room_avatar.dart
- packages/neon/neon_talk/test/rich_object_test.dart
- packages/neon_framework/lib/src/blocs/apps.dart
- packages/neon_framework/lib/src/blocs/capabilities.dart
- packages/neon_framework/lib/src/blocs/unified_search.dart
- packages/neon_framework/lib/src/blocs/user_details.dart
- packages/neon_framework/lib/src/blocs/user_status.dart
- packages/neon_framework/lib/src/blocs/weather_status.dart
- packages/neon_framework/lib/src/storage/request_cache.dart
- packages/neon_framework/lib/src/utils/push_utils.dart
- packages/neon_framework/lib/src/utils/request_manager.dart
- packages/neon_framework/lib/src/widgets/image.dart
- packages/neon_framework/lib/src/widgets/user_avatar.dart
- packages/neon_framework/test/image_test.dart
- packages/neon_framework/test/persistence_test.dart
- packages/neon_framework/test/request_manager_test.dart
https://github.com/nextcloud/neon/issues/2155
I'm not sure myself if hashing the request is the best way, as it makes it a lot harder to understand the data that is stored in the cache. OTOH storing all those request parameters in the cache is tedious and we rarely or even never need to inspect the cached data, so it feels a bit pointless.
> refactor(neon_framework): Compute RequestManager cache keys automatically

- packages/nextcloud/lib/src/api/notes.openapi.dart
- packages/nextcloud/lib/src/api/notes.openapi.json
I hope that I did not misread the php code but it looks like it always returns an empty array.
https://github.com/nextcloud/notes/blob/b8d90049ef51a2b80dbb10e756c01fdd139c6135/lib/Controller/NotesController.php#L301-L309
> fix(nextcloud): notes api returns empty array when deleting a note

- packages/dynamite/dynamite_end_to_end_test/test/authentication_test.dart
- packages/dynamite/dynamite_end_to_end_test/test/parameters_test.dart
- packages/dynamite/dynamite_end_to_end_test/test/request_body_test.dart
- packages/dynamite/dynamite_runtime/lib/src/client/response.dart
- packages/dynamite/dynamite_runtime/pubspec.yaml
- packages/neon/neon_dashboard/test/bloc_test.dart
- packages/neon/neon_notifications/test/bloc_test.dart
- packages/neon/neon_talk/test/bloc_test.dart
- packages/neon/neon_talk/test/create_room_dialog_test.dart
- packages/neon/neon_talk/test/message_input_test.dart
- packages/neon/neon_talk/test/room_bloc_test.dart
- packages/neon_framework/test/apps_bloc_test.dart
- packages/neon_framework/test/autocomplete_test.dart
- packages/neon_framework/test/maintenance_mode_bloc_test.dart
- packages/neon_framework/test/unified_search_bloc_test.dart
- packages/neon_framework/test/user_details_bloc_test.dart
- packages/neon_framework/test/user_status_bloc_test.dart
- packages/neon_framework/test/weather_status_bloc_test.dart
Adding back the http_parser dependency :)
> fix(dynamite_runtime): use content type header to deserialize response

- packages/neon/neon_talk/lib/src/blocs/room.dart
- packages/neon/neon_talk/test/room_bloc_test.dart
- packages/nextcloud/test/fixtures/spreed/chat/delete_message.regexp
- packages/nextcloud/test/spreed_test.dart
Fixes https://github.com/nextcloud/neon/issues/2178
Depends on https://github.com/nextcloud/neon/pull/2179
> fix(neon_talk): Update parent messages

- packages/nextcloud/test/weather_status_test.dart
It was a bad idea to make it so precise, for some reason the coordinates we get now are different from the ones we used to get...
> test(nextcloud): Fix weather_status coordinates

- packages/neon_framework/lib/src/pages/login_qr_code.dart
- packages/neon_framework/lib/src/router.dart
- packages/neon_framework/lib/src/router.g.dart
Fixes https://github.com/nextcloud/neon/issues/1706
> fix(neon_framework): Fix QR-Code login routes

- packages/nextcloud/test/spreed_test.dart
A skip in an expect will make the test retry which of course doesn't change anything. Also it should ensure the value, even if it is null, instead of ignoring it.
> test(nextcloud): Remove expect skip

- packages/dynamite/dynamite/example/lib/petstore.openapi.dart
- packages/dynamite/dynamite/lib/src/models/openapi/operation.dart
- packages/dynamite/dynamite_end_to_end_test/lib/documentation.openapi.dart
- packages/dynamite/dynamite_end_to_end_test/lib/documentation.openapi.g.dart
- packages/dynamite/dynamite_end_to_end_test/lib/documentation.openapi.json
- packages/nextcloud/lib/src/api/cookbook.openapi.dart
Fixes https://github.com/nextcloud/neon/issues/2240
> fix(dynamite): Add missing docs about request body

- packages/neon_framework/lib/src/pages/login_qr_code.dart
Fixes https://github.com/nextcloud/neon/issues/2260
Due to only using push the scan page was kept open and the qr code was continuously scanned. This lead to the page being pushed again and again. Replacing the page solves this as the scan widget is then disposed.
> fix(neon_framework): Fix QR-Code login resulting in infinite login loop

- packages/neon/neon_news/lib/src/widgets/articles_view.dart
- packages/neon/neon_news/lib/src/widgets/feeds_view.dart
- packages/neon/neon_news/lib/src/widgets/folders_view.dart
- packages/neon/neon_notes/lib/src/widgets/notes_view.dart
- packages/neon/neon_notifications/lib/src/widgets/notification.dart
- packages/neon/neon_notifications/test/main_page_test.dart
- packages/neon/neon_notifications/test/notification_test.dart
#2158 
1. Neon News 
- Articles (swipe to mark read/unread)
- Folders
- Feeds
2. Neon Notifications 
3. Neon notes
> refactor(neon_news, neon_notes, neon_notifications): replace long press actions with swipe-to-dismiss 

- packages/neon/neon_talk/lib/src/pages/main.dart
- packages/neon/neon_talk/lib/src/utils/helpers.dart
- packages/neon/neon_talk/lib/src/widgets/message.dart
Follow-up to https://github.com/nextcloud/neon/pull/2287.
I originally parse the timestamps as UTC because they were in the nextcloud package where the local timezone might not be desired, but in neon_talk we always want the local timezone.
> refactor(neon_talk): Parse timestamps to local timezone

- packages/nextcloud/test/fixtures/webdav/list_directory.regexp
- packages/nextcloud_test/lib/src/proxy_http_client.dart
Needed for https://github.com/nextcloud/neon/issues/1901
> fix(nextcloud_test): Skip CSRF token requests in fixtures

- packages/nextcloud/test/cookbook_test.dart
- packages/nextcloud/test/fixtures/cookbook/categories/renamecategory.regexp
- packages/nextcloud/test/fixtures/cookbook/recipes/deleterecipe.regexp
- packages/nextcloud/test/fixtures/cookbook/recipes/newrecipe.regexp
- packages/nextcloud/test/fixtures/cookbook/recipes/newrecipe_and_deleterecipe.regexp
Preparation for https://github.com/nextcloud/neon/issues/1901
> test(nextcloud): Reuse container for cookbook tests

- melos.yaml
- packages/neon_framework/lib/src/blocs/login_check_account.dart
- packages/neon_framework/lib/src/blocs/login_check_server_status.dart
- packages/neon_framework/lib/src/blocs/login_flow.dart
- packages/neon_framework/lib/src/models/account.dart
- packages/neon_framework/lib/src/utils/request_manager.dart
- packages/neon_http_client/dart_test.yaml
- packages/neon_http_client/lib/src/interceptors/csrf_interceptor.dart
- packages/neon_http_client/lib/src/interceptors/interceptors.dart
- packages/neon_http_client/lib/src/neon_http_client.dart
- packages/neon_http_client/pubspec.yaml
- packages/neon_http_client/pubspec_overrides.yaml
- packages/neon_http_client/test/client_conformance_test.dart
- packages/neon_http_client/test/interceptors/csrf_interceptor_test.dart
- packages/neon_http_client/test/neon_http_client_test.dart
- packages/nextcloud_test/lib/src/test_client.dart
- pubspec.yaml
The coverage is a bit different from the one reported by the `flutter_test` package, as they both use different coverage collectors.
Let's hope it won't be too off from the current one
> feat(neon_http_client): add csrf interceptor 

- packages/neon/neon_talk/lib/src/widgets/message.dart
- packages/neon/neon_talk/test/message_test.dart
- packages/neon/neon_talk/test/room_page_test.dart
Closes https://github.com/nextcloud/neon/issues/2314
I could go even further and detect if the device doesn't have any mouse attached and then omit the button entirely (instead of whitespace), which would give more space to the message itself. This would probably be a win, since touch devices usually have smaller screens and can make use of the extra space. What do you think?
> feat(neon_talk): Allow using message actions on touch-only devices

- .github/workflows/dart.yml
- packages/neon/neon_news/pubspec.yaml
- packages/neon/neon_notes/pubspec.yaml
- packages/neon_framework/pubspec.yaml
~~The revert is only there to make the CI fail intentionally.~~
Works as expected: [nextcloud/neon/actions/runs/10235365287/job/28316108288?pr=2346](https://github.com/nextcloud/neon/actions/runs/10235365287/job/28316108288?pr=2346)
> ci: Lint code with downgraded dependencies

- .github/renovate.json
Renovate just force pushes https://github.com/nextcloud/neon/pull/2356, so I can remove the unnecessary formatting changes...
> chore(tool): migrate renovate config

- .github/workflows/conventional_commits.yaml
- .github/workflows/dart.yml
- .github/workflows/generate.yaml
- .github/workflows/publish.yaml
- .github/workflows/update_presets.yaml
Dart 3.5 allows the analyzer version 6.8.0 which leads to https://github.com/invertase/dart_custom_lint/issues/261: https://github.com/nextcloud/neon/actions/runs/10272580857/job/28425098327?pr=2360
Pinning the version to 3.4 will fix the problem for now, until we use a Flutter version that uses Dart 3.5.
> ci: Pin Dart SDK version

- packages/nextcloud/test/fixtures/news/items/mark_multiple_articles_as_read_and_unread.regexp
- packages/nextcloud/test/fixtures/news/items/star_and_unstar_multiple_articles.regexp
When testing locally the host is `localhost:8080` and not `localhost`
> test(nextcloud): Fix news fixture not allowing varying hosts

- packages/neon_http_client/pubspec.yaml
- packages/nextcloud/pubspec.yaml
Pulls in https://github.com/dart-lang/http/pull/1284
> chore(deps): Update http_client_conformance_tests

- packages/neon_framework/lib/src/widgets/user_avatar.dart
The server restricts the valid sizes to 64 and 512: https://github.com/nextcloud/server/blob/21db61817467169d225af1e4a96bb37f9feaf70e/core/Controller/AvatarController.php#L70-L80
To avoid multiple cache entries with the same content we can already apply this limitation on the client side.
> fix(neon_framework): Only request avatars in valid sizes

- packages/app/web/flutter_bootstrap.js
Fixes https://github.com/nextcloud/neon/issues/2382
> fix(app): Add custom bootstrapping to bring back web color emojis

- packages/neon_framework/packages/files_app/lib/src/blocs/browser.dart
- packages/neon_framework/packages/files_app/lib/src/blocs/files.dart
- packages/neon_framework/packages/files_app/lib/src/pages/main.dart
- packages/neon_framework/packages/files_app/lib/src/utils/dialog.dart
- packages/neon_framework/packages/files_app/lib/src/widgets/browser_view.dart
- packages/neon_framework/packages/files_app/lib/src/widgets/dialog.dart
- packages/neon_framework/packages/files_app/lib/src/widgets/file_list_tile.dart
- packages/neon_framework/packages/files_app/lib/src/widgets/navigator.dart
Simplifies the Bloc structure and improves the overall architecture of the Files app.
This is probably the right moment to add tests for everything, but that will be quite some effort.
Even without tests this can be reviewed and tested already.
> refactor(files_app): Restructure Blocs

- packages/neon_framework/lib/src/blocs/maintenance_mode.dart
- packages/neon_framework/lib/src/models/push_notification.dart
- packages/neon_framework/lib/src/pages/login_check_server_status.dart
- packages/neon_framework/lib/src/widgets/user_avatar.dart
- packages/neon_framework/packages/files_app/lib/src/blocs/browser.dart
- packages/neon_framework/packages/files_app/lib/src/blocs/files.dart
- packages/neon_framework/packages/files_app/lib/src/models/file_details.dart
- packages/neon_framework/packages/files_app/lib/src/pages/main.dart
- packages/neon_framework/packages/files_app/lib/src/sort/files.dart
- packages/neon_framework/packages/files_app/lib/src/utils/dialog.dart
- packages/neon_framework/packages/files_app/lib/src/utils/task.dart
- packages/neon_framework/packages/files_app/lib/src/widgets/actions.dart
- packages/neon_framework/packages/files_app/lib/src/widgets/browser_view.dart
- packages/neon_framework/packages/files_app/lib/src/widgets/dialog.dart
- packages/neon_framework/packages/files_app/lib/src/widgets/file_list_tile.dart
- packages/neon_framework/packages/files_app/lib/src/widgets/file_preview.dart
- packages/neon_framework/packages/files_app/lib/src/widgets/navigator.dart
- packages/neon_framework/packages/neon_http_client/lib/src/interceptors/csrf_interceptor.dart
- packages/neon_framework/packages/news_app/lib/src/utils/dialog.dart
- packages/neon_lints/example/lib/neon_lints.dart
- packages/neon_lints/example/pubspec.yaml
- packages/neon_lints/example/pubspec_overrides.yaml
- packages/neon_lints/lib/neon_lints.dart
- packages/neon_lints/lib/src/prefer_prefixed_nextcloud_import.dart
Avoids namespace pollution and is already the way it is done almost everywhere (except for the files app it seems).
> feat(neon_lints): Add rule to prefer prefixed nextcloud imports

- packages/neon_framework/analysis_options.yaml
- packages/neon_framework/lib/src/models/account.dart
- packages/neon_framework/lib/src/models/push_notification.g.dart
- packages/neon_framework/packages/dashboard_app/analysis_options.yaml
- packages/neon_framework/packages/files_app/analysis_options.yaml
- packages/neon_framework/packages/news_app/analysis_options.yaml
- packages/neon_framework/packages/notes_app/analysis_options.yaml
- packages/neon_framework/packages/notifications_app/analysis_options.yaml
- packages/neon_framework/packages/talk_app/analysis_options.yaml
- packages/neon_lints/lib/src/base.yaml
- packages/neon_lints/lint_maker.yaml
- packages/nextcloud/analysis_options.yaml
> fix(neon_framework): build issue due to error in generated files

- packages/cookie_store/dart_test.yaml
- packages/cookie_store/lib/src/cookie_persistence.dart
- packages/cookie_store/lib/src/cookie_store.dart
- packages/cookie_store/packages/cookie_store_conformance_tests/lib/src/utils.dart
- packages/cookie_store/packages/cookie_store_conformance_tests/pubspec.yaml
- packages/cookie_store/pubspec.yaml
The `Cookie` does not depend on the dart vm and is therefore also usable on web.
To verify this, I've also enabled unit tests on chrome.
> refactor(cookie_store): remove universal_io dependency.

- packages/neon_framework/lib/src/pages/login_flow.dart
- packages/neon_framework/lib/src/utils/launch_url.dart
Using the active account could be going wrong in two ways:
1. no account in the context (first login), error
2. account preset, but it's an already existing one and not the one we want to log into
Given https://github.com/nextcloud/neon/pull/2407 I'm not adding a test for this right now.
There is no other place where we call launchUrl() and possibly give it no/a wrong account.
> fix(neon_framework): Fix login flow not launching URL

- packages/nextcloud/lib/src/api/webdav/models/webdav.dart
- packages/nextcloud/lib/src/api/webdav/models/webdav.g.dart
- packages/nextcloud/test/api/webdav/webdav_test.dart
- packages/nextcloud/test/fixtures/webdav/create_share.regexp
- packages/nextcloud/test/fixtures/webdav/set_and_get_tags.regexp
Fixes https://github.com/nextcloud/neon/issues/2410
Just some stupid copy-pasta. To be fair the code in that file is not really readable because of all the annotations, fields and parameters...
> fix(nextcloud): Use correct WebDAV namespaces for oc:checksum, oc:share-type and oc:tags

- .github/workflows/publish.yaml
Same as https://github.com/nextcloud/neon/pull/2435, but from me :P
> ci: Use patched fdroidserver to fix publish workflow

- packages/nextcloud/lib/src/api/webdav/webdav_client.dart
- packages/nextcloud/test/api/webdav/webdav_test.dart
- packages/nextcloud/test/fixtures/webdav/upload_file_with_checksum.regexp
Extracted from https://github.com/nextcloud/neon/pull/2431
> feat(nextcloud): Add support for checksums for uploading WebDAV files

- packages/dynamite/lib/src/builder/resolve_interface.dart
- packages/dynamite/packages/dynamite_end_to_end_test/lib/interfaces.openapi.dart
- packages/dynamite/packages/dynamite_end_to_end_test/lib/interfaces.openapi.g.dart
- packages/dynamite/packages/dynamite_end_to_end_test/lib/interfaces.openapi.json
New field in Nextcloud 30 starts with a `$`
> fix(dynamite): Escape wireNames

- .github/workflows/publish.yaml
https://gitlab.com/fdroid/fdroidserver/-/merge_requests/1512
is in master now
> chore(ci): for android publish use master fdroidserver again

- packages/nextcloud/lib/src/api/webdav/models/webdav.dart
- packages/nextcloud/lib/src/api/webdav/models/webdav.g.dart
- packages/nextcloud/lib/src/api/webdav/webdav_client.dart
- packages/nextcloud/test/api/webdav/webdav_test.dart
- packages/nextcloud/test/fixtures/webdav/extended_mkcol.regexp
Closes https://github.com/nextcloud/neon/issues/512
> feat(nextcloud): Implement WebDAV extended MKCOL

- packages/nextcloud/packages/nextcloud_test_presets/docker/Dockerfile
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/cookbook/0.11
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/drop_account/2.4
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/drop_account/2.5
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/drop_account/2.6
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/news/25.0
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/notes/4.10
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/notes/4.8
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/notes/4.9
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/server/28.0
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/server/29.0
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/spreed/18.0
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/spreed/19.0
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/tables/0.6
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/tables/0.7
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/tables/0.8
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/uppush/1.4
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/uppush/1.5
- packages/nextcloud/packages/nextcloud_test_presets/lib/src/generate_presets.dart
- packages/nextcloud/packages/nextcloud_test_presets/lib/src/models/app.dart
- packages/nextcloud/packages/nextcloud_test_presets/lib/src/models/app_release.dart
- packages/nextcloud/packages/nextcloud_test_presets/lib/src/models/models.dart
- packages/nextcloud/packages/nextcloud_test_presets/lib/src/models/server_release.dart
Locally it helps docker a lot to detect that images didn't change and it should also help in CI to avoid unnecessary build time.
The only downside is that we get more preset updates, but it's not too often and the benefits outweigh this downside.
> perf(nextcloud_test_presets): Use docker image digests to improve caching

- packages/neon_framework/packages/account_repository/test/utils/http_client_builder_test.dart
- packages/neon_framework/packages/neon_http_client/lib/src/interceptors/authorization_throttling_interceptor.dart
- packages/neon_framework/packages/neon_http_client/lib/src/interceptors/http_interceptor.dart
- packages/neon_framework/packages/neon_http_client/lib/src/neon_http_client.dart
- packages/neon_framework/packages/neon_http_client/test/interceptors/authorization_throttling_interceptor_test.dart
- packages/neon_framework/packages/neon_http_client/test/neon_http_client_test.dart
Closes https://github.com/nextcloud/neon/issues/365
Quite simple to implement with our interceptors :smile:
Every Account gets it's own NeonHttpClient and therefore it's own AuthenticationInterceptor, so no separation is required.
I removed the catch handlers because the interceptor needs to be able to throw an exception for requests that need to be blocked.
> feat(neon_http_client): Add AuthenticationInterceptor

- packages/neon_framework/packages/news_app/lib/src/widgets/articles_view.dart
- packages/neon_framework/packages/news_app/lib/src/widgets/feed_icon.dart
https://github.com/nextcloud/neon/pull/2448 accidentally removed the size constraint which lead to some jumping around while loading the icons.
> fix(news_app): Apply size constraint in NewsFeedIcon

- packages/neon_framework/lib/src/settings/models/exportable.dart
- packages/neon_framework/lib/src/settings/models/option.dart
- packages/neon_framework/test/option_test.dart
- packages/neon_framework/test/options_collection_test.dart
Fixes https://github.com/nextcloud/neon/issues/1749
The problem was that the load operation didn't trigger a save, so the values were just lost.
> fix(neon_framework): Fix settings import

- packages/neon_framework/lib/src/router.dart
I forgot that go_router will cache the route you are already on.
This fixes the 401 issues I had when switching accounts.
> fix(neon_framework): account switching

- packages/neon_framework/packages/account_repository/lib/src/account_repository.dart
- packages/neon_framework/packages/account_repository/test/account_repository_test.dart
This is how it used to work before and it is a lot more intuitive to the user as they otherwise might think the account was not added properly.
> fix(account_repository): Change active account after logging in with a new one

- packages/neon_framework/packages/talk_app/lib/src/widgets/message.dart
- packages/neon_framework/packages/talk_app/test/message_test.dart
Message text selection is broken in different ways on both mobile and desktop, so removing it for now.
> fix(talk_app): Remove broken message text selection

- packages/neon_framework/packages/files_app/lib/src/utils/task.dart
- packages/nextcloud/lib/src/api/webdav/webdav_client.dart
- packages/nextcloud/test/api/webdav/webdav_test.dart
Fixes https://github.com/nextcloud/neon/issues/2307
> fix(nextcloud)!: Throw DynamiteStatusCodeExceptions for invalid WebDAV status codes

- packages/neon_framework/packages/talk_app/lib/src/widgets/message.dart
- packages/neon_framework/packages/talk_app/test/message_test.dart
WidgetSpan+Text lead to weird results when there was a rich object that was hidden due to overflow. Just using a TextSpan directly is more performant and correctly handles the overflow.
> fix(talk_app): Fix text overflow in message preview with rich object

- packages/neon_framework/lib/src/blocs/push_notifications.dart
- packages/neon_framework/lib/src/testing/mock_server.dart
- packages/neon_framework/lib/src/testing/mocks.dart
- packages/neon_framework/lib/src/utils/account_client_extension.dart
- packages/neon_framework/lib/src/widgets/error.dart
- packages/neon_framework/packages/account_repository/lib/src/account_repository.dart
- packages/neon_framework/packages/account_repository/lib/src/models/account.dart
- packages/neon_framework/packages/account_repository/lib/src/models/credentials.dart
- packages/neon_framework/packages/account_repository/lib/src/models/credentials.g.dart
- packages/neon_framework/packages/account_repository/lib/src/models/login_qr_code.dart
- packages/neon_framework/packages/account_repository/lib/src/testing/testing_credentials.dart
- packages/neon_framework/packages/account_repository/lib/src/utils/http_client_builder.dart
- packages/neon_framework/packages/account_repository/test/account_repository_test.dart
- packages/neon_framework/packages/account_repository/test/account_storage_test.dart
- packages/neon_framework/packages/account_repository/test/models/account_test.dart
- packages/neon_framework/packages/account_repository/test/models/credentials_test.dart
- packages/neon_framework/packages/account_repository/test/models/login_qr_code_test.dart
- packages/neon_framework/packages/account_repository/test/utils/http_client_builder_test.dart
- packages/neon_framework/packages/talk_app/lib/src/widgets/rich_object/file.dart
- packages/neon_framework/test/login/bloc/login_bloc_test.dart
- packages/neon_framework/test/login/bloc/login_state_test.dart
- packages/neon_framework/test/login_qr_code/bloc/login_qr_code_bloc_test.dart
- packages/neon_framework/test/login_qr_code/bloc/login_qr_code_state_test.dart
- packages/neon_framework/test/utils/account_client_extension_test.dart
As discussed in the initial account_repository PR (https://github.com/nextcloud/neon/pull/2403#discussion_r1720686033).
> refactor(neon_framework): rename credentials password to appPassowrd

- .github/workflows/generate.yaml
Fails: https://github.com/nextcloud/neon/actions/runs/11065409908/job/30744783500?pr=2521
Introduced by https://github.com/nextcloud/neon/pull/2517
> ci: Fix installing yq

- packages/cookie_store/lib/src/storable_cookie.dart
- packages/neon_framework/lib/src/bloc/result.dart
- packages/neon_framework/lib/src/settings/models/exportable.dart
- packages/neon_framework/lib/src/settings/models/option.dart
- packages/neon_framework/lib/src/settings/utils/settings_export_helper.dart
- packages/neon_framework/lib/src/theme/icons.dart
- packages/neon_lints/lib/src/base.yaml
- packages/neon_lints/lint_maker.yaml
I disabled `document_ignores` for now as it would be too much effort to document all of them now.
> feat(neon_lints): update lints

- .github/workflows/publish.yaml
Regression from https://github.com/nextcloud/neon/pull/2517
Fixes https://github.com/nextcloud/neon/actions/runs/11119127833/job/30893832380#step:7:14
[Action default is 33.0.0](https://github.com/ilharp/sign-android-release/tree/master?tab=readme-ov-file#inputs) while the [Ubuntu 24.04 image only has 34.0.0 and 35.0.0](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#android)
Also discovered https://gitlab.com/fdroid/fdroidserver/-/issues/1192 so the install method for fdroidserver was fixed as well.
> ci: Fix Android signing by using pre-installed build-tools version

- .github/workflows/dart.yml
- .github/workflows/generate.yaml
Just learned about the `--exit-code` option last week, so if there is any diff it will automatically show it and fail as well.
> ci: Simplify git diff checks

- packages/neon_framework/lib/l10n/en.arb
- packages/neon_framework/lib/l10n/localizations.dart
- packages/neon_framework/lib/l10n/localizations_en.dart
When receiving push notifications the app ID will be `spreed` so we need a localization for that ID such that it can be correctly displayed in the Android notification channel list and the notification title.
> fix(neon_framework): Add localization for spreed app ID

- packages/nextcloud/packages/nextcloud_test_presets/docker/Dockerfile
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/cookbook/0.11
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/drop_account/2.4
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/drop_account/2.5
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/drop_account/2.6
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/news/25.0
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/notes/4.10
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/notes/4.11
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/notes/4.8
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/notes/4.9
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/spreed/18.0
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/spreed/19.0
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/spreed/20.0
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/tables/0.6
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/tables/0.7
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/tables/0.8
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/uppush/1.4
- packages/nextcloud/packages/nextcloud_test_presets/docker/presets/uppush/1.5
- packages/nextcloud/packages/nextcloud_test_presets/lib/src/generate_presets.dart
- packages/nextcloud/packages/nextcloud_test_presets/lib/src/models/app_release.dart
- packages/nextcloud/packages/nextcloud_test_presets/pubspec.yaml
Ensures we always download a valid file and that the release can not be replaced without noticing it.
> feat(nextcloud_test_presets): Add and verify app release checksums

- packages/neon_framework/packages/account_repository/lib/src/models/credentials.dart
- packages/nextcloud/lib/src/api/webdav/models/webdav_file.dart
- packages/nextcloud/test/api/webdav/models/webdav_file_test.dart
Might fix https://github.com/saber-notes/saber/issues/772
> fix(nextcloud): Fix WebDav path calculations for instances hosted at subpaths

- CHANGELOG.md
- packages/neon_framework/example/pubspec.lock
- packages/neon_framework/packages/account_repository/pubspec.yaml
- packages/neon_framework/packages/dashboard_app/pubspec.yaml
- packages/neon_framework/packages/files_app/pubspec.yaml
- packages/neon_framework/packages/neon_http_client/pubspec.yaml
- packages/neon_framework/packages/neon_storage/pubspec.yaml
- packages/neon_framework/packages/news_app/pubspec.yaml
- packages/neon_framework/packages/notes_app/pubspec.yaml
- packages/neon_framework/packages/notifications_app/pubspec.yaml
- packages/neon_framework/packages/notifications_push_repository/pubspec.yaml
- packages/neon_framework/packages/talk_app/pubspec.yaml
- packages/neon_framework/pubspec.yaml
- packages/neon_lints/example/pubspec.yaml
- packages/nextcloud/CHANGELOG.md
- packages/nextcloud/packages/nextcloud_test/pubspec.yaml
- packages/nextcloud/packages/nextcloud_test_presets/pubspec.yaml
- packages/nextcloud/pubspec.yaml
> chore(release): publish packages

- .cspell/nextcloud.txt
- packages/nextcloud/packages/nextcloud_test/lib/nextcloud_test.dart
- packages/nextcloud/packages/nextcloud_test/lib/src/matchers/webdav_props.dart
- packages/nextcloud/packages/nextcloud_test/lib/src/presets.dart
- packages/nextcloud/packages/nextcloud_test/pubspec.yaml
- packages/nextcloud/test/api/webdav/webdav_test.dart
- packages/nextcloud/test/fixtures/webdav/get_directory_props.regexp
- packages/nextcloud/test/fixtures/webdav/get_file_props.regexp
This is going to become a lot more useful when https://github.com/sabre-io/dav/pull/1564 is merged and in a released Nextcloud version, as we are currently missing out on a lot of props when requesting all available props.
> test(nextcloud): Add checks to ensure that all available props are parsed

- packages/neon_framework/lib/src/utils/push_utils.dart
- packages/neon_framework/test/push_utils_test.dart
Fixes https://github.com/nextcloud/neon/issues/2581
I know it's not perfect yet, but it avoids getting spammed by push notifications if there are multiple.
> fix(neon_framework): Group push notifications on Android

- packages/neon_framework/example/de.provokateurin.neon.yaml
22.08 is no longer maintained and trying to run the app with the old SDK leads to `nextcloud-neon: symbol lookup error: nextcloud-neon: undefined symbol: g_once_init_enter_pointer` on my system.
> fix(neon_framework): Bump example flatpak SDK

- .cspell/tools.txt
- packages/neon_framework/example/linux/my_application.cc
Copied from https://github.com/flutter/flutter/pull/154522
Now the icon properly shows up for the flatpak:
> fix(example): Fix window icon on wayland

- .cspell/nextcloud.txt
- packages/neon_framework/lib/src/utils/push_utils.dart
- packages/neon_framework/test/push_utils_test.dart
- packages/nextcloud/lib/src/api/notifications/notifications_helpers.dart
- packages/nextcloud/lib/src/api/notifications/notifications_helpers.g.dart
I discovered this while investigating https://github.com/nextcloud/neon/issues/2591 (I even first thought this was the initial problem).
Added documentation upstream (https://github.com/nextcloud/notifications/pull/2089) because it was not documented back when it was added (https://github.com/nextcloud/notifications/pull/1429).
> fix(neon_framework): Handle delete-multiple background push notifications

- packages/neon_framework/lib/src/utils/push_utils.dart
- packages/neon_framework/test/push_utils_test.dart
Closes https://github.com/nextcloud/neon/issues/2600
Before/After:
> feat(neon_framework): Use big text style for push notifications

- .github/renovate.json
should unblock #2596 and #2559
> fix(tool): Group custom_lint packages in renovate config

- tool/dev.sh
I've been experience DNS issues within the docker quite a few times and using the host network fixes it reliably.
> fix(tool): Use host network for dev container

- packages/neon_framework/packages/neon_http_client/lib/src/interceptors/authorization_throttling_interceptor.dart
- packages/neon_framework/packages/neon_http_client/pubspec.yaml
- packages/neon_framework/packages/neon_http_client/test/interceptors/authorization_throttling_interceptor_test.dart
The detection flagged some responses that were fine (even though I believe nothing should really use the 401 status code except the authentication middleware), which resulted in the app becoming unusable due to the blocking.
I limited it to OCS responses for now as most requests use that format and we can correctly detect invalid credentials 100% of the time through the custom status code 997.
For non-OCS APIs and WebDAV it might be possible as well, but I think they are not so important and we can add them if ever needed.
I know there are those really ugly nested if blocks, but the alternative would be to chain null-aware casts and I don't think that is much better than this.
> fix(neon_http_client): Make authorization throttling less agressive

- packages/neon_framework/lib/src/widgets/rich_text/file.dart
- packages/neon_framework/test/rich_text_test.dart
Closes https://github.com/nextcloud/neon/issues/2411
This was too easy :sweat_smile:
> feat(neon_framework): Display blurhash for rich text file previews

- packages/neon_framework/packages/talk_app/lib/src/blocs/room.dart
Fixes https://github.com/nextcloud/neon/issues/2498
> fix(talk_app): Silence message polling timeout exception

- .github/workflows/dart.yml
- .github/workflows/dependency_overrides.patch
- packages/neon_framework/packages/files_app/pubspec.yaml
- packages/neon_framework/packages/notifications_app/pubspec.yaml
- packages/neon_framework/packages/talk_app/pubspec.yaml
- packages/neon_framework/pubspec.yaml
- packages/nextcloud/pubspec.yaml
Running the tests also ensures the code actually works and it's not just throwing no linting errors.
I only added the overrides to packages with tests as there is no way to automatically verify the overrides fix the build issues otherwise.
There seem to be some runtime issues with flutter_svg and vector_graphics, but I didn't look further into those.
This is only a step in the right direction and to verify that everything is fine with downgraded dependencies we need to have tests for every package.
> ci: Run all Dart steps with both upgraded and downgraded dependencies

- packages/neon_framework/lib/src/login/view/login_view.dart
- packages/neon_framework/test/login/view/login_page_test.dart
Basically the same fix as I did in https://github.com/nextcloud/neon/pull/2200 with the bug being reintroduced in https://github.com/nextcloud/neon/pull/2407.
> fix(neon_framework): Correctly reload after updating account credentials

- .gitmodules
- cspell.json
- packages/neon_framework/example/linux/flutter/generated_plugin_registrant.cc
- packages/neon_framework/example/linux/flutter/generated_plugins.cmake
- packages/neon_framework/example/pubspec.lock
- packages/neon_framework/generate_emojis.dart
- packages/neon_framework/lib/l10n/en.arb
- packages/neon_framework/lib/l10n/localizations.dart
- packages/neon_framework/lib/l10n/localizations_en.dart
- packages/neon_framework/lib/src/utils/emojis.dart
- packages/neon_framework/lib/src/widgets/dialog.dart
- packages/neon_framework/packages/talk_app/lib/src/widgets/message_input.dart
- packages/neon_framework/packages/talk_app/pubspec.yaml
- packages/neon_framework/packages/talk_app/test/message_input_test.dart
- packages/neon_framework/packages/talk_app/test/message_test.dart
- packages/neon_framework/packages/talk_app/test/reactions_test.dart
- packages/neon_framework/pubspec.yaml
- packages/neon_framework/test/dialog_test.dart
- tool/generate-assets.sh
Fixes https://github.com/nextcloud/neon/issues/2499
I thought implementing a custom emoji picker would be hard because all the existing packages suck and are unmaintained, but it turned out it was quite simple in the end.
Because the available emojis are generated from the metadata they are also more complete than what we had before, because the package was manually adding them to a list.
This picker does not support alternates (e.g. skin tones) yet, but it can be added easily.
It also does not save any recently used emojis, but we can add that as well.
Due to having all the metadata available we can now also add shortcode (e.g. `:smile:`) completion for text inputs (e.g. Talk message input) which is pretty neat.
For some reason the Tabbar renders a bit weird on Android and I believe it …
> refactor(neon_framework): Implement a custom emoji picker

- packages/neon_framework/packages/talk_app/lib/src/widgets/reactions.dart
Fixes https://github.com/nextcloud/neon/issues/2671
> fix(talk_app): Fix reactions overflow

- packages/neon_framework/packages/talk_app/lib/src/pages/room.dart
- packages/neon_framework/packages/talk_app/lib/src/utils/helpers.dart
- packages/neon_framework/packages/talk_app/lib/src/widgets/message.dart
- packages/neon_framework/packages/talk_app/lib/src/widgets/reactions.dart
- packages/neon_framework/packages/talk_app/test/room_page_test.dart
Closes https://github.com/nextcloud/neon/issues/2495
> feat(talk_app): Implement swipe-to-reply

- packages/neon_framework/lib/src/widgets/user_avatar.dart
- packages/neon_framework/packages/neon_rich_text/lib/src/rich_objects/mention.dart
- packages/neon_framework/packages/talk_app/lib/src/blocs/talk.dart
- packages/neon_framework/packages/talk_app/lib/src/dialogs/create_room.dart
- packages/neon_framework/packages/talk_app/lib/src/widgets/actor_avatar.dart
- packages/neon_framework/packages/talk_app/lib/src/widgets/message_input.dart
- packages/neon_framework/packages/talk_app/lib/src/widgets/room_avatar.dart
- packages/neon_framework/packages/talk_app/test/create_room_dialog_test.dart
- packages/neon_framework/packages/talk_app/test/message_input_test.dart
- packages/neon_framework/packages/talk_app/test/room_avatar_test.dart
- packages/neon_framework/test/user_avatar_test.dart
Closes https://github.com/nextcloud/neon/issues/2613
> feat(talk_app): Use existing user status data

- packages/neon_framework/example/pubspec.lock
- packages/neon_framework/example/pubspec.yaml
- packages/neon_framework/example/pubspec_overrides.yaml
It got bumped in https://github.com/nextcloud/neon/pull/2712 which triggered https://github.com/miguelpruivo/flutter_file_picker/issues/1643 so we have to downgrade it for now.
> fix(deps): Downgrade file_picker to 8.1.4 to fix Android build errors

- packages/neon_framework/packages/talk_app/lib/src/widgets/message_input.dart
Extracted from https://github.com/nextcloud/neon/pull/2647
> fix(talk_app): Ignore invalid text selection when searching mentions

- .github/workflows/dart.yml
We don't upgrade the dependencies, we take the current ones specified in the pubspec.lock.
It's not that relevant right now as it is basically the same as doing an upgrade, because only the example has a pubspec.lock, but with https://github.com/nextcloud/neon/pull/2704 it will be completely wrong.
> ci: Correctly name Dart job as current dependencies and not upgraded

- packages/neon_framework/example/pubspec.lock
- packages/neon_framework/example/pubspec.yaml
- packages/neon_framework/example/pubspec_overrides.yaml
https://github.com/nextcloud/neon/pull/2713
> chore(deps): Bump file_picker

- pubspec.yaml
For some reason running melos inside a melos hook is currently broken in newer versions. This might be due to contraint differences.
> build: Fix melos hooks

- packages/nextcloud/packages/nextcloud_test/lib/src/models/nextcloud_tester.dart
- packages/nextcloud/packages/nextcloud_test/lib/src/test_target/docker_container.dart
- packages/nextcloud/packages/nextcloud_test/lib/src/test_target/local.dart
- packages/nextcloud/packages/nextcloud_test/lib/src/test_target/test_target.dart
- packages/nextcloud/packages/nextcloud_test_presets/docker/Dockerfile
- packages/nextcloud/test/api/cookbook/cookbook_test.dart
- packages/nextcloud/test/api/news/news_test.dart
- tool/dev.sh
Basically the same as https://github.com/nextcloud/neon/pull/2601.
Also has the benefit that our testing code gets slightly less complicated.
For some reason the tests were still working just fine in CI, but locally the dashboard and weather_status tests were partially failing because the container couldn't connect to the required external services.
> fix(nextcloud_test): Use host network for docker containers

- packages/nextcloud/packages/nextcloud_test/lib/src/test_target/docker_container.dart
Forgotten in https://github.com/nextcloud/neon/pull/2769.
On the host network we don't get the 125 status code anymore if the port was already allocated, but just 1. We can't distinguish that from any other failure, so just using retries should do the trick to avoid false positives in case the port is already used.
> fix(nextcloud_test): Handle port already used with retries

- packages/nextcloud/test/api/spreed/spreed_test.dart
- packages/nextcloud/test/fixtures/spreed/chat/clear_history.regexp
- packages/nextcloud/test/fixtures/spreed/room/message_expiration.regexp
There are some changes in the `lastMessage` data returned in spreed 21 (https://github.com/nextcloud/neon/pull/2775), so adding a test now to serve as regression testing.
> test(nextcloud): Test spreed message expiration

- packages/nextcloud/packages/nextcloud_test/lib/src/test_target/docker_container.dart
https://github.com/nextcloud/neon/pull/2770 wasn't actually working because the exit code was always 0 due to detached mode.
By checking if the container is still running we really know that everything is fine.
I tested this by lowering the range of random ports to 20 so failures are very likely and it managed to properly find a port for each container.
> fix(nextcloud_test): Really handle docker container port already being allocated

- packages/neon_framework/example/android/app/build.gradle
Fixes
```
Your project is configured to compile against Android SDK 34, but the following plugin(s) require to be compiled against a higher Android SDK version:
- flutter_plugin_android_lifecycle compiles against Android SDK 35
Fix this issue by compiling against the highest Android SDK version (they are backward compatible).
```
> build(example): Update Android compileSdkVersion to 35

- .cspell/nextcloud.txt
- packages/nextcloud/packages/nextcloud_test_presets/docker/Dockerfile
Backports were merged and released in 30.0.9 and 31.0.3 already:
https://github.com/nextcloud/server/pull/51719
https://github.com/nextcloud/server/pull/51720
> Revert "fix(nextcloud_test_presets): Fix error in installation process"

- .github/workflows/publish.yaml
Currently wasting a lot of CI time and energy for building every day. The F-Droid repo is broken anyway and always needs a manual reset before a new version can be published.
> ci: Only publish on demand
